# slug -> (es, ar, pt, de, ru). Names: lowercase common nouns except DE capitalization.

NAMES = {
    "snake": ("serpiente", "ثعبان", "cobra", "Schlange", "змея"),
    "black-snake": ("serpiente negra", "ثعبان أسود", "cobra preta", "schwarze Schlange", "чёрная змея"),
    "white-snake": ("serpiente blanca", "ثعبان أبيض", "cobra branca", "weiße Schlange", "белая змея"),
    "green-snake": ("serpiente verde", "ثعبان أخضر", "cobra verde", "grüne Schlange", "зелёная змея"),
    "snake-bite": ("mordedura de serpiente", "لدغة ثعبان", "picada de cobra", "Schlangenbiss", "укус змеи"),
    "dead-snake": ("serpiente muerta", "ثعبان ميت", "cobra morta", "tote Schlange", "мёртвая змея"),
    "many-snakes": ("muchas serpientes", "ثعابين كثيرة", "muitas cobras", "viele Schlangen", "много змей"),
    "big-snake": ("serpiente grande", "ثعبان كبير", "cobra grande", "große Schlange", "огромная змея"),
    "snakes-in-water": ("serpientes en el agua", "ثعابين في الماء", "cobras na água", "Schlangen im Wasser", "змеи в воде"),
    "teeth": ("dientes", "أسنان", "dentes", "Zähne", "зубы"),
    "teeth-falling-out": ("caerse los dientes", "تساقط الأسنان", "dentes caindo", "Zähne fallen aus", "выпадают зубы"),
    "broken-teeth": ("dientes rotos", "أسنان مكسورة", "dentes quebrados", "gebrochene Zähne", "сломанные зубы"),
    "loose-teeth": ("dientes flojos", "أسنان متخلخلة", "dentes moles", "lockere Zähne", "шатаются зубы"),
    "pulling-teeth": ("sacarse un diente", "خلع الأسنان", "arrancar um dente", "Zähne ziehen", "вырывают зубы"),
    "rotten-teeth": ("dientes podridos", "أسنان متعفنة", "dentes podres", "faule Zähne", "гнилые зубы"),
    "losing-teeth": ("perder los dientes", "فقدان الأسنان", "perder os dentes", "Zähne verlieren", "терять зубы"),
    "water": ("agua", "ماء", "água", "Wasser", "вода"),
    "flood": ("inundación", "فيضان", "enchente", "Überschwemmung", "наводнение"),
    "ocean": ("océano", "محيط", "oceano", "Ozean", "океан"),
    "river": ("río", "نهر", "rio", "Fluss", "река"),
    "drowning": ("ahogarse", "غرق", "afogamento", "Ertrinken", "утопление"),
    "dirty-water": ("agua sucia", "ماء وسخ", "água suja", "schmutziges Wasser", "грязная вода"),
    "clear-water": ("agua clara", "ماء صافٍ", "água limpa", "klares Wasser", "чистая вода"),
    "rain": ("lluvia", "مطر", "chuva", "Regen", "дождь"),
    "waterfall": ("cascada", "شلال", "cachoeira", "Wasserfall", "водопад"),
    "death": ("muerte", "موت", "morte", "Tod", "смерть"),
    "someone-dying": ("alguien muriendo", "شخص يحتضر", "alguém morrendo", "jemand stirbt", "кто-то умирает"),
    "dead-person": ("una persona muerta", "شخص ميت", "uma pessoa morta", "ein Toter", "мёртвый человек"),
    "funeral": ("un funeral", "جنازة", "um funeral", "eine Beerdigung", "похороны"),
    "being-killed": ("que te maten", "أن تُقتل", "ser morto", "getötet werden", "тебя убивают"),
    "killing-someone": ("matar a alguien", "قتل شخص", "matar alguém", "jemanden töten", "убить кого-то"),
    "dead-relative": ("un pariente muerto", "قريب متوفى", "um parente morto", "ein verstorbener Verwandter", "умерший родственник"),
    "own-death": ("tu propia muerte", "موتك أنت", "a própria morte", "der eigene Tod", "собственная смерть"),
    "dead-parent": ("un padre o una madre muertos", "والد متوفى", "um pai ou mãe mortos", "ein verstorbener Elternteil", "умерший родитель"),
    "baby": ("bebé", "رضيع", "bebê", "Baby", "младенец"),
    "newborn-baby": ("bebé recién nacido", "مولود جديد", "recém-nascido", "neugeborenes Baby", "новорождённый"),
    "crying-baby": ("bebé llorando", "رضيع يبكي", "bebê chorando", "weinendes Baby", "плачущий младенец"),
    "baby-boy": ("bebé niño", "طفل رضيع", "bebê menino", "männliches Baby", "мальчик-младенец"),
    "baby-girl": ("bebé niña", "طفلة رضيعة", "bebê menina", "weibliches Baby", "девочка-младенец"),
    "holding-a-baby": ("cargar a un bebé", "حمل رضيع", "segurar um bebê", "ein Baby halten", "держать младенца"),
    "lost-baby": ("bebé perdido", "رضيع مفقود", "bebê perdido", "verlorenes Baby", "потерянный младенец"),
    "pregnancy": ("embarazo", "حمل", "gravidez", "Schwangerschaft", "беременность"),
    "being-pregnant": ("estar embarazada", "أن تكوني حاملاً", "estar grávida", "schwanger sein", "быть беременной"),
    "pregnancy-test": ("una prueba de embarazo", "اختبار حمل", "um teste de gravidez", "ein Schwangerschaftstest", "тест на беременность"),
    "giving-birth": ("dar a luz", "ولادة", "dar à luz", "gebären", "роды"),
    "miscarriage": ("aborto espontáneo", "إجهاض", "aborto espontâneo", "Fehlgeburt", "выкидыш"),
    "pregnant-woman": ("una mujer embarazada", "امرأة حامل", "uma mulher grávida", "eine schwangere Frau", "беременная женщина"),
    "pregnant-with-twins": ("embarazada de mellizos", "حامل بتوأم", "grávida de gêmeos", "mit Zwillingen schwanger", "беременна двойней"),
    "dog": ("perro", "كلب", "cachorro", "Hund", "собака"),
    "black-dog": ("perro negro", "كلب أسود", "cachorro preto", "schwarzer Hund", "чёрная собака"),
    "white-dog": ("perro blanco", "كلب أبيض", "cachorro branco", "weißer Hund", "белая собака"),
    "dog-bite": ("mordida de perro", "عضة كلب", "mordida de cachorro", "Hundebiss", "укус собаки"),
    "friendly-dog": ("perro amistoso", "كلب ودود", "cachorro amigável", "freundlicher Hund", "доброжелательная собака"),
    "aggressive-dog": ("perro agresivo", "كلب عدواني", "cachorro agressivo", "aggressiver Hund", "агрессивная собака"),
    "dead-dog": ("perro muerto", "كلب ميت", "cachorro morto", "toter Hund", "мёртвая собака"),
    "cat": ("gato", "قط", "gato", "Katze", "кошка"),
    "black-cat": ("gato negro", "قط أسود", "gato preto", "schwarze Katze", "чёрная кошка"),
    "white-cat": ("gato blanco", "قط أبيض", "gato branco", "weiße Katze", "белая кошка"),
    "cat-attack": ("ataque de gato", "هجوم قط", "ataque de gato", "Katzenangriff", "нападение кошки"),
    "kittens": ("gatitos", "قطط صغيرة", "gatinhos", "Kätzchen", "котята"),
    "dead-cat": ("gato muerto", "قط ميت", "gato morto", "tote Katze", "мёртвая кошка"),
    "flying": ("volar", "طيران", "voar", "Fliegen", "полёт"),
    "flying-high": ("volar alto", "الطيران عالياً", "voar alto", "hoch fliegen", "лететь высоко"),
    "flying-over-water": ("volar sobre el agua", "الطيران فوق الماء", "voar sobre a água", "über Wasser fliegen", "лететь над водой"),
    "flying-without-wings": ("volar sin alas", "الطيران بلا جناحين", "voar sem asas", "ohne Flügel fliegen", "лететь без крыльев"),
    "falling-while-flying": ("caer mientras vuelas", "السقوط أثناء الطيران", "cair enquanto voa", "beim Fliegen stürzen", "падение во время полёта"),
    "falling": ("caer", "سقوط", "cair", "Fallen", "падение"),
    "falling-from-height": ("caer desde una altura", "السقوط من ارتفاع", "cair de uma altura", "aus der Höhe stürzen", "падение с высоты"),
    "falling-off-building": ("caerse de un edificio", "السقوط من مبنى", "cair de um prédio", "von einem Gebäude stürzen", "падение с здания"),
    "falling-into-water": ("caer al agua", "السقوط في الماء", "cair na água", "ins Wasser stürzen", "падение в воду"),
    "falling-and-waking-up": ("caer y despertar", "السقوط والاستيقاظ", "cair e acordar", "fallen und aufwachen", "падение и пробуждение"),
    "fear-of-heights": ("miedo a las alturas", "الخوف من المرتفعات", "medo de altura", "Höhenangst", "страх высоты"),
    "being-chased": ("que te persigan", "مطاردة", "ser perseguido", "verfolgt werden", "погоня"),
    "chased-by-man": ("que te persiga un hombre", "مطاردة رجل لك", "ser perseguido por um homem", "von einem Mann verfolgt werden", "погоня мужчины"),
    "chased-by-animal": ("que te persiga un animal", "مطاردة حيوان لك", "ser perseguido por um animal", "von einem Tier verfolgt werden", "погоня животного"),
    "chased-by-monster": ("que te persiga un monstruo", "مطاردة وحش لك", "ser perseguido por um monstro", "von einem Monster verfolgt werden", "погоня чудовища"),
    "hiding-from-someone": ("esconderse de alguien", "الاختباء من شخص", "esconder-se de alguém", "sich vor jemandem verstecken", "прятаться от кого-то"),
    "house": ("casa", "بيت", "casa", "Haus", "дом"),
    "old-house": ("casa vieja", "بيت قديم", "casa velha", "altes Haus", "старый дом"),
    "new-house": ("casa nueva", "بيت جديد", "casa nova", "neues Haus", "новый дом"),
    "burning-house": ("casa en llamas", "بيت يحترق", "casa pegando fogo", "brennendes Haus", "горящий дом"),
    "empty-house": ("casa vacía", "بيت فارغ", "casa vazia", "leeres Haus", "пустой дом"),
    "childhood-house": ("casa de la infancia", "بيت الطفولة", "casa da infância", "Kindheitshaus", "дом детства"),
    "haunted-house": ("casa embrujada", "بيت مسكون", "casa mal-assombrada", "Spukhaus", "дом с привидениями"),
    "attic": ("un desván", "علّية", "um sótão", "ein Dachboden", "чердак"),
    "basement": ("un sótano", "قبو", "um porão", "ein Keller", "подвал"),
    "bathroom": ("un baño", "حمّام", "um banheiro", "ein Badezimmer", "ванная"),
    "cannot-find-bathroom": ("no encontrar un baño", "العجز عن إيجاد حمّام", "não achar um banheiro", "keine Toilette finden", "не найти туалет"),
    "kitchen": ("una cocina", "مطبخ", "uma cozinha", "eine Küche", "кухня"),
    "unused-room": ("un cuarto oculto o sin uso", "غرفة مهجورة أو خفية", "um cômodo escondido ou sem uso", "ein ungenutztes oder verborgenes Zimmer", "неиспользуемая или скрытая комната"),
    "bedroom": ("un dormitorio", "غرفة نوم", "um quarto", "ein Schlafzimmer", "спальня"),
    "money": ("dinero", "مال", "dinheiro", "Geld", "деньги"),
    "finding-money": ("encontrar dinero", "العثور على مال", "encontrar dinheiro", "Geld finden", "найти деньги"),
    "losing-money": ("perder dinero", "خسارة المال", "perder dinheiro", "Geld verlieren", "потерять деньги"),
    "coins": ("monedas", "عملات معدنية", "moedas", "Münzen", "монеты"),
    "gold": ("oro", "ذهب", "ouro", "Gold", "золото"),
    "wallet": ("cartera", "محفظة", "carteira", "Geldbörse", "кошелёк"),
    "stealing-money": ("robar dinero", "سرقة مال", "roubar dinheiro", "Geld stehlen", "красть деньги"),
    "spider": ("araña", "عنكبوت", "aranha", "Spinne", "паук"),
    "big-spider": ("araña grande", "عنكبوت كبير", "aranha grande", "große Spinne", "большой паук"),
    "black-spider": ("araña negra", "عنكبوت أسود", "aranha preta", "schwarze Spinne", "чёрный паук"),
    "spider-bite": ("mordedura de araña", "لدغة عنكبوت", "picada de aranha", "Spinnenbiss", "укус паука"),
    "killing-spider": ("matar una araña", "قتل عنكبوت", "matar uma aranha", "eine Spinne töten", "убить паука"),
    "spider-web": ("telaraña", "شبكة عنكبوت", "teia de aranha", "Spinnennetz", "паутина"),
    "car": ("auto", "سيارة", "carro", "Auto", "машина"),
    "car-accident": ("accidente de auto", "حادث سيارة", "acidente de carro", "Autounfall", "авария"),
    "driving-car": ("manejar un auto", "قيادة سيارة", "dirigir um carro", "ein Auto fahren", "вести машину"),
    "losing-car": ("perder un auto", "فقدان سيارة", "perder um carro", "ein Auto verlieren", "потерять машину"),
    "stolen-car": ("auto robado", "سيارة مسروقة", "carro roubado", "gestohlenes Auto", "угнанная машина"),
    "car-crash": ("choque de auto", "تصادم سيارة", "batida de carro", "Autocrash", "крушение машины"),
    "brake-failure": ("fallo de frenos", "تعطل الفرامل", "falha no freio", "Bremsversagen", "отказ тормозов"),
    "buying-a-car": ("comprar un auto", "شراء سيارة", "comprar um carro", "ein Auto kaufen", "купить машину"),
    "passenger-in-car": ("ir de pasajero en un auto", "الركوب في سيارة", "ser passageiro no carro", "Beifahrer in einem Auto sein", "ехать пассажиром"),
    "new-car": ("un auto nuevo", "سيارة جديدة", "um carro novo", "ein neues Auto", "новая машина"),
    "car-keys": ("llaves del auto", "مفاتيح السيارة", "chaves do carro", "Autoschlüssel", "ключи от машины"),
    "car-in-water": ("un auto en el agua", "سيارة في الماء", "um carro na água", "ein Auto im Wasser", "машина в воде"),
    "school": ("escuela", "مدرسة", "escola", "Schule", "школа"),
    "old-school": ("escuela vieja", "مدرسة قديمة", "escola antiga", "alte Schule", "старая школа"),
    "being-late-to-school": ("llegar tarde a la escuela", "التأخر عن المدرسة", "chegar atrasado à escola", "zu spät zur Schule kommen", "опоздать в школу"),
    "school-exam": ("un examen escolar", "امتحان مدرسي", "uma prova escolar", "eine Schulprüfung", "школьный экзамен"),
    "empty-school": ("una escuela vacía", "مدرسة فارغة", "uma escola vazia", "eine leere Schule", "пустая школа"),
    "getting-lost-in-school": ("perderse en la escuela", "الضياع في المدرسة", "se perder na escola", "sich in der Schule verlaufen", "заблудиться в школе"),
    "childhood-school": ("tu escuela de la infancia", "مدرسة طفولتك", "sua escola da infância", "deine Kindheitsschule", "школа детства"),
    "school-classroom": ("un salón de clases", "صف دراسي", "uma sala de aula", "ein Klassenzimmer", "класс"),
    "failing-at-school": ("reprobar en la escuela", "الرسوب في المدرسة", "reprovar na escola", "in der Schule durchfallen", "провал в школе"),
    "hospital": ("hospital", "مستشفى", "hospital", "Krankenhaus", "больница"),
    "being-in-hospital": ("estar en el hospital", "الإقامة في المستشفى", "estar no hospital", "im Krankenhaus sein", "лежать в больнице"),
    "hospital-bed": ("una cama de hospital", "سرير مستشفى", "uma cama de hospital", "ein Krankenbett", "больничная койка"),
    "visiting-someone-in-hospital": ("visitar a alguien en el hospital", "زيارة مريض في المستشفى", "visitar alguém no hospital", "jemanden im Krankenhaus besuchen", "навещать в больнице"),
    "empty-hospital": ("un hospital vacío", "مستشفى فارغ", "um hospital vazio", "ein leeres Krankenhaus", "пустая больница"),
    "hospital-emergency": ("una emergencia hospitalaria", "طوارئ المستشفى", "uma emergência no hospital", "ein Krankenhausnotfall", "больничная неотложка"),
    "surgery-in-hospital": ("cirugía en el hospital", "عملية جراحية", "cirurgia no hospital", "eine Operation im Krankenhaus", "операция в больнице"),
    "lost-in-hospital": ("perderse en el hospital", "الضياع في المستشفى", "se perder no hospital", "sich im Krankenhaus verlaufen", "заблудиться в больнице"),
    "hospital-room": ("una habitación de hospital", "غرفة مستشفى", "um quarto de hospital", "ein Krankenzimmer", "больничная палата"),
    "church": ("iglesia", "كنيسة", "igreja", "Kirche", "церковь"),
    "praying-in-church": ("rezar en la iglesia", "الصلاة في الكنيسة", "rezar na igreja", "in der Kirche beten", "молиться в церкви"),
    "empty-church": ("una iglesia vacía", "كنيسة فارغة", "uma igreja vazia", "eine leere Kirche", "пустая церковь"),
    "old-church": ("una iglesia antigua", "كنيسة قديمة", "uma igreja antiga", "eine alte Kirche", "старая церковь"),
    "church-wedding": ("una boda en la iglesia", "زفاف كنسي", "um casamento na igreja", "eine kirchliche Hochzeit", "венчание"),
    "church-bells": ("campanas de iglesia", "أجراس الكنيسة", "sinos da igreja", "Kirchenglocken", "церковные колокола"),
    "burning-church": ("una iglesia en llamas", "كنيسة تحترق", "uma igreja pegando fogo", "eine brennende Kirche", "горящая церковь"),
    "church-service": ("un oficio religioso", "قداس أو خدمة كنسية", "um culto na igreja", "ein Gottesdienst", "церковная служба"),
    "abandoned-church": ("una iglesia abandonada", "كنيسة مهجورة", "uma igreja abandonada", "eine verlassene Kirche", "заброшенная церковь"),
    "cemetery": ("cementerio", "مقبرة", "cemitério", "Friedhof", "кладбище"),
    "walking-through-cemetery": ("caminar por un cementerio", "المشي في مقبرة", "andar por um cemitério", "über einen Friedhof gehen", "идти по кладбищу"),
    "graveyard": ("un camposanto", "مدفن", "um campo santo", "ein Kirchhof", "погост"),
    "visiting-a-grave": ("visitar una tumba", "زيارة قبر", "visitar um túmulo", "ein Grab besuchen", "навещать могилу"),
    "open-grave": ("una tumba abierta", "قبر مفتوح", "um túmulo aberto", "ein offenes Grab", "открытая могила"),
    "old-cemetery": ("un cementerio antiguo", "مقبرة قديمة", "um cemitério antigo", "ein alter Friedhof", "старое кладбище"),
    "cemetery-at-night": ("un cementerio de noche", "مقبرة ليلاً", "um cemitério à noite", "ein Friedhof bei Nacht", "кладбище ночью"),
    "seeing-your-own-grave": ("ver tu propia tumba", "رؤية قبرك", "ver o próprio túmulo", "das eigene Grab sehen", "видеть свою могилу"),
    "flowers-on-a-grave": ("flores sobre una tumba", "ورود على قبر", "flores em um túmulo", "Blumen auf einem Grab", "цветы на могиле"),
    "hotel": ("hotel", "فندق", "hotel", "Hotel", "гостиница"),
    "staying-in-hotel": ("quedarse en un hotel", "الإقامة في فندق", "ficar em um hotel", "in einem Hotel übernachten", "жить в гостинице"),
    "luxury-hotel": ("un hotel de lujo", "فندق فاخر", "um hotel de luxo", "ein Luxushotel", "роскошный отель"),
    "dirty-hotel-room": ("una habitación de hotel sucia", "غرفة فندق وسخة", "um quarto de hotel sujo", "ein schmutziges Hotelzimmer", "грязная гостиничная комната"),
    "getting-lost-in-hotel": ("perderse en un hotel", "الضياع في فندق", "se perder em um hotel", "sich in einem Hotel verlaufen", "заблудиться в гостинице"),
    "hotel-elevator": ("un elevador de hotel", "مصعد فندق", "um elevador de hotel", "ein Hotelaufzug", "гостиничный лифт"),
    "empty-hotel": ("un hotel vacío", "فندق فارغ", "um hotel vazio", "ein leeres Hotel", "пустой отель"),
    "hotel-check-in": ("un registro en el hotel", "تسجيل الوصول إلى الفندق", "um registro na recepção", "eine Hotelanmeldung", "регистрация в отеле"),
    "strange-hotel-room": ("una habitación de hotel extraña", "غرفة فندق غريبة", "um quarto de hotel estranho", "ein fremdes Hotelzimmer", "чужая гостиничная комната"),
    "airport": ("aeropuerto", "مطار", "aeroporto", "Flughafen", "аэропорт"),
    "missing-flight": ("perder un vuelo", "تفويت رحلة", "perder um voo", "einen Flug verpassen", "опоздать на рейс"),
    "waiting-at-airport": ("esperar en un aeropuerto", "الانتظار في المطار", "esperar no aeroporto", "am Flughafen warten", "ждать в аэропорту"),
    "running-through-airport": ("correr por un aeropuerto", "الجري في المطار", "correr pelo aeroporto", "durch den Flughafen rennen", "бежать по аэропорту"),
    "empty-airport": ("un aeropuerto vacío", "مطار فارغ", "um aeroporto vazio", "ein leerer Flughafen", "пустой аэропорт"),
    "airport-security": ("seguridad del aeropuerto", "أمن المطار", "segurança do aeroporto", "Flughafensicherheit", "досмотр в аэропорту"),
    "lost-luggage-at-airport": ("equipaje perdido en un aeropuerto", "أمتعة ضائعة في المطار", "bagagem perdida no aeroporto", "verlorenes Gepäck am Flughafen", "потерянный багаж в аэропорту"),
    "boarding-a-plane": ("abordar un avión", "الصعود إلى الطائرة", "embarcar no avião", "ein Flugzeug besteigen", "садиться в самолёт"),
    "cancelled-flight": ("un vuelo cancelado", "رحلة ملغاة", "um voo cancelado", "ein gestrichener Flug", "отменённый рейс"),
    "prison": ("cárcel", "سجن", "prisão", "Gefängnis", "тюрьма"),
    "being-in-prison": ("estar en la cárcel", "أن تكون في السجن", "estar na prisão", "im Gefängnis sein", "сидеть в тюрьме"),
    "escaping-prison": ("escapar de la cárcel", "الهروب من السجن", "fugir da prisão", "aus dem Gefängnis fliehen", "побег из тюрьмы"),
    "visiting-someone-in-prison": ("visitar a alguien en la cárcel", "زيارة سجين", "visitar alguém na prisão", "jemanden im Gefängnis besuchen", "навещать в тюрьме"),
    "prison-cell": ("una celda", "زنزانة", "uma cela", "eine Gefängniszelle", "тюремная камера"),
    "being-wrongly-imprisoned": ("estar preso injustamente", "السجن ظلماً", "ser preso injustamente", "zu Unrecht inhaftiert sein", "несправедливо заключённый"),
    "prison-guards": ("guardianes de la cárcel", "حرّاس السجن", "agentes penitenciários", "Gefängniswärter", "тюремные надзиратели"),
    "breaking-out-of-prison": ("fugarse de la cárcel", "كسر السجن", "escapar da prisão", "aus dem Gefängnis ausbrechen", "вырваться из тюрьмы"),
    "locked-in-prison": ("estar encerrado en la cárcel", "الإغلاق في السجن", "ficar trancado na prisão", "im Gefängnis eingeschlossen sein", "заперт в тюрьме"),
    "castle": ("castillo", "قلعة", "castelo", "Schloss", "замок"),
    "old-castle": ("un castillo antiguo", "قلعة قديمة", "um castelo antigo", "ein altes Schloss", "старый замок"),
    "haunted-castle": ("un castillo embrujado", "قلعة مسكونة", "um castelo mal-assombrado", "ein Spukschloss", "замок с привидениями"),
    "living-in-castle": ("vivir en un castillo", "السكن في قلعة", "morar em um castelo", "in einem Schloss leben", "жить в замке"),
    "castle-ruins": ("ruinas de un castillo", "أطلال قلعة", "ruínas de castelo", "Schlossruinen", "руины замка"),
    "castle-on-a-hill": ("un castillo en una colina", "قلعة على تل", "um castelo no morro", "ein Schloss auf einem Hügel", "замок на холме"),
    "entering-a-castle": ("entrar a un castillo", "دخول قلعة", "entrar em um castelo", "ein Schloss betreten", "войти в замок"),
    "being-trapped-in-castle": ("quedar atrapado en un castillo", "الاحتجاز في قلعة", "ficar preso em um castelo", "in einem Schloss gefangen sein", "застрять в замке"),
    "royal-castle": ("un castillo real", "قلعة ملكية", "um castelo real", "ein königliches Schloss", "королевский замок"),
    "beach": ("playa", "شاطئ", "praia", "Strand", "пляж"),
    "walking-on-beach": ("caminar por una playa", "المشي على الشاطئ", "andar na praia", "am Strand spazieren", "идти по пляжу"),
    "empty-beach": ("una playa vacía", "شاطئ خالٍ", "uma praia vazia", "ein leerer Strand", "пустой пляж"),
    "beach-waves": ("olas de la playa", "أمواج الشاطئ", "ondas da praia", "Strandwellen", "волны на пляже"),
    "stormy-beach": ("una playa tormentosa", "شاطئ عاصف", "uma praia tempestuosa", "ein stürmischer Strand", "штормовой пляж"),
    "sunny-beach": ("una playa soleada", "شاطئ مشمس", "uma praia ensolarada", "ein sonniger Strand", "солнечный пляж"),
    "beach-at-night": ("una playa de noche", "شاطئ ليلاً", "uma praia à noite", "ein Strand bei Nacht", "пляж ночью"),
    "finding-something-on-beach": ("encontrar algo en una playa", "العثور على شيء في الشاطئ", "encontrar algo na praia", "etwas am Strand finden", "найти что-то на пляже"),
    "lost-on-beach": ("perderse en una playa", "الضياع في الشاطئ", "se perder na praia", "sich am Strand verlaufen", "заблудиться на пляже"),
    "forest": ("bosque", "غابة", "floresta", "Wald", "лес"),
    "dark-forest": ("un bosque oscuro", "غابة مظلمة", "uma floresta escura", "ein dunkler Wald", "тёмный лес"),
    "walking-in-forest": ("caminar por un bosque", "المشي في غابة", "andar na floresta", "in einem Wald gehen", "идти по лесу"),
    "getting-lost-in-forest": ("perderse en un bosque", "الضياع في الغابة", "se perder na floresta", "sich im Wald verlaufen", "заблудиться в лесу"),
    "burning-forest": ("un bosque en llamas", "غابة تحترق", "uma floresta em chamas", "ein brennender Wald", "горящий лес"),
    "green-forest": ("un bosque verde", "غابة خضراء", "uma floresta verde", "ein grüner Wald", "зелёный лес"),
    "forest-animals": ("animales del bosque", "حيوانات الغابة", "animais da floresta", "Waldtiere", "лесные звери"),
    "running-through-forest": ("correr por un bosque", "الجري في الغابة", "correr pela floresta", "durch den Wald rennen", "бежать через лес"),
    "enchanted-forest": ("un bosque encantado", "غابة مسحورة", "uma floresta encantada", "ein verzauberter Wald", "заколдованный лес"),
    "fish": ("pez", "سمكة", "peixe", "Fisch", "рыба"),
    "big-fish": ("un pez grande", "سمكة كبيرة", "um peixe grande", "ein großer Fisch", "большая рыба"),
    "dead-fish": ("un pez muerto", "سمكة ميتة", "um peixe morto", "ein toter Fisch", "мёртвая рыба"),
    "catching-fish": ("pescar un pez", "صيد سمكة", "pescar um peixe", "einen Fisch fangen", "поймать рыбу"),
    "swimming-fish": ("peces nadando", "سمك يسبح", "peixes nadando", "schwimmende Fische", "плывущая рыба"),
    "fish-jumping": ("un pez saltando", "سمكة تقفز", "um peixe pulando", "ein springender Fisch", "прыгающая рыба"),
    "colorful-fish": ("un pez de colores", "سمكة ملونة", "um peixe colorido", "ein bunter Fisch", "пёстрая рыба"),
    "fish-in-clear-water": ("peces en agua clara", "سمك في ماء صافٍ", "peixes em água limpa", "Fische in klarem Wasser", "рыба в чистой воде"),
    "fish-tank": ("una pecera", "حوض سمك", "um aquário", "ein Aquarium", "аквариум"),
    "bird": ("pájaro", "طائر", "pássaro", "Vogel", "птица"),
    "flying-bird": ("un pájaro volando", "طائر محلّق", "um pássaro voando", "ein fliegender Vogel", "летящая птица"),
    "black-bird": ("un pájaro negro", "طائر أسود", "um pássaro preto", "ein schwarzer Vogel", "чёрная птица"),
    "white-bird": ("un pájaro blanco", "طائر أبيض", "um pássaro branco", "ein weißer Vogel", "белая птица"),
    "bird-attack": ("un ataque de pájaro", "هجوم طائر", "um ataque de pássaro", "ein Vogelangriff", "нападение птицы"),
    "dead-bird": ("un pájaro muerto", "طائر ميت", "um pássaro morto", "ein toter Vogel", "мёртвая птица"),
    "bird-nest": ("un nido de pájaro", "عش طائر", "um ninho de pássaro", "ein Vogelnest", "птичье гнездо"),
    "singing-bird": ("un pájaro cantando", "طائر يغني", "um pássaro cantando", "ein singender Vogel", "поющая птица"),
    "flock-of-birds": ("una bandada de pájaros", "سرب طيور", "um bando de pássaros", "ein Vogelschwarm", "стая птиц"),
    "horse": ("caballo", "حصان", "cavalo", "Pferd", "лошадь"),
    "white-horse": ("un caballo blanco", "حصان أبيض", "um cavalo branco", "ein weißes Pferd", "белый конь"),
    "black-horse": ("un caballo negro", "حصان أسود", "um cavalo preto", "ein schwarzes Pferd", "чёрный конь"),
    "riding-horse": ("montar a caballo", "ركوب حصان", "montar a cavalo", "ein Pferd reiten", "ехать верхом"),
    "wild-horse": ("un caballo salvaje", "حصان بري", "um cavalo selvagem", "ein wildes Pferd", "дикая лошадь"),
    "injured-horse": ("un caballo herido", "حصان مصاب", "um cavalo ferido", "ein verletztes Pferd", "раненая лошадь"),
    "dead-horse": ("un caballo muerto", "حصان ميت", "um cavalo morto", "ein totes Pferd", "мёртвая лошадь"),
    "horse-race": ("una carrera de caballos", "سباق خيل", "uma corrida de cavalos", "ein Pferderennen", "скачки"),
    "horse-chasing-you": ("un caballo que te persigue", "حصان يلاحقك", "um cavalo te perseguindo", "ein Pferd, das dich jagt", "лошадь гонится за тобой"),
    "wolf": ("lobo", "ذئب", "lobo", "Wolf", "волк"),
    "black-wolf": ("un lobo negro", "ذئب أسود", "um lobo preto", "ein schwarzer Wolf", "чёрный волк"),
    "white-wolf": ("un lobo blanco", "ذئب أبيض", "um lobo branco", "ein weißer Wolf", "белый волк"),
    "wolf-attack": ("un ataque de lobo", "هجوم ذئب", "um ataque de lobo", "ein Wolfsangriff", "нападение волка"),
    "pack-of-wolves": ("una manada de lobos", "قطيع ذئاب", "uma alcateia", "ein Wolfsrudel", "стая волков"),
    "friendly-wolf": ("un lobo amistoso", "ذئب ودود", "um lobo amigável", "ein freundlicher Wolf", "доброжелательный волк"),
    "dead-wolf": ("un lobo muerto", "ذئب ميت", "um lobo morto", "ein toter Wolf", "мёртвый волк"),
    "howling-wolf": ("un lobo aullando", "ذئب يعوي", "um lobo uivando", "ein heulender Wolf", "воющий волк"),
    "wolf-chasing-you": ("un lobo que te persigue", "ذئب يلاحقك", "um lobo te perseguindo", "ein Wolf, der dich jagt", "волк гонится за тобой"),
    "bear": ("oso", "دب", "urso", "Bär", "медведь"),
    "black-bear": ("un oso negro", "دب أسود", "um urso preto", "ein schwarzer Bär", "чёрный медведь"),
    "brown-bear": ("un oso pardo", "دب بني", "um urso pardo", "ein Braunbär", "бурый медведь"),
    "bear-attack": ("un ataque de oso", "هجوم دب", "um ataque de urso", "ein Bärenangriff", "нападение медведя"),
    "friendly-bear": ("un oso amistoso", "دب ودود", "um urso amigável", "ein freundlicher Bär", "доброжелательный медведь"),
    "baby-bear": ("un osezno", "دب صغير", "um ursinho", "ein Bärenjunges", "медвежонок"),
    "dead-bear": ("un oso muerto", "دب ميت", "um urso morto", "ein toter Bär", "мёртвый медведь"),
    "giant-bear": ("un oso gigante", "دب عملاق", "um urso gigante", "ein riesiger Bär", "огромный медведь"),
    "running-from-bear": ("huir de un oso", "الهرب من دب", "correr de um urso", "vor einem Bären weglaufen", "бежать от медведя"),
    "lion": ("león", "أسد", "leão", "Löwe", "лев"),
    "lion-attack": ("un ataque de león", "هجوم أسد", "um ataque de leão", "ein Löwenangriff", "нападение льва"),
    "friendly-lion": ("un león amistoso", "أسد ودود", "um leão amigável", "ein freundlicher Löwe", "доброжелательный лев"),
    "lion-chasing-you": ("un león que te persigue", "أسد يلاحقك", "um leão te perseguindo", "ein Löwe, der dich jagt", "лев гонится за тобой"),
    "dead-lion": ("un león muerto", "أسد ميت", "um leão morto", "ein toter Löwe", "мёртвый лев"),
    "roaring-lion": ("un león rugiendo", "أسد يزأر", "um leão rugindo", "ein brüllender Löwe", "рычащий лев"),
    "lion-cub": ("un cachorro de león", "شبل أسد", "um filhote de leão", "ein Löwenjunges", "львёнок"),
    "black-lion": ("un león negro", "أسد أسود", "um leão preto", "ein schwarzer Löwe", "чёрный лев"),
    "white-lion": ("un león blanco", "أسد أبيض", "um leão branco", "ein weißer Löwe", "белый лев"),
    "tiger": ("tigre", "نمر", "tigre", "Tiger", "тигр"),
    "tiger-attack": ("un ataque de tigre", "هجوم نمر", "um ataque de tigre", "ein Tigerangriff", "нападение тигра"),
    "white-tiger": ("un tigre blanco", "نمر أبيض", "um tigre branco", "ein weißer Tiger", "белый тигр"),
    "black-tiger": ("un tigre negro", "نمر أسود", "um tigre preto", "ein schwarzer Tiger", "чёрный тигр"),
    "friendly-tiger": ("un tigre amistoso", "نمر ودود", "um tigre amigável", "ein freundlicher Tiger", "доброжелательный тигр"),
    "dead-tiger": ("un tigre muerto", "نمر ميت", "um tigre morto", "ein toter Tiger", "мёртвый тигр"),
    "tiger-chasing-you": ("un tigre que te persigue", "نمر يلاحقك", "um tigre te perseguindo", "ein Tiger, der dich jagt", "тигр гонится за тобой"),
    "baby-tiger": ("un tigre bebé", "شبل نمر", "um filhote de tigre", "ein Tigerjunges", "тигрёнок"),
    "giant-tiger": ("un tigre gigante", "نمر عملاق", "um tigre gigante", "ein riesiger Tiger", "огромный тигр"),
    "shark": ("tiburón", "قرش", "tubarão", "Hai", "акула"),
    "shark-attack": ("un ataque de tiburón", "هجوم قرش", "um ataque de tubarão", "ein Haiangriff", "нападение акулы"),
    "dead-shark": ("un tiburón muerto", "قرش ميت", "um tubarão morto", "ein toter Hai", "мёртвая акула"),
    "giant-shark": ("un tiburón gigante", "قرش عملاق", "um tubarão gigante", "ein riesiger Hai", "огромная акула"),
    "swimming-with-sharks": ("nadar con tiburones", "السباحة مع أسماك القرش", "nadar com tubarões", "mit Haien schwimmen", "плавать с акулами"),
    "black-shark": ("un tiburón negro", "قرش أسود", "um tubarão preto", "ein schwarzer Hai", "чёрная акула"),
    "shark-chasing-you": ("un tiburón que te persigue", "قرش يلاحقك", "um tubarão te perseguindo", "ein Hai, der dich jagt", "акула гонится за тобой"),
    "shark-in-clear-water": ("un tiburón en agua clara", "قرش في ماء صافٍ", "um tubarão em água limpa", "ein Hai in klarem Wasser", "акула в чистой воде"),
    "shark-bite": ("una mordida de tiburón", "عضة قرش", "uma mordida de tubarão", "ein Haibiss", "укус акулы"),
    "owl": ("búho", "بومة", "coruja", "Eule", "сова"),
    "white-owl": ("un búho blanco", "بومة بيضاء", "uma coruja branca", "eine weiße Eule", "белая сова"),
    "black-owl": ("un búho negro", "بومة سوداء", "uma coruja preta", "eine schwarze Eule", "чёрная сова"),
    "owl-watching-you": ("un búho que te observa", "بومة ترقبك", "uma coruja te observando", "eine Eule, die dich beobachtet", "сова смотрит на тебя"),
    "dead-owl": ("un búho muerto", "بومة ميتة", "uma coruja morta", "eine tote Eule", "мёртвая сова"),
    "flying-owl": ("un búho volando", "بومة محلّقة", "uma coruja voando", "eine fliegende Eule", "летящая сова"),
    "owl-at-night": ("un búho de noche", "بومة في الليل", "uma coruja à noite", "eine Eule bei Nacht", "сова ночью"),
    "giant-owl": ("un búho gigante", "بومة عملاقة", "uma coruja gigante", "eine riesige Eule", "огромная сова"),
    "talking-owl": ("un búho que habla", "بومة تتكلم", "uma coruja falante", "eine sprechende Eule", "говорящая сова"),
    "butterfly": ("mariposa", "فراشة", "borboleta", "Schmetterling", "бабочка"),
    "white-butterfly": ("una mariposa blanca", "فراشة بيضاء", "uma borboleta branca", "ein weißer Schmetterling", "белая бабочка"),
    "black-butterfly": ("una mariposa negra", "فراشة سوداء", "uma borboleta preta", "ein schwarzer Schmetterling", "чёрная бабочка"),
    "colorful-butterfly": ("una mariposa de colores", "فراشة ملونة", "uma borboleta colorida", "ein bunter Schmetterling", "пёстрая бабочка"),
    "dead-butterfly": ("una mariposa muerta", "فراشة ميتة", "uma borboleta morta", "ein toter Schmetterling", "мёртвая бабочка"),
    "giant-butterfly": ("una mariposa gigante", "فراشة عملاقة", "uma borboleta gigante", "ein riesiger Schmetterling", "огромная бабочка"),
    "butterfly-landing-on-you": ("una mariposa que se posa en ti", "فراشة تحط عليك", "uma borboleta pousando em você", "ein Schmetterling, der sich auf dich setzt", "бабочка садится на тебя"),
    "many-butterflies": ("muchas mariposas", "فراشات كثيرة", "muitas borboletas", "viele Schmetterlinge", "много бабочек"),
    "butterfly-transformation": ("una transformación de mariposa", "تحوّل الفراشة", "uma transformação de borboleta", "eine Schmetterlingsverwandlung", "превращение бабочки"),
    "fire": ("fuego", "نار", "fogo", "Feuer", "огонь"),
    "escaping-a-fire": ("escapar de un incendio", "الهروب من حريق", "escapar de um incêndio", "einem Feuer entkommen", "спастись от пожара"),
    "starting-a-fire": ("prender un fuego", "إشعال نار", "atear um fogo", "ein Feuer legen", "разжечь огонь"),
    "putting-out-a-fire": ("apagar un fuego", "إطفاء نار", "apagar um fogo", "ein Feuer löschen", "тушить огонь"),
    "wildfire": ("un incendio forestal", "حريق هائل", "um incêndio florestal", "ein Flächenbrand", "лесной пожар"),
    "fire-smoke": ("fuego y humo", "نار ودخان", "fogo e fumaça", "Feuer und Rauch", "огонь и дым"),
    "clothes-on-fire": ("la ropa en llamas", "ثيابك تحترق", "roupa pegando fogo", "brennende Kleidung", "одежда в огне"),
    "fire-in-the-sky": ("fuego en el cielo", "نار في السماء", "fogo no céu", "Feuer am Himmel", "огонь в небе"),
    "tornado": ("tornado", "إعصار", "tornado", "Tornado", "торнадо"),
    "tornado-coming": ("un tornado que se acerca", "إعصار يتجه نحوك", "um tornado vindo na sua direção", "ein Tornado, der auf dich zukommt", "торнадо идёт на тебя"),
    "hiding-from-tornado": ("esconderse de un tornado", "الاختباء من إعصار", "esconder-se de um tornado", "sich vor einem Tornado verstecken", "прятаться от торнадо"),
    "surviving-a-tornado": ("sobrevivir a un tornado", "النجاة من إعصار", "sobreviver a um tornado", "einen Tornado überleben", "пережить торнадо"),
    "multiple-tornadoes": ("varios tornados", "أعاصير متعددة", "vários tornados", "mehrere Tornados", "несколько торнадо"),
    "tornado-destroying-house": ("un tornado destruyendo una casa", "إعصار يدمّر بيتاً", "um tornado destruindo uma casa", "ein Tornado, der ein Haus zerstört", "торнадо разрушает дом"),
    "tornado-far-away": ("un tornado a lo lejos", "إعصار بعيد", "um tornado ao longe", "ein ferner Tornado", "торнадо вдали"),
    "earthquake": ("terremoto", "زلزال", "terremoto", "Erdbeben", "землетрясение"),
    "ground-shaking": ("la tierra temblando", "اهتزاز الأرض", "o chão tremendo", "der Boden bebt", "земля трясётся"),
    "building-collapsing": ("un edificio derrumbándose", "انهيار مبنى", "um prédio desabando", "ein einstürzendes Gebäude", "обрушение здания"),
    "surviving-an-earthquake": ("sobrevivir a un terremoto", "النجاة من زلزال", "sobreviver a um terremoto", "ein Erdbeben überleben", "пережить землетрясение"),
    "earthquake-cracks": ("grietas que se abren en el suelo", "شقوق تنفتح في الأرض", "rachaduras se abrindo no chão", "Risse im Boden", "трещины в земле"),
    "earthquake-at-home": ("un terremoto en casa", "زلزال في البيت", "um terremoto em casa", "ein Erdbeben zu Hause", "землетрясение дома"),
    "aftershocks": ("réplicas", "هزات ارتدادية", "abalos secundários", "Nachbeben", "афтершоки"),
    "storm": ("tormenta", "عاصفة", "tempestade", "Sturm", "буря"),
    "thunder-and-lightning": ("trueno y relámpago", "رعد وبرق", "trovão e relâmpago", "Donner und Blitz", "гром и молния"),
    "caught-in-a-storm": ("quedar atrapado en una tormenta", "الإمساك في عاصفة", "ser pego em uma tempestade", "in einem Sturm gefangen sein", "попасть в бурю"),
    "storm-approaching": ("una tormenta que se acerca", "عاصفة تقترب", "uma tempestade se aproximando", "ein aufziehender Sturm", "приближающаяся буря"),
    "sheltering-from-storm": ("refugiarse de una tormenta", "الاحتماء من عاصفة", "abrigar-se de uma tempestade", "sich vor einem Sturm unterstellen", "укрыться от бури"),
    "storm-passing": ("una tormenta que pasa", "عاصفة تنقشع", "uma tempestade passando", "ein vorbeiziehender Sturm", "буря проходит"),
    "storm-at-sea": ("una tormenta en el mar", "عاصفة في البحر", "uma tempestade no mar", "ein Sturm auf See", "буря в море"),
    "blood": ("sangre", "دم", "sangue", "Blut", "кровь"),
    "bleeding": ("sangrar", "نزيف", "sangramento", "Bluten", "кровотечение"),
    "blood-on-hands": ("sangre en las manos", "دم على يديك", "sangue nas mãos", "Blut an den Händen", "кровь на руках"),
    "blood-on-clothes": ("sangre en la ropa", "دم على الثياب", "sangue na roupa", "Blut auf der Kleidung", "кровь на одежде"),
    "someone-else-bleeding": ("otra persona sangrando", "شخص آخر ينزف", "outra pessoa sangrando", "jemand anderes blutet", "кто-то другой кровоточит"),
    "blood-on-the-floor": ("sangre en el piso", "دم على الأرض", "sangue no chão", "Blut auf dem Boden", "кровь на полу"),
    "coughing-blood": ("toser sangre", "سعال الدم", "tossir sangue", "Blut husten", "кашлять кровью"),
    "hair": ("cabello", "شعر", "cabelo", "Haar", "волосы"),
    "hair-falling-out": ("caérsele el cabello", "تساقط الشعر", "cabelo caindo", "Haarausfall", "выпадают волосы"),
    "cutting-hair": ("cortarse el cabello", "قص الشعر", "cortar o cabelo", "Haare schneiden", "стричь волосы"),
    "long-hair": ("cabello largo", "شعر طويل", "cabelo longo", "langes Haar", "длинные волосы"),
    "white-or-gray-hair": ("cabello blanco o canoso", "شعر أبيض أو أشيب", "cabelo branco ou grisalho", "weißes oder graues Haar", "седые или белые волосы"),
    "someone-cutting-your-hair": ("que te corten el cabello", "شخص يقص شعرك", "alguém cortando seu cabelo", "jemand schneidet dir die Haare", "тебе стригут волосы"),
    "washing-hair": ("lavarse el cabello", "غسل الشعر", "lavar o cabelo", "Haare waschen", "мыть волосы"),
    "ex": ("tu ex", "شريكك السابق", "seu ex", "dein Ex", "бывший"),
    "ex-boyfriend": ("un exnovio", "حبيب سابق", "um ex-namorado", "ein Ex-Freund", "бывший парень"),
    "ex-girlfriend": ("una exnovia", "حبيبة سابقة", "uma ex-namorada", "eine Ex-Freundin", "бывшая девушка"),
    "ex-coming-back": ("un ex que regresa", "عودة شريك سابق", "um ex voltando", "ein Ex, der zurückkommt", "бывший возвращается"),
    "arguing-with-ex": ("discutir con un ex", "جدال مع شريك سابق", "discutir com um ex", "Streit mit einem Ex", "ссора с бывшим"),
    "ex-apologizing": ("un ex pidiendo perdón", "اعتذار شريك سابق", "um ex pedindo desculpas", "ein Ex, der sich entschuldigt", "бывший извиняется"),
    "ex-with-someone-else": ("un ex con otra persona", "شريك سابق مع شخص آخر", "um ex com outra pessoa", "ein Ex mit jemand anderem", "бывший с кем-то другим"),
    "ex-family": ("la familia de un ex", "عائلة الشريك السابق", "a família de um ex", "die Familie eines Ex", "семья бывшего"),
    "cheating": ("infidelidad", "خيانة", "traição", "Fremdgehen", "измена"),
    "partner-cheating": ("tu pareja siéndote infiel", "خيانة شريكك", "seu parceiro te traindo", "dein Partner fremdgeht", "партнёр изменяет"),
    "cheating-on-partner": ("serle infiel a tu pareja", "خيانتك لشريكك", "trair seu parceiro", "dem Partner fremdgehen", "изменить партнёру"),
    "being-caught-cheating": ("que te descubran en una infidelidad", "انكشاف الخيانة", "ser pego traindo", "beim Fremdgehen erwischt werden", "поймать на измене"),
    "confronting-a-cheater": ("enfrentar a quien te fue infiel", "مواجهة الخائن", "enfrentar quem traiu", "einen Betrüger konfrontieren", "противостоять изменщику"),
    "forgiving-cheating": ("perdonar una infidelidad", "مسامحة الخيانة", "perdoar uma traição", "Fremdgehen verzeihen", "простить измену"),
    "recurring-cheating-dreams": ("sueños recurrentes de infidelidad", "أحلام خيانة متكررة", "sonhos recorrentes de traição", "wiederkehrende Fremdgehträume", "повторяющиеся сны об измене"),
    "wedding": ("boda", "زفاف", "casamento", "Hochzeit", "свадьба"),
    "your-own-wedding": ("tu propia boda", "زفافك أنت", "o próprio casamento", "die eigene Hochzeit", "собственная свадьба"),
    "someone-elses-wedding": ("la boda de otra persona", "زفاف شخص آخر", "o casamento de outra pessoa", "die Hochzeit eines anderen", "чужая свадьба"),
    "wedding-going-wrong": ("una boda que sale mal", "زفاف يفسد", "um casamento dando errado", "eine schiefgehende Hochzeit", "свадьба идёт наперекосяк"),
    "wedding-dress": ("un vestido de novia", "فستان زفاف", "um vestido de noiva", "ein Hochzeitskleid", "свадебное платье"),
    "marrying-a-stranger": ("casarte con un desconocido", "الزواج من غريب", "casar com um desconhecido", "einen Fremden heiraten", "выйти за незнакомца"),
    "runaway-bride-or-groom": ("una novia o un novio que huye", "عروس أو عريس يهرب", "noiva ou noivo fugindo", "eine flüchtende Braut oder ein flüchtender Bräutigam", "сбежавшие жених или невеста"),
    "kissing": ("besar", "تقبيل", "beijo", "Küssen", "поцелуй"),
    "kissing-a-stranger": ("besar a un desconocido", "تقبيل غريب", "beijar um desconhecido", "einen Fremden küssen", "целовать незнакомца"),
    "kissing-an-ex": ("besar a un ex", "تقبيل شريك سابق", "beijar um ex", "einen Ex küssen", "целовать бывшего"),
    "kissing-a-friend": ("besar a un amigo", "تقبيل صديق", "beijar um amigo", "einen Freund küssen", "целовать друга"),
    "being-kissed-unexpectedly": ("que te besen de sorpresa", "قبلة مفاجئة", "ser beijado de surpresa", "unerwartet geküsst werden", "неожиданный поцелуй"),
    "refusing-a-kiss": ("rechazar un beso", "رفض قبلة", "recusar um beijo", "einen Kuss ablehnen", "отказать в поцелуе"),
    "kissing-a-celebrity": ("besar a un famoso", "تقبيل مشهور", "beijar uma celebridade", "einen Promi küssen", "целовать знаменитость"),
    "sex": ("sexo", "جنس", "sexo", "Sex", "секс"),
    "sex-with-a-coworker": ("sexo con un compañero de trabajo", "جنس مع زميل عمل", "sexo com um colega de trabalho", "Sex mit einem Kollegen", "секс с коллегой"),
    "sex-with-an-ex": ("sexo con un ex", "جنس مع شريك سابق", "sexo com um ex", "Sex mit einem Ex", "секс с бывшим"),
    "sex-with-a-stranger": ("sexo con un desconocido", "جنس مع غريب", "sexo com um desconhecido", "Sex mit einem Fremden", "секс с незнакомцем"),
    "sex-with-a-friend": ("sexo con un amigo", "جنس مع صديق", "sexo com um amigo", "Sex mit einem Freund", "секс с другом"),
    "sex-with-your-boss": ("sexo con tu jefe", "جنس مع المدير", "sexo com o chefe", "Sex mit dem Chef", "секс с начальником"),
    "sex-with-someone-you-dislike": ("sexo con alguien que no te agrada", "جنس مع من تكره", "sexo com alguém de quem você não gosta", "Sex mit jemandem, den du nicht magst", "секс с тем, кто неприятен"),
    "sex-with-your-partner": ("sexo con tu pareja", "جنس مع شريكك", "sexo com seu parceiro", "Sex mit dem Partner", "секс с партнёром"),
    "mother": ("madre", "أم", "mãe", "Mutter", "мать"),
    "walking-with-my-mother": ("caminar con tu madre", "المشي مع أمك", "andar com sua mãe", "mit der Mutter spazieren", "идти с матерью"),
    "mother-dying": ("tu madre muriendo", "موت أمك", "sua mãe morrendo", "die Mutter stirbt", "мать умирает"),
    "deceased-mother": ("una madre fallecida", "أم متوفاة", "uma mãe falecida", "eine verstorbene Mutter", "покойная мать"),
    "arguing-with-mother": ("discutir con tu madre", "جدال مع الأم", "discutir com sua mãe", "Streit mit der Mutter", "ссора с матерью"),
    "mother-hugging-you": ("tu madre abrazándote", "أمك تعانقك", "sua mãe te abraçando", "die Mutter umarmt dich", "мать обнимает тебя"),
    "becoming-a-mother": ("convertirte en madre", "أن تصبحي أماً", "tornar-se mãe", "Mutter werden", "стать матерью"),
    "angry-mother": ("una madre enojada", "أم غاضبة", "uma mãe brava", "eine wütende Mutter", "разгневанная мать"),
    "father": ("padre", "أب", "pai", "Vater", "отец"),
    "father-dying": ("tu padre muriendo", "موت أبيك", "seu pai morrendo", "der Vater stirbt", "отец умирает"),
    "deceased-father": ("un padre fallecido", "أب متوفى", "um pai falecido", "ein verstorbener Vater", "покойный отец"),
    "arguing-with-father": ("discutir con tu padre", "جدال مع الأب", "discutir com seu pai", "Streit mit dem Vater", "ссора с отцом"),
    "father-hugging-you": ("tu padre abrazándote", "أبوك يعانقك", "seu pai te abraçando", "der Vater umarmt dich", "отец обнимает тебя"),
    "absent-father": ("un padre ausente", "أب غائب", "um pai ausente", "ein abwesender Vater", "отсутствующий отец"),
    "angry-father": ("un padre enojado", "أب غاضب", "um pai bravo", "ein wütender Vater", "разгневанный отец"),
    "brother": ("hermano", "أخ", "irmão", "Bruder", "брат"),
    "brother-dying": ("tu hermano muriendo", "موت أخيك", "seu irmão morrendo", "der Bruder stirbt", "брат умирает"),
    "arguing-with-brother": ("discutir con tu hermano", "جدال مع الأخ", "discutir com seu irmão", "Streit mit dem Bruder", "ссора с братом"),
    "brother-in-danger": ("tu hermano en peligro", "أخوك في خطر", "seu irmão em perigo", "der Bruder in Gefahr", "брат в опасности"),
    "older-brother": ("un hermano mayor", "أخ أكبر", "um irmão mais velho", "ein älterer Bruder", "старший брат"),
    "younger-brother": ("un hermano menor", "أخ أصغر", "um irmão mais novo", "ein jüngerer Bruder", "младший брат"),
    "estranged-brother": ("un hermano distanciado", "أخ قطيعة", "um irmão afastado", "ein entfremdeter Bruder", "отдалившийся брат"),
    "sister": ("hermana", "أخت", "irmã", "Schwester", "сестра"),
    "sister-dying": ("tu hermana muriendo", "موت أختك", "sua irmã morrendo", "die Schwester stirbt", "сестра умирает"),
    "arguing-with-sister": ("discutir con tu hermana", "جدال مع الأخت", "discutir com sua irmã", "Streit mit der Schwester", "ссора с сестрой"),
    "sister-crying": ("tu hermana llorando", "أختك تبكي", "sua irmã chorando", "die Schwester weint", "сестра плачет"),
    "older-sister": ("una hermana mayor", "أخت أكبر", "uma irmã mais velha", "eine ältere Schwester", "старшая сестра"),
    "younger-sister": ("una hermana menor", "أخت أصغر", "uma irmã mais nova", "eine jüngere Schwester", "младшая сестра"),
    "protecting-your-sister": ("proteger a tu hermana", "حماية أختك", "proteger sua irmã", "die Schwester beschützen", "защищать сестру"),
    "god": ("dios", "الله", "deus", "Gott", "бог"),
    "talking-to-god": ("hablar con dios", "الكلام مع الله", "falar com deus", "mit Gott sprechen", "говорить с богом"),
    "seeing-god": ("ver a dios", "رؤية الله", "ver deus", "Gott sehen", "видеть бога"),
    "praying-to-god": ("rezarle a dios", "الصلاة إلى الله", "rezar a deus", "zu Gott beten", "молиться богу"),
    "gods-voice": ("oír la voz de dios", "سماع صوت الله", "ouvir a voz de deus", "Gottes Stimme hören", "слышать голос бога"),
    "being-judged-by-god": ("ser juzgado por dios", "الحساب أمام الله", "ser julgado por deus", "von Gott gerichtet werden", "суд божий"),
    "receiving-a-blessing": ("recibir una bendición", "تلقي بركة", "receber uma bênção", "einen Segen empfangen", "получить благословение"),
    "illness": ("enfermedad", "مرض", "doença", "Krankheit", "болезнь"),
    "being-sick": ("estar enfermo", "المرض", "estar doente", "krank sein", "болеть"),
    "terminal-illness": ("una enfermedad terminal", "مرض عضال", "uma doença terminal", "eine tödliche Krankheit", "смертельная болезнь"),
    "sick-family-member": ("un familiar enfermo", "قريب مريض", "um familiar doente", "ein krankes Familienmitglied", "больной родственник"),
    "recovering-from-illness": ("recuperarse de una enfermedad", "الشفاء من مرض", "recuperar-se de uma doença", "von einer Krankheit genesen", "выздоравливать"),
    "undiagnosed-illness": ("una enfermedad sin diagnóstico", "مرض بلا تشخيص", "uma doença sem diagnóstico", "eine undiagnostizierte Krankheit", "недиагностированная болезнь"),
    "vomiting-in-a-dream": ("vomitar", "قيء", "vomitar", "Erbrechen", "рвота"),
    "ghost": ("fantasma", "شبح", "fantasma", "Geist", "призрак"),
    "ghost-of-a-loved-one": ("el fantasma de un ser querido", "شبح حبيب", "o fantasma de alguém querido", "der Geist eines geliebten Menschen", "призрак близкого"),
    "haunted-by-a-ghost": ("estar embrujado", "المطاردة من شبح", "ser assombrado", "heimgesucht werden", "преследование призраком"),
    "friendly-ghost": ("un fantasma amistoso", "شبح ودود", "um fantasma amigável", "ein freundlicher Geist", "доброжелательный призрак"),
    "ghost-attacking-you": ("un fantasma que te ataca", "شبح يهاجمك", "um fantasma te atacando", "ein Geist, der dich angreift", "призрак нападает на тебя"),
    "ghost-in-your-house": ("un fantasma en tu casa", "شبح في بيتك", "um fantasma na sua casa", "ein Geist in deinem Haus", "призрак в доме"),
    "becoming-a-ghost": ("convertirte en fantasma", "أن تصبح شبحاً", "tornar-se um fantasma", "ein Geist werden", "стать призраком"),
    "demon": ("demonio", "شيطان", "demônio", "Dämon", "демон"),
    "being-attacked-by-demon": ("que te ataque un demonio", "هجوم شيطان عليك", "ser atacado por um demônio", "von einem Dämon angegriffen werden", "нападение демона"),
    "demon-possession": ("posesión demoníaca", "مسّ شيطاني", "possessão demoníaca", "dämonische Besessenheit", "одержимость демоном"),
    "fighting-a-demon": ("pelear con un demonio", "قتال شيطان", "lutar contra um demônio", "gegen einen Dämon kämpfen", "биться с демоном"),
    "demon-in-your-house": ("un demonio en tu casa", "شيطان في بيتك", "um demônio na sua casa", "ein Dämon in deinem Haus", "демон в доме"),
    "demon-watching-you": ("un demonio que te observa", "شيطان يراقبك", "um demônio te observando", "ein Dämon, der dich beobachtet", "демон наблюдает за тобой"),
    "casting-out-a-demon": ("expulsar a un demonio", "طرد شيطان", "expulsar um demônio", "einen Dämon austreiben", "изгнать демона"),
    "angel": ("ángel", "ملاك", "anjo", "Engel", "ангел"),
    "angel-visiting-you": ("un ángel que te visita", "ملاك يزورك", "um anjo te visitando", "ein Engel, der dich besucht", "ангел приходит к тебе"),
    "guardian-angel": ("un ángel de la guarda", "ملاك حارس", "um anjo da guarda", "ein Schutzengel", "ангел-хранитель"),
    "angel-delivering-message": ("un ángel que trae un mensaje", "ملاك يحمل رسالة", "um anjo trazendo um recado", "ein Engel mit einer Botschaft", "ангел приносит весть"),
    "angel-wings": ("alas de ángel", "أجنحة ملاك", "asas de anjo", "Engelsflügel", "ангельские крылья"),
    "crying-angel": ("un ángel llorando", "ملاك يبكي", "um anjo chorando", "ein weinender Engel", "плачущий ангел"),
    "angel-and-demon-together": ("un ángel y un demonio juntos", "ملاك وشيطان معاً", "um anjo e um demônio juntos", "Engel und Dämon zusammen", "ангел и демон вместе"),
    "rat": ("rata", "فأر", "rato", "Ratte", "крыса"),
    "rats-in-the-house": ("ratas en la casa", "فئران في البيت", "ratos na casa", "Ratten im Haus", "крысы в доме"),
    "rat-biting-you": ("una rata que te muerde", "فأر يعضك", "um rato te mordendo", "eine Ratte, die dich beißt", "крыса кусает тебя"),
    "many-rats": ("muchas ratas", "فئران كثيرة", "muitos ratos", "viele Ratten", "много крыс"),
    "white-rat": ("una rata blanca", "فأر أبيض", "um rato branco", "eine weiße Ratte", "белая крыса"),
    "dead-rat": ("una rata muerta", "فأر ميت", "um rato morto", "eine tote Ratte", "мёртвая крыса"),
    "rat-running-away": ("una rata que huye", "فأر يهرب", "um rato fugindo", "eine fliehende Ratte", "крыса убегает"),
    "alligator": ("caimán", "تمساح أمريكي", "jacaré", "Alligator", "аллигатор"),
    "alligator-attack": ("un ataque de caimán", "هجوم تمساح", "um ataque de jacaré", "ein Alligatorangriff", "нападение аллигатора"),
    "alligator-in-water": ("un caimán en el agua", "تمساح في الماء", "um jacaré na água", "ein Alligator im Wasser", "аллигатор в воде"),
    "alligator-in-house": ("un caimán en la casa", "تمساح في البيت", "um jacaré na casa", "ein Alligator im Haus", "аллигатор в доме"),
    "running-from-alligator": ("huir de un caimán", "الهرب من تمساح", "correr de um jacaré", "vor einem Alligator weglaufen", "бежать от аллигатора"),
    "baby-alligator": ("un caimán bebé", "تمساح صغير", "um filhote de jacaré", "ein Alligatorjunges", "детёныш аллигатора"),
    "dead-alligator": ("un caimán muerto", "تمساح ميت", "um jacaré morto", "ein toter Alligator", "мёртвый аллигатор"),
    "elephant": ("elefante", "فيل", "elefante", "Elefant", "слон"),
    "friendly-elephant": ("un elefante amistoso", "فيل ودود", "um elefante amigável", "ein freundlicher Elefant", "доброжелательный слон"),
    "elephant-chasing-you": ("un elefante que te persigue", "فيل يلاحقك", "um elefante te perseguindo", "ein Elefant, der dich jagt", "слон гонится за тобой"),
    "baby-elephant": ("un elefante bebé", "فيل صغير", "um filhote de elefante", "ein Elefantenjunges", "слонёнок"),
    "white-elephant": ("un elefante blanco", "فيل أبيض", "um elefante branco", "ein weißer Elefant", "белый слон"),
    "elephant-in-water": ("un elefante en el agua", "فيل في الماء", "um elefante na água", "ein Elefant im Wasser", "слон в воде"),
    "dead-elephant": ("un elefante muerto", "فيل ميت", "um elefante morto", "ein toter Elefant", "мёртвый слон"),
    "being-naked": ("estar desnudo en público", "التعرّي أمام الناس", "estar nu em público", "nackt in der Öffentlichkeit sein", "нагота на людях"),
    "naked-at-school": ("estar desnudo en la escuela", "التعرّي في المدرسة", "estar nu na escola", "nackt in der Schule sein", "голым в школе"),
    "naked-at-work": ("estar desnudo en el trabajo", "التعرّي في العمل", "estar nu no trabalho", "nackt bei der Arbeit sein", "голым на работе"),
    "nobody-noticing-you-naked": ("que nadie note que estás desnudo", "ألا يلاحظ أحد تعرّيك", "ninguém perceber que você está nu", "niemand bemerkt deine Nacktheit", "никто не замечает наготы"),
    "trying-to-cover-up": ("tratar de cubrirse", "محاولة ستر نفسك", "tentar se cobrir", "sich zuzudecken versuchen", "пытаться прикрыться"),
    "partially-naked": ("estar parcialmente desnudo", "التعرّي الجزئي", "estar parcialmente nu", "teilweise nackt sein", "частичная нагота"),
    "comfortable-being-naked": ("sentirse cómodo desnudo", "الراحة وأنت عارٍ", "sentir-se à vontade nu", "sich nackt wohlfühlen", "спокойно быть голым"),
    "work": ("trabajo", "عمل", "trabalho", "Arbeit", "работа"),
    "being-fired": ("que te despidan", "الفصل من العمل", "ser demitido", "gefeuert werden", "увольнение"),
    "being-late-for-work": ("llegar tarde al trabajo", "التأخر عن العمل", "chegar atrasado ao trabalho", "zu spät zur Arbeit kommen", "опоздать на работу"),
    "old-job": ("un trabajo viejo", "وظيفة قديمة", "um emprego antigo", "ein alter Job", "прежняя работа"),
    "angry-boss": ("un jefe enojado", "مدير غاضب", "um chefe bravo", "ein wütender Chef", "разгневанный начальник"),
    "new-job": ("un trabajo nuevo", "وظيفة جديدة", "um emprego novo", "ein neuer Job", "новая работа"),
    "overwhelmed-at-work": ("sentirse rebasado en el trabajo", "الإرهاق في العمل", "ficar sobrecarregado no trabalho", "bei der Arbeit überfordert sein", "перегруз на работе"),
    "phone": ("teléfono", "هاتف", "celular", "Telefon", "телефон"),
    "losing-your-phone": ("perder el teléfono", "فقدان هاتفك", "perder o celular", "das Telefon verlieren", "потерять телефон"),
    "broken-phone": ("un teléfono roto", "هاتف مكسور", "um celular quebrado", "ein kaputtes Telefon", "сломанный телефон"),
    "phone-not-working": ("un teléfono que no funciona", "هاتف لا يعمل", "um celular que não funciona", "ein Telefon, das nicht geht", "телефон не работает"),
    "unknown-caller": ("una llamada desconocida", "متصل مجهول", "uma ligação desconhecida", "ein unbekannter Anrufer", "неизвестный звонящий"),
    "missed-calls": ("llamadas perdidas", "مكالمات فائتة", "chamadas perdidas", "verpasste Anrufe", "пропущенные звонки"),
    "phone-ringing": ("un teléfono sonando", "هاتف يرن", "um celular tocando", "ein klingelndes Telefon", "телефон звонит"),
    "crawling": ("gatear", "زحف", "engatinhar", "Kriechen", "ползание"),
    "crawling-on-the-floor": ("gatear por el piso", "الزحف على الأرض", "engatinhar no chão", "auf dem Boden kriechen", "ползти по полу"),
    "crawling-like-a-baby": ("gatear como un bebé", "الزحف كرضيع", "engatinhar como um bebê", "wie ein Baby kriechen", "ползти как младенец"),
    "crawling-through-a-tunnel": ("gatear por un túnel", "الزحف في نفق", "engatinhar por um túnel", "durch einen Tunnel kriechen", "ползти по тоннелю"),
    "crawling-through-small-spaces": ("gatear por espacios estrechos", "الزحف في أماكن ضيقة", "engatinhar por espaços apertados", "durch enge Räume kriechen", "ползти в тесноте"),
    "unable-to-stand-crawling": ("no poder pararse y gatear en su lugar", "العجز عن الوقوف والزحف بدلاً منه", "não conseguir ficar de pé e engatinhar", "nicht stehen können und stattdessen kriechen", "не встать и ползти вместо этого"),
    "crawling-away-from-danger": ("gatear lejos del peligro", "الزحف بعيداً عن الخطر", "engatinhar para longe do perigo", "vor Gefahr wegkriechen", "уползать от опасности"),
    "someone-crawling-toward-you": ("alguien que gatea hacia ti", "شخص يزحف نحوك", "alguém engatinhando até você", "jemand, der auf dich zugekrochen kommt", "кто-то ползёт к тебе"),
    "tunnel": ("túnel", "نفق", "túnel", "Tunnel", "тоннель"),
    "light-at-end-of-tunnel": ("luz al final de un túnel", "نور في آخر النفق", "luz no fim do túnel", "Licht am Ende eines Tunnels", "свет в конце тоннеля"),
    "dark-tunnel": ("un túnel oscuro", "نفق مظلم", "um túnel escuro", "ein dunkler Tunnel", "тёмный тоннель"),
    "endless-tunnel": ("un túnel sin fin", "نفق لا ينتهي", "um túnel sem fim", "ein endloser Tunnel", "бесконечный тоннель"),
    "blocked-tunnel": ("un túnel bloqueado", "نفق مسدود", "um túnel bloqueado", "ein blockierter Tunnel", "заблокированный тоннель"),
    "train-in-a-tunnel": ("un tren en un túnel", "قطار في نفق", "um trem em um túnel", "ein Zug im Tunnel", "поезд в тоннеле"),
    "exiting-a-tunnel": ("salir de un túnel", "الخروج من نفق", "sair de um túnel", "einen Tunnel verlassen", "выйти из тоннеля"),
    "heights": ("alturas", "مرتفعات", "altura", "Höhen", "высота"),
    "standing-at-great-height": ("estar de pie a gran altura", "الوقوف على ارتفاع شاهق", "ficar em pé num lugar alto", "in großer Höhe stehen", "стоять на большой высоте"),
    "looking-down-from-heights": ("mirar hacia abajo desde una altura", "النظر إلى الأسفل من علو", "olhar de cima de uma altura", "aus der Höhe hinabsehen", "смотреть вниз с высоты"),
    "climbing-to-heights": ("subir a una altura", "التسلق إلى علو", "subir a uma altura", "in die Höhe klettern", "подниматься на высоту"),
    "high-ledge-no-railing": ("un borde alto sin barandal", "حافة عالية بلا درابزين", "uma beirada alta sem guarda-corpo", "ein hoher Sims ohne Geländer", "высокий уступ без перил"),
    "afraid-on-a-bridge": ("miedo en un puente alto", "الخوف على جسر عالٍ", "medo em uma ponte alta", "Angst auf einer hohen Brücke", "страх на высоком мосту"),
    "heights-without-falling": ("alturas sin caer", "مرتفعات بلا سقوط", "altura sem cair", "Höhe ohne Sturz", "высота без падения"),
    "nightmare": ("pesadilla", "كابوس", "pesadelo", "Albtraum", "кошмар"),
    "recurring-nightmare": ("una pesadilla recurrente", "كابوس متكرر", "um pesadelo recorrente", "ein wiederkehrender Albtraum", "повторяющийся кошмар"),
    "horrible-dream": ("un sueño horrible", "حلم فظيع", "um sonho horrível", "ein schrecklicher Traum", "ужасный сон"),
    "waking-from-nightmare": ("despertar de una pesadilla", "الاستيقاظ من كابوس", "acordar de um pesadelo", "aus einem Albtraum erwachen", "проснуться от кошмара"),
    "childhood-nightmare": ("una pesadilla de la infancia", "كابوس طفولة", "um pesadelo de infância", "ein Kindheitsalbtraum", "детский кошмар"),
    "nightmare-about-death": ("una pesadilla sobre la muerte", "كابوس عن الموت", "um pesadelo sobre a morte", "ein Albtraum vom Tod", "кошмар о смерти"),
    "sharing-a-nightmare": ("contarle a alguien una pesadilla", "رواية كابوس لأحد", "contar um pesadelo a alguém", "jemandem einen Albtraum erzählen", "рассказать о кошмаре"),
    "tsunami": ("tsunami", "تسونامي", "tsunami", "Tsunami", "цунами"),
    "tsunami-coming": ("un tsunami que se acerca", "تسونامي يتجه نحوك", "um tsunami vindo na sua direção", "ein Tsunami, der auf dich zukommt", "цунами идёт на тебя"),
    "running-from-tsunami": ("huir de un tsunami", "الهرب من تسونامي", "correr de um tsunami", "vor einem Tsunami weglaufen", "бежать от цунами"),
    "surviving-a-tsunami": ("sobrevivir a un tsunami", "النجاة من تسونامي", "sobreviver a um tsunami", "einen Tsunami überleben", "пережить цунами"),
    "tsunami-and-family": ("un tsunami con la familia cerca", "تسونامي والعائلة قريبة", "um tsunami com a família por perto", "ein Tsunami mit der Familie in der Nähe", "цунами рядом с семьёй"),
    "watching-tsunami-from-afar": ("ver un tsunami desde lejos", "مشاهدة تسونامي من بعيد", "ver um tsunami de longe", "einen Tsunami aus der Ferne sehen", "смотреть на цунами издалека"),
    "underwater-after-tsunami": ("estar bajo el agua después de un tsunami", "البقاء تحت الماء بعد تسونامي", "ficar debaixo d'água depois de um tsunami", "nach einem Tsunami unter Wasser sein", "под водой после цунами"),
    "swimming": ("nadar", "سباحة", "nadar", "Schwimmen", "плавание"),
    "swimming-easily": ("nadar con facilidad", "السباحة بيسر", "nadar com facilidade", "leicht schwimmen", "легко плыть"),
    "struggling-to-swim": ("forcejear para nadar", "التعثر في السباحة", "ter dificuldade para nadar", "sich beim Schwimmen abmühen", "с трудом плыть"),
    "swimming-underwater": ("nadar bajo el agua", "السباحة تحت الماء", "nadar debaixo d'água", "unter Wasser schwimmen", "плыть под водой"),
    "swimming-in-dirty-water": ("nadar en agua sucia", "السباحة في ماء وسخ", "nadar em água suja", "in schmutzigem Wasser schwimmen", "плыть в грязной воде"),
    "swimming-to-shore": ("nadar hacia la orilla", "السباحة إلى الشاطئ", "nadar até a margem", "ans Ufer schwimmen", "плыть к берегу"),
    "unable-to-swim": ("no poder nadar", "العجز عن السباحة", "não conseguir nadar", "nicht schwimmen können", "не уметь плавать"),
    "mirror": ("espejo", "مرآة", "espelho", "Spiegel", "зеркало"),
    "broken-mirror": ("un espejo roto", "مرآة مكسورة", "um espelho quebrado", "ein zerbrochener Spiegel", "разбитое зеркало"),
    "not-recognizing-yourself": ("no reconocerse en un espejo", "عدم التعرّف على نفسك في المرآة", "não se reconhecer no espelho", "sich im Spiegel nicht erkennen", "не узнать себя в зеркале"),
    "someone-else-in-mirror": ("otra persona en el espejo", "شخص آخر في المرآة", "outra pessoa no espelho", "jemand anderes im Spiegel", "в зеркале кто-то другой"),
    "cracked-mirror": ("un espejo agrietado", "مرآة متصدعة", "um espelho rachado", "ein gesprungener Spiegel", "треснувшее зеркало"),
    "mirror-in-dark-room": ("un espejo en un cuarto oscuro", "مرآة في غرفة مظلمة", "um espelho em um quarto escuro", "ein Spiegel in einem dunklen Zimmer", "зеркало в тёмной комнате"),
    "smashing-a-mirror": ("romper un espejo", "تحطيم مرآة", "quebrar um espelho", "einen Spiegel zerschlagen", "разбить зеркало"),
    "train": ("tren", "قطار", "trem", "Zug", "поезд"),
    "missing-a-train": ("perder un tren", "تفويت قطار", "perder um trem", "einen Zug verpassen", "опоздать на поезд"),
    "train-crash": ("un choque de tren", "تصادم قطار", "um descarrilamento", "ein Zugunglück", "крушение поезда"),
    "wrong-train": ("estar en el tren equivocado", "الركوب في القطار الخطأ", "estar no trem errado", "im falschen Zug sitzen", "не тот поезд"),
    "empty-train": ("un tren vacío", "قطار فارغ", "um trem vazio", "ein leerer Zug", "пустой поезд"),
    "train-station": ("una estación de tren", "محطة قطار", "uma estação de trem", "ein Bahnhof", "вокзал"),
    "stopping-a-train": ("detener un tren", "إيقاف قطار", "parar um trem", "einen Zug anhalten", "остановить поезд"),
    "plane": ("avión", "طائرة", "avião", "Flugzeug", "самолёт"),
    "plane-crash": ("accidente de avión", "تحطم طائرة", "queda de avião", "Flugzeugabsturz", "авиакатастрофа"),
    "flying-in-a-plane": ("volar en un avión", "الطيران في طائرة", "voar de avião", "in einem Flugzeug fliegen", "лететь на самолёте"),
    "turbulence-on-plane": ("turbulencia en un avión", "اضطراب جوي في الطائرة", "turbulência no avião", "Turbulenzen im Flugzeug", "турбулентность в самолёте"),
    "missing-a-plane": ("perder un avión", "تفويت طائرة", "perder um avião", "ein Flugzeug verpassen", "опоздать на самолёт"),
    "piloting-a-plane": ("pilotar un avión", "قيادة طائرة", "pilotar um avião", "ein Flugzeug steuern", "пилотировать самолёт"),
    "plane-landing": ("un avión aterrizando", "هبوط طائرة", "um avião pousando", "eine Landung", "посадка самолёта"),
    "grandparents": ("abuelos", "جدّان", "avós", "Großeltern", "бабушка и дедушка"),
    "deceased-grandparent": ("un abuelo o una abuela fallecidos", "جد أو جدة متوفيان", "um avô ou avó falecido", "ein verstorbener Großelternteil", "покойный дедушка или бабушка"),
    "grandmother-in-dream": ("tu abuela", "جدتك", "sua avó", "deine Großmutter", "бабушка"),
    "grandfather-in-dream": ("tu abuelo", "جدك", "seu avô", "dein Großvater", "дедушка"),
    "visiting-grandparents": ("visitar a los abuelos", "زيارة الجدّين", "visitar os avós", "die Großeltern besuchen", "в гостях у бабушки и дедушки"),
    "grandparents-house": ("la casa de los abuelos", "بيت الجدّين", "a casa dos avós", "das Haus der Großeltern", "дом бабушки и дедушки"),
    "arguing-with-grandparent": ("discutir con un abuelo o una abuela", "جدال مع جد أو جدة", "discutir com um avô ou avó", "Streit mit einem Großelternteil", "ссора с бабушкой или дедушкой"),
    "stairs": ("escaleras", "سلالم", "escadas", "Treppe", "лестница"),
    "climbing-stairs": ("subir escaleras", "صعود السلالم", "subir escadas", "Treppen steigen", "подниматься по лестнице"),
    "falling-down-stairs": ("caerse por las escaleras", "السقوط من السلالم", "cair da escada", "die Treppe hinunterstürzen", "упасть с лестницы"),
    "endless-stairs": ("escaleras sin fin", "سلالم لا تنتهي", "escadas sem fim", "endlose Treppen", "бесконечная лестница"),
    "broken-stairs": ("escaleras rotas", "سلالم مكسورة", "escadas quebradas", "kaputte Treppen", "сломанная лестница"),
    "descending-stairs": ("bajar las escaleras", "النزول على السلالم", "descer as escadas", "die Treppe hinuntergehen", "спускаться по лестнице"),
    "spiral-staircase": ("una escalera de caracol", "سلم حلزوني", "uma escada em caracol", "eine Wendeltreppe", "винтовая лестница"),
    "trapped": ("estar atrapado", "الاحتجاز", "ficar preso", "gefangen sein", "в ловушке"),
    "trapped-in-a-room": ("atrapado en un cuarto", "الاحتجاز في غرفة", "preso em um quarto", "in einem Zimmer gefangen", "заперт в комнате"),
    "trapped-underwater": ("atrapado bajo el agua", "الاحتجاز تحت الماء", "preso debaixo d'água", "unter Wasser gefangen", "заперт под водой"),
    "trapped-in-a-crowd": ("atrapado en una multitud", "الاحتجاز في زحام", "preso em uma multidão", "in einer Menge gefangen", "зажат в толпе"),
    "cant-open-door": ("no poder abrir una puerta", "العجز عن فتح باب", "não conseguir abrir uma porta", "eine Tür nicht öffnen können", "не открыть дверь"),
    "trapped-in-elevator": ("atrapado en un elevador", "الاحتجاز في مصعد", "preso em um elevador", "im Aufzug gefangen", "застрять в лифте"),
    "escaping-being-trapped": ("escapar después de estar atrapado", "الهروب بعد الاحتجاز", "escapar depois de ficar preso", "nach der Gefangenschaft entkommen", "вырваться из ловушки"),
    "being-lost": ("estar perdido", "الضياع", "estar perdido", "sich verlaufen", "заблудиться"),
    "lost-in-a-city": ("perderse en una ciudad", "الضياع في مدينة", "se perder numa cidade", "sich in einer Stadt verlaufen", "заблудиться в городе"),
    "lost-and-cant-find-home": ("estar perdido y no hallar el hogar", "الضياع والعجز عن إيجاد البيت", "estar perdido e não achar o caminho de casa", "verlaufen sein und das Zuhause nicht finden", "заблудиться и не найти дом"),
    "lost-with-no-phone": ("estar perdido sin teléfono", "الضياع بلا هاتف", "estar perdido sem celular", "verlaufen ohne Telefon", "заблудиться без телефона"),
    "asking-directions-dream": ("pedir indicaciones", "طلب الاتجاهات", "pedir informações", "nach dem Weg fragen", "спрашивать дорогу"),
    "lost-child-in-dream": ("un niño perdido", "طفل ضائع", "uma criança perdida", "ein verlorenes Kind", "потерявшийся ребёнок"),
    "finding-your-way": ("encontrar el camino después de perderse", "إيجاد الطريق بعد الضياع", "achar o caminho depois de se perder", "nach dem Verlaufen den Weg finden", "найти дорогу после блуждания"),
    "twins": ("mellizos", "توأم", "gêmeos", "Zwillinge", "близнецы"),
    "having-twins": ("tener mellizos", "إنجاب توأم", "ter gêmeos", "Zwillinge bekommen", "родить близнецов"),
    "identical-twins": ("mellizos idénticos", "توأم متطابق", "gêmeos idênticos", "eineiige Zwillinge", "однояйцевые близнецы"),
    "twin-babies": ("bebés mellizos", "رضيعان توأم", "bebês gêmeos", "Zwillingsbabys", "младенцы-близнецы"),
    "meeting-your-twin": ("conocer a tu mellizo", "لقاء توأمك", "encontrar seu gêmeo", "deinen Zwilling treffen", "встретить своего близнеца"),
    "twins-fighting": ("mellizos peleando", "توأم يتقاتلان", "gêmeos brigando", "streitende Zwillinge", "близнецы ссорятся"),
    "losing-one-twin": ("perder a un mellizo", "فقدان أحد التوأم", "perder um dos gêmeos", "einen Zwilling verlieren", "потерять одного из близнецов"),
    "lottery": ("lotería", "يانصيب", "loteria", "Lotterie", "лотерея"),
    "winning-the-lottery": ("ganar la lotería", "الفوز باليانصيب", "ganhar na loteria", "im Lotto gewinnen", "выиграть в лотерею"),
    "losing-lottery-ticket": ("perder un boleto de lotería", "فقدان تذكرة يانصيب", "perder um bilhete de loteria", "einen Lottoschein verlieren", "потерять лотерейный билет"),
    "sharing-lottery-win": ("compartir un premio de lotería", "تقاسم جائزة اليانصيب", "dividir um prêmio da loteria", "einen Lottogewinn teilen", "делить лотерейный выигрыш"),
    "fake-lottery-win": ("un premio de lotería falso", "فوز زائف باليانصيب", "um prêmio falso da loteria", "ein falscher Lottogewinn", "ложный лотерейный выигрыш"),
    "buying-lottery-ticket": ("comprar un boleto de lotería", "شراء تذكرة يانصيب", "comprar um bilhete de loteria", "einen Lottoschein kaufen", "купить лотерейный билет"),
    "lottery-numbers": ("números de lotería", "أرقام اليانصيب", "números da loteria", "Lottozahlen", "лотерейные числа"),
    "debt": ("deuda", "دين", "dívida", "Schuld", "долг"),
    "unable-to-pay-debt": ("no poder pagar una deuda", "العجز عن سداد دين", "não conseguir pagar uma dívida", "eine Schuld nicht zahlen können", "не суметь отдать долг"),
    "someone-owes-you": ("alguien que te debe", "شخص يدين لك", "alguém te devendo", "jemand schuldet dir etwas", "кто-то тебе должен"),
    "debt-collectors": ("cobradores de deuda", "محصّلو الديون", "cobradores de dívida", "Schuldeneintreiber", "коллекторы"),
    "paying-off-debt": ("saldar una deuda", "سداد دين", "quitar uma dívida", "Schulden tilgen", "погасить долг"),
    "hidden-debt": ("una deuda oculta", "دين خفي", "uma dívida escondida", "eine versteckte Schuld", "скрытый долг"),
    "inheriting-debt": ("heredar una deuda", "وراثة دين", "herdar uma dívida", "Schulden erben", "унаследовать долг"),
    "rabbit": ("conejo", "أرنب", "coelho", "Kaninchen", "кролик"),
    "white-rabbit": ("un conejo blanco", "أرنب أبيض", "um coelho branco", "ein weißes Kaninchen", "белый кролик"),
    "rabbit-running-away": ("un conejo que huye", "أرنب يهرب", "um coelho fugindo", "ein fliehendes Kaninchen", "кролик убегает"),
    "many-rabbits": ("muchos conejos", "أرانب كثيرة", "muitos coelhos", "viele Kaninchen", "много кроликов"),
    "dead-rabbit": ("un conejo muerto", "أرنب ميت", "um coelho morto", "ein totes Kaninchen", "мёртвый кролик"),
    "holding-a-rabbit": ("cargar un conejo", "حمل أرنب", "segurar um coelho", "ein Kaninchen halten", "держать кролика"),
    "rabbit-in-house": ("un conejo en la casa", "أرنب في البيت", "um coelho na casa", "ein Kaninchen im Haus", "кролик в доме"),
    "eating": ("comer", "أكل", "comer", "Essen", "еда"),
    "eating-with-family": ("comer en familia", "الأكل مع العائلة", "comer com a família", "mit der Familie essen", "есть с семьёй"),
    "eating-alone": ("comer solo", "الأكل وحدك", "comer sozinho", "allein essen", "есть в одиночестве"),
    "eating-at-restaurant": ("comer en un restaurante", "الأكل في مطعم", "comer em um restaurante", "im Restaurant essen", "есть в ресторане"),
    "eating-delicious-food": ("comer algo delicioso", "أكل طعام لذيذ", "comer comida gostosa", "etwas Köstliches essen", "есть вкусную еду"),
    "eating-spoiled-food": ("comer comida echada a perder", "أكل طعام فاسد", "comer comida estragada", "verdorbene Speisen essen", "есть испорченную еду"),
    "unable-to-eat": ("no poder comer", "العجز عن الأكل", "não conseguir comer", "nicht essen können", "не мочь есть"),
    "overeating": ("comer en exceso", "الإفراط في الأكل", "comer demais", "Essen ohne Maß", "переедание"),
    "sharing-food": ("compartir la comida", "تقاسم الطعام", "compartilhar comida", "Essen teilen", "делиться едой"),
    "cake": ("pastel", "كعكة", "bolo", "Kuchen", "торт"),
    "cooking-food": ("cocinar", "طبخ", "cozinhar", "Kochen", "готовка"),
    "boat": ("bote", "قارب", "barco", "Boot", "лодка"),
    "sinking-boat": ("un bote que se hunde", "قارب يغرق", "um barco afundando", "ein sinkendes Boot", "тонущая лодка"),
    "rowing-a-boat": ("remar un bote", "تجديف قارب", "remar um barco", "ein Boot rudern", "грести"),
    "boat-in-storm": ("un bote en una tormenta", "قارب في عاصفة", "um barco na tempestade", "ein Boot im Sturm", "лодка в бурю"),
    "empty-boat": ("un bote vacío", "قارب فارغ", "um barco vazio", "ein leeres Boot", "пустая лодка"),
    "luxury-yacht": ("un yate o bote de lujo", "يخت فاخر", "um iate de luxo", "eine Luxusjacht", "роскошная яхта"),
    "docking-a-boat": ("atracar un bote", "إرساء قارب", "atracar um barco", "ein Boot anlegen", "причалить лодку"),
    "celebrity": ("un famoso", "مشهور", "uma celebridade", "ein Promi", "знаменитость"),
    "meeting-a-celebrity": ("conocer a un famoso", "لقاء مشهور", "encontrar uma celebridade", "einen Promi treffen", "встретить знаменитость"),
    "becoming-famous": ("volverse famoso", "الشهرة", "ficar famoso", "berühmt werden", "стать знаменитым"),
    "celebrity-ignoring-you": ("un famoso que te ignora", "مشهور يتجاهلك", "uma celebridade te ignorando", "ein Promi, der dich ignoriert", "знаменитость тебя не замечает"),
    "dating-a-celebrity": ("salir con un famoso", "مواعدة مشهور", "namorar uma celebridade", "mit einem Promi gehen", "встречаться со знаменитостью"),
    "celebrity-ex": ("un famoso como ex", "مشهور كان شريكاً سابقاً", "uma celebridade como ex", "ein Promi als Ex", "знаменитость как бывший"),
    "old-friend": ("un amigo de antes", "صديق قديم", "um amigo antigo", "ein alter Freund", "старый друг"),
    "old-friend-from-school": ("un amigo de la escuela", "صديق من أيام المدرسة", "um amigo da escola", "ein Schulfreund von früher", "друг со школы"),
    "talking-to-old-friend": ("hablar con un amigo de antes", "الكلام مع صديق قديم", "conversar com um amigo antigo", "mit einem alten Freund sprechen", "говорить со старым другом"),
    "dead-old-friend": ("un amigo de antes fallecido", "صديق قديم متوفى", "um amigo antigo falecido", "ein verstorbener alter Freund", "покойный старый друг"),
    "arguing-with-old-friend": ("discutir con un amigo de antes", "جدال مع صديق قديم", "discutir com um amigo antigo", "Streit mit einem alten Freund", "ссора со старым другом"),
    "old-friend-changed": ("un amigo de antes que ha cambiado", "صديق قديم تغيّر", "um amigo antigo que mudou", "ein alter Freund, der sich verändert hat", "старый друг, который изменился"),
    "test": ("un examen", "اختبار", "uma prova", "eine Prüfung", "экзамен"),
    "unprepared-for-test": ("llegar sin preparar a un examen", "عدم الاستعداد لاختبار", "estar despreparado para uma prova", "unvorbereitet zu einer Prüfung", "не готов к экзамену"),
    "failing-a-test": ("reprobar un examen", "الرسوب في اختبار", "reprovar numa prova", "eine Prüfung nicht bestehen", "провалить экзамен"),
    "late-to-a-test": ("llegar tarde a un examen", "التأخر عن اختبار", "chegar atrasado a uma prova", "zu spät zu einer Prüfung kommen", "опоздать на экзамен"),
    "cannot-find-exam-room": ("no hallar el salón del examen", "العجز عن إيجاد قاعة الاختبار", "não achar a sala da prova", "den Prüfungsraum nicht finden", "не найти аудиторию экзамена"),
    "blank-test-paper": ("una hoja de examen en blanco", "ورقة اختبار فارغة", "uma prova em branco", "ein leeres Prüfungsblatt", "чистый экзаменационный лист"),
    "ring": ("un anillo", "خاتم", "um anel", "ein Ring", "кольцо"),
    "wedding-ring": ("un anillo de bodas", "خاتم زواج", "uma aliança", "ein Ehering", "обручальное кольцо"),
    "losing-a-ring": ("perder un anillo", "فقدان خاتم", "perder um anel", "einen Ring verlieren", "потерять кольцо"),
    "broken-ring": ("un anillo roto", "خاتم مكسور", "um anel quebrado", "ein zerbrochener Ring", "сломанное кольцо"),
    "engagement-ring": ("un anillo de compromiso", "خاتم خطوبة", "um anel de noivado", "ein Verlobungsring", "помолвочное кольцо"),
    "finding-a-ring": ("encontrar un anillo", "العثور على خاتم", "encontrar um anel", "einen Ring finden", "найти кольцо"),
    "flowers": ("flores", "ورود", "flores", "Blumen", "цветы"),
    "receiving-flowers": ("recibir flores", "تلقي ورود", "receber flores", "Blumen geschenkt bekommen", "получить цветы"),
    "wilted-flowers": ("flores marchitas", "ورود ذابلة", "flores murchas", "welke Blumen", "увядшие цветы"),
    "roses": ("rosas", "ورود حمراء", "rosas", "Rosen", "розы"),
    "picking-flowers": ("cortar flores", "قطف الورود", "colher flores", "Blumen pflücken", "собирать цветы"),
    "dead-flowers": ("flores muertas", "ورود ميتة", "flores mortas", "tote Blumen", "мёртвые цветы"),
    "keys": ("llaves", "مفاتيح", "chaves", "Schlüssel", "ключи"),
    "lost-keys": ("llaves perdidas", "مفاتيح ضائعة", "chaves perdidas", "verlorene Schlüssel", "потерянные ключи"),
    "finding-keys": ("encontrar las llaves", "العثور على المفاتيح", "encontrar as chaves", "Schlüssel finden", "найти ключи"),
    "house-keys": ("llaves de la casa", "مفاتيح البيت", "chaves de casa", "Hausschlüssel", "ключи от дома"),
    "broken-key": ("una llave rota", "مفتاح مكسور", "uma chave quebrada", "ein zerbrochener Schlüssel", "сломанный ключ"),
    "bunch-of-keys": ("un manojo de llaves", "باقة مفاتيح", "um molho de chaves", "ein Schlüsselbund", "связка ключей"),
    "shoes": ("zapatos", "أحذية", "sapatos", "Schuhe", "обувь"),
    "lost-shoes": ("zapatos perdidos", "أحذية ضائعة", "sapatos perdidos", "verlorene Schuhe", "потерянная обувь"),
    "new-shoes": ("zapatos nuevos", "أحذية جديدة", "sapatos novos", "neue Schuhe", "новая обувь"),
    "barefoot": ("estar descalzo", "الحفاء", "estar descalço", "barfuß sein", "босиком"),
    "worn-shoes": ("zapatos gastados", "أحذية بالية", "sapatos gastos", "abgetragene Schuhe", "стоптанная обувь"),
    "high-heels": ("tacones altos", "كعب عالٍ", "salto alto", "hohe Absätze", "высокие каблуки"),
    "dragon": ("un dragón", "تنين", "um dragão", "ein Drache", "дракон"),
    "flying-dragon": ("un dragón volando", "تنين محلّق", "um dragão voando", "ein fliegender Drache", "летящий дракон"),
    "dragon-attack": ("un dragón que te ataca", "تنين يهاجمك", "um dragão te atacando", "ein Drache, der dich angreift", "дракон нападает на тебя"),
    "dragon-fire": ("un dragón que echa fuego", "تنين ينفث النار", "um dragão cuspindo fogo", "ein feuerspeiender Drache", "дракон дышит огнём"),
    "friendly-dragon": ("un dragón amistoso", "تنين ودود", "um dragão amigável", "ein freundlicher Drache", "доброжелательный дракон"),
    "chinese-dragon": ("un dragón chino", "تنين صيني", "um dragão chinês", "ein chinesischer Drache", "китайский дракон"),
    "moon": ("la luna", "القمر", "a lua", "der Mond", "луна"),
    "full-moon": ("una luna llena", "بدر", "uma lua cheia", "ein Vollmond", "полная луна"),
    "crescent-moon": ("una luna creciente", "هلال", "uma lua crescente", "eine Mondsichel", "серп луны"),
    "red-moon": ("una luna roja", "قمر أحمر", "uma lua vermelha", "ein roter Mond", "красная луна"),
    "moonlight": ("claro de luna", "ضوء القمر", "luar", "Mondlicht", "лунный свет"),
    "moon-over-water": ("la luna sobre el agua", "القمر فوق الماء", "a lua sobre a água", "der Mond über dem Wasser", "луна над водой"),
    "colors": ("colores", "ألوان", "cores", "Farben", "цвета"),
    "seeing-red": ("ver rojo", "رؤية الأحمر", "ver vermelho", "Rot sehen", "видеть красное"),
    "wearing-black": ("vestir de negro", "ارتداء الأسود", "vestir preto", "Schwarz tragen", "носить чёрное"),
    "wearing-white": ("vestir de blanco", "ارتداء الأبيض", "vestir branco", "Weiß tragen", "носить белое"),
    "blue-in-a-dream": ("el color azul", "اللون الأزرق", "a cor azul", "die Farbe Blau", "синий цвет"),
    "yellow-in-a-dream": ("el color amarillo", "اللون الأصفر", "a cor amarela", "die Farbe Gelb", "жёлтый цвет"),
    "insects": ("insectos", "حشرات", "insetos", "Insekten", "насекомые"),
    "bees": ("abejas", "نحل", "abelhas", "Bienen", "пчёлы"),
    "cockroach": ("una cucaracha", "صرصور", "uma barata", "eine Kakerlake", "таракан"),
    "ants": ("hormigas", "نمل", "formigas", "Ameisen", "муравьи"),
    "flies": ("moscas", "ذباب", "moscas", "Fliegen", "мухи"),
    "insect-swarm": ("un enjambre de insectos", "سرب حشرات", "um enxame de insetos", "ein Insektenschwarm", "рой насекомых"),
    "intruder": ("un intruso", "متسلل", "um invasor", "ein Eindringling", "незваный гость"),
    "intruder-in-house": ("un intruso en la casa", "متسلل في البيت", "um invasor na casa", "ein Eindringling im Haus", "незваный в доме"),
    "hiding-from-intruder": ("esconderse de un intruso", "الاختباء من متسلل", "esconder-se de um invasor", "sich vor einem Eindringling verstecken", "прятаться от незваного"),
    "fighting-an-intruder": ("pelear con un intruso", "قتال متسلل", "lutar contra um invasor", "gegen einen Eindringling kämpfen", "биться с незваным"),
    "intruder-at-window": ("un intruso en la ventana", "متسلل عند النافذة", "um invasor na janela", "ein Eindringling am Fenster", "незваный у окна"),
    "unknown-intruder": ("un intruso desconocido", "متسلل مجهول", "um invasor desconhecido", "ein unbekannter Eindringling", "неизвестный незваный"),
    "being-ignored": ("que te ignoren", "التجاهل", "ser ignorado", "ignoriert werden", "тебя игнорируют"),
    "ignored-by-friend": ("que te ignore un amigo", "تجاهل صديق لك", "ser ignorado por um amigo", "von einem Freund ignoriert werden", "друг тебя игнорирует"),
    "ignored-by-family": ("que te ignore la familia", "تجاهل العائلة لك", "ser ignorado pela família", "von der Familie ignoriert werden", "семья тебя игнорирует"),
    "ignored-in-a-crowd": ("que te ignoren en una multitud", "التجاهل في الزحام", "ser ignorado no meio da multidão", "in einer Menge ignoriert werden", "игнорируют в толпе"),
    "partner-ignoring-you": ("una pareja que te ignora", "شريك يتجاهلك", "um parceiro te ignorando", "ein Partner, der dich ignoriert", "партнёр тебя игнорирует"),
    "calling-and-being-ignored": ("llamar y que te ignoren", "النداء والتجاهل", "chamar e ser ignorado", "rufen und ignoriert werden", "звать и быть не услышанным"),
    "crocodile": ("un cocodrilo", "تمساح", "um crocodilo", "ein Krokodil", "крокодил"),
    "crocodile-attack": ("un cocodrilo que te ataca", "تمساح يهاجمك", "um crocodilo te atacando", "ein Krokodil, das dich angreift", "крокодил нападает на тебя"),
    "crocodile-in-water": ("un cocodrilo en el agua", "تمساح في الماء", "um crocodilo na água", "ein Krokodil im Wasser", "крокодил в воде"),
    "crocodile-tears": ("lágrimas de cocodrilo", "دموع تماسيح", "lágrimas de crocodilo", "Krokodilstränen", "крокодиловы слёзы"),
    "baby-crocodile": ("un cocodrilo bebé", "تمساح صغير", "um filhote de crocodilo", "ein Krokodiljunges", "крокодильчик"),
    "dead-crocodile": ("un cocodrilo muerto", "تمساح ميت", "um crocodilo morto", "ein totes Krokodil", "мёртвый крокодил"),
    "dolphin": ("un delfín", "دولفين", "um golfinho", "ein Delfin", "дельфин"),
    "swimming-with-dolphins": ("nadar con delfines", "السباحة مع الدلافين", "nadar com golfinhos", "mit Delfinen schwimmen", "плавать с дельфинами"),
    "dolphin-jumping": ("un delfín saltando", "دولفين يقفز", "um golfinho pulando", "ein springender Delfin", "прыгающий дельфин"),
    "injured-dolphin": ("un delfín herido", "دولفين مصاب", "um golfinho ferido", "ein verletzter Delfin", "раненый дельфин"),
    "many-dolphins": ("muchos delfines", "دلافين كثيرة", "muitos golfinhos", "viele Delfine", "много дельфинов"),
    "dead-dolphin": ("un delfín muerto", "دولفين ميت", "um golfinho morto", "ein toter Delfin", "мёртвый дельфин"),
    "frog": ("una rana", "ضفدع", "um sapo", "ein Frosch", "лягушка"),
    "frog-turning-into-something": ("una rana transformándose", "ضفدع يتحوّل", "um sapo se transformando", "ein sich verwandelnder Frosch", "лягушка превращается"),
    "many-frogs": ("muchas ranas", "ضفادع كثيرة", "muitos sapos", "viele Frösche", "много лягушек"),
    "catching-a-frog": ("atrapar una rana", "الإمساك بضفدع", "pegar um sapo", "einen Frosch fangen", "поймать лягушку"),
    "frog-in-the-house": ("una rana en la casa", "ضفدع في البيت", "um sapo na casa", "ein Frosch im Haus", "лягушка в доме"),
    "dead-frog": ("una rana muerta", "ضفدع ميت", "um sapo morto", "ein toter Frosch", "мёртвая лягушка"),
    "fox": ("un zorro", "ثعلب", "uma raposa", "ein Fuchs", "лиса"),
    "red-fox": ("un zorro rojo", "ثعلب أحمر", "uma raposa vermelha", "ein roter Fuchs", "рыжая лиса"),
    "fox-in-the-house": ("un zorro en la casa", "ثعلب في البيت", "uma raposa na casa", "ein Fuchs im Haus", "лиса в доме"),
    "being-chased-by-a-fox": ("que te persiga un zorro", "مطاردة ثعلب لك", "ser perseguido por uma raposa", "von einem Fuchs verfolgt werden", "лиса гонится за тобой"),
    "friendly-fox": ("un zorro amistoso", "ثعلب ودود", "uma raposa amigável", "ein freundlicher Fuchs", "доброжелательная лиса"),
    "dead-fox": ("un zorro muerto", "ثعلب ميت", "uma raposa morta", "ein toter Fuchs", "мёртвая лиса"),
    "goat": ("una cabra", "ماعز", "um bode", "eine Ziege", "коза"),
    "climbing-goat": ("una cabra trepando", "ماعز يتسلق", "um bode subindo", "eine kletternde Ziege", "коза карабкается"),
    "goat-attack": ("una cabra que te ataca", "ماعز يهاجمك", "um bode te atacando", "eine Ziege, die dich angreift", "коза нападает на тебя"),
    "white-goat": ("una cabra blanca", "ماعز أبيض", "um bode branco", "eine weiße Ziege", "белая коза"),
    "herd-of-goats": ("un rebaño de cabras", "قطيع ماعز", "um rebanho de cabras", "eine Ziegenherde", "стадо коз"),
    "dead-goat": ("una cabra muerta", "ماعز ميت", "um bode morto", "eine tote Ziege", "мёртвая коза"),
    "giraffe": ("una jirafa", "زرافة", "uma girafa", "eine Giraffe", "жираф"),
    "tall-giraffe": ("una jirafa muy alta", "زرافة شديدة الطول", "uma girafa muito alta", "eine sehr hohe Giraffe", "очень высокий жираф"),
    "giraffe-eating": ("una jirafa comiendo hojas", "زرافة تأكل أوراقاً", "uma girafa comendo folhas", "eine Giraffe, die Blätter frisst", "жираф ест листья"),
    "baby-giraffe": ("una jirafa bebé", "زرافة صغيرة", "um filhote de girafa", "ein Giraffenjunges", "жирафёнок"),
    "running-giraffe": ("una jirafa corriendo", "زرافة تركض", "uma girafa correndo", "eine rennende Giraffe", "бегущий жираф"),
    "dead-giraffe": ("una jirafa muerta", "زرافة ميتة", "uma girafa morta", "eine tote Giraffe", "мёртвый жираф"),
    "camel": ("un camello", "جمل", "um camelo", "ein Kamel", "верблюд"),
    "riding-a-camel": ("montar un camello", "ركوب جمل", "montar um camelo", "ein Kamel reiten", "ехать на верблюде"),
    "thirsty-camel": ("un camello sediento", "جمل عطشان", "um camelo com sede", "ein durstiges Kamel", "жаждущий верблюд"),
    "camel-caravan": ("una caravana de camellos", "قافلة جمال", "uma caravana de camelos", "eine Kamelkarawane", "верблюжий караван"),
    "loaded-camel": ("un camello con una carga pesada", "جمل يحمل حملاً ثقيلاً", "um camelo com carga pesada", "ein schwer beladenes Kamel", "верблюд с тяжёлым грузом"),
    "dead-camel": ("un camello muerto", "جمل ميت", "um camelo morto", "ein totes Kamel", "мёртвый верблюд"),
    "bat": ("un murciélago", "خفاش", "um morcego", "eine Fledermaus", "летучая мышь"),
    "bats-in-the-house": ("murciélagos en la casa", "خفافيش في البيت", "morcegos na casa", "Fledermäuse im Haus", "летучие мыши в доме"),
    "bat-flying-at-you": ("un murciélago que vuela hacia ti", "خفاش يطير نحوك", "um morcego voando em você", "eine Fledermaus, die auf dich zufliegt", "летучая мышь летит на тебя"),
    "many-bats": ("un enjambre de murciélagos", "سرب خفافيش", "um bando de morcegos", "ein Schwarm Fledermäuse", "рой летучих мышей"),
    "white-bat": ("un murciélago blanco", "خفاش أبيض", "um morcego branco", "eine weiße Fledermaus", "белая летучая мышь"),
    "dead-bat": ("un murciélago muerto", "خفاش ميت", "um morcego morto", "eine tote Fledermaus", "мёртвая летучая мышь"),
    "deer": ("un venado", "غزال", "um cervo", "ein Reh", "олень"),
    "white-deer": ("un venado blanco", "غزال أبيض", "um cervo branco", "ein weißes Reh", "белый олень"),
    "deer-running-away": ("un venado que huye", "غزال يهرب", "um cervo fugindo", "ein fliehendes Reh", "олень убегает"),
    "injured-deer": ("un venado herido", "غزال مصاب", "um cervo ferido", "ein verletztes Reh", "раненый олень"),
    "stag-with-antlers": ("un ciervo con astas", "أيل بقرونه", "um veado com chifres", "ein Hirsch mit Geweih", "олень с рогами"),
    "dead-deer": ("un venado muerto", "غزال ميت", "um cervo morto", "ein totes Reh", "мёртвый олень"),
    "dinosaur": ("un dinosaurio", "ديناصور", "um dinossauro", "ein Dinosaurier", "динозавр"),
    "t-rex": ("un tiranosaurio", "تي ركس", "um tiranossauro", "ein T-Rex", "тираннозавр"),
    "dinosaur-chasing-you": ("un dinosaurio que te persigue", "ديناصور يلاحقك", "um dinossauro te perseguindo", "ein Dinosaurier, der dich jagt", "динозавр гонится за тобой"),
    "friendly-dinosaur": ("un dinosaurio amistoso", "ديناصور ودود", "um dinossauro amigável", "ein freundlicher Dinosaurier", "доброжелательный динозавр"),
    "baby-dinosaur": ("un dinosaurio bebé", "ديناصور صغير", "um filhote de dinossauro", "ein Dinosaurierjunges", "детёныш динозавра"),
    "dead-dinosaur": ("un dinosaurio muerto", "ديناصور ميت", "um dinossauro morto", "ein toter Dinosaurier", "мёртвый динозавр"),
    "beaver": ("un castor", "قندس", "um castor", "ein Biber", "бобр"),
    "beaver-dam": ("una presa de castor", "سد قندس", "uma barragem de castor", "ein Biberdamm", "бобровая плотина"),
    "beaver-building": ("un castor construyendo", "قندس يبني", "um castor construindo", "ein bauender Biber", "бобр строит"),
    "beaver-in-the-house": ("un castor en la casa", "قندس في البيت", "um castor na casa", "ein Biber im Haus", "бобр в доме"),
    "injured-beaver": ("un castor herido", "قندس مصاب", "um castor ferido", "ein verletzter Biber", "раненый бобр"),
    "dead-beaver": ("un castor muerto", "قندس ميت", "um castor morto", "ein toter Biber", "мёртвый бобр"),
    "clothes": ("ropa", "ملابس", "roupa", "Kleidung", "одежда"),
    "shopping-for-clothes": ("comprar ropa", "التسوّق لشراء ملابس", "comprar roupa", "Kleidung kaufen", "покупать одежду"),
    "torn-clothes": ("ropa rota", "ملابس ممزقة", "roupa rasgada", "zerrissene Kleidung", "рваная одежда"),
    "childhood-clothes": ("ropa de la infancia", "ملابس الطفولة", "roupa de infância", "Kindheitskleidung", "одежда детства"),
    "wrong-clothes": ("llevar la ropa equivocada", "ارتداء الملابس الخطأ", "estar com a roupa errada", "die falsche Kleidung tragen", "не та одежда"),
    "new-clothes": ("ropa nueva", "ملابس جديدة", "roupa nova", "neue Kleidung", "новая одежда"),
    "numbers": ("números", "أرقام", "números", "Zahlen", "числа"),
    "repeating-numbers": ("números que se repiten", "أرقام متكررة", "números que se repetem", "sich wiederholende Zahlen", "повторяющиеся числа"),
    "unlucky-number": ("un número de mala suerte", "رقم منحوس", "um número de azar", "eine Unglückszahl", "несчастливое число"),
    "counting-in-a-dream": ("contar", "العدّ", "contar", "Zählen", "счёт"),
    "wrong-number": ("un número equivocado", "رقم خاطئ", "um número errado", "eine falsche Zahl", "неверный номер"),
    "golden-number": ("un número dorado o ganador", "رقم ذهبي أو رابح", "um número dourado ou vencedor", "eine goldene oder gewinnende Zahl", "золотое или выигрышное число"),
    "eyes": ("ojos", "عينان", "olhos", "Augen", "глаза"),
    "losing-an-eye": ("perder un ojo", "فقدان عين", "perder um olho", "ein Auge verlieren", "потерять глаз"),
    "someone-watching-you": ("alguien que te observa", "شخص يراقبك", "alguém te observando", "jemand beobachtet dich", "кто-то смотрит на тебя"),
    "blindness": ("quedarse ciego", "فقدان البصر", "ficar cego", "erblinden", "ослепнуть"),
    "third-eye": ("un tercer ojo", "عين ثالثة", "um terceiro olho", "ein drittes Auge", "третий глаз"),
    "injured-eyes": ("ojos heridos o sangrando", "عينان مصابتان أو نازفتان", "olhos feridos ou sangrando", "verletzte oder blutende Augen", "раненые или кровоточащие глаза"),
    "hands": ("manos", "يدان", "mãos", "Hände", "руки"),
    "dirty-hands": ("manos sucias", "يدان وسختان", "mãos sujas", "schmutzige Hände", "грязные руки"),
    "injured-hands": ("manos heridas", "يدان مصابتان", "mãos feridas", "verletzte Hände", "раненые руки"),
    "holding-hands": ("tomarse de las manos", "إمساك الأيدي", "de mãos dadas", "Hände halten", "держать за руки"),
    "cut-off-hands": ("manos cortadas", "يدان مقطوعتان", "mãos decepadas", "abgeschnittene Hände", "отрубленные руки"),
    "washing-hands": ("lavarse las manos", "غسل اليدين", "lavar as mãos", "die Hände waschen", "мыть руки"),
    "crying": ("llorar", "بكاء", "choro", "Weinen", "плач"),
    "crying-in-public": ("llorar en público", "البكاء أمام الناس", "chorar em público", "in der Öffentlichkeit weinen", "плакать на людях"),
    "unable-to-cry": ("no poder llorar", "العجز عن البكاء", "não conseguir chorar", "nicht weinen können", "не мочь заплакать"),
    "someone-else-crying": ("otra persona llorando", "شخص آخر يبكي", "outra pessoa chorando", "jemand anderes weint", "кто-то другой плачет"),
    "crying-with-relief": ("llorar de alivio", "البكاء من الارتياح", "chorar de alívio", "vor Erleichterung weinen", "плакать от облегчения"),
    "inconsolable-crying": ("llanto inconsolable", "بكاء لا يُعزّى", "choro inconsolável", "untröstliches Weinen", "безутешный плач"),
    "anger": ("enojo", "غضب", "raiva", "Wut", "гнев"),
    "screaming-in-anger": ("gritar de enojo", "الصراخ من الغضب", "gritar de raiva", "vor Wut schreien", "кричать от гнева"),
    "someone-angry-at-you": ("alguien enojado contigo", "شخص غاضب منك", "alguém com raiva de você", "jemand ist wütend auf dich", "кто-то злится на тебя"),
    "unable-to-get-angry": ("no poder enojarse", "العجز عن الغضب", "não conseguir ficar com raiva", "nicht wütend werden können", "не мочь разозлиться"),
    "breaking-things-in-anger": ("romper cosas de enojo", "كسر الأشياء من الغضب", "quebrar coisas de raiva", "im Zorn Dinge zerbrechen", "ломать вещи в гневе"),
    "calm-after-anger": ("la calma después del enojo", "الهدوء بعد الغضب", "a calma depois da raiva", "Ruhe nach der Wut", "спокойствие после гнева"),
    "snake-and-water": ("serpiente y agua", "ثعبان وماء", "cobra e água", "Schlange und Wasser", "змея и вода"),
    "snake-and-baby": ("serpiente y bebé", "ثعبان ورضيع", "cobra e bebê", "Schlange und Baby", "змея и младенец"),
    "snake-and-fire": ("serpiente y fuego", "ثعبان ونار", "cobra e fogo", "Schlange und Feuer", "змея и огонь"),
    "snake-and-house": ("serpiente y casa", "ثعبان وبيت", "cobra e casa", "Schlange und Haus", "змея и дом"),
    "snake-and-pregnancy": ("serpiente y embarazo", "ثعبان وحمل", "cobra e gravidez", "Schlange und Schwangerschaft", "змея и беременность"),
    "baby-and-death": ("bebé y muerte", "رضيع وموت", "bebê e morte", "Baby und Tod", "младенец и смерть"),
    "baby-and-water": ("bebé y agua", "رضيع وماء", "bebê e água", "Baby und Wasser", "младенец и вода"),
    "death-and-water": ("muerte y agua", "موت وماء", "morte e água", "Tod und Wasser", "смерть и вода"),
    "death-and-fire": ("muerte y fuego", "موت ونار", "morte e fogo", "Tod und Feuer", "смерть и огонь"),
    "spider-and-snake": ("araña y serpiente", "عنكبوت وثعبان", "aranha e cobra", "Spinne und Schlange", "паук и змея"),
    "cat-and-dog": ("gato y perro", "قط وكلب", "gato e cachorro", "Katze und Hund", "кошка и собака"),
    "dog-and-snake": ("perro y serpiente", "كلب وثعبان", "cachorro e cobra", "Hund und Schlange", "собака и змея"),
    "wedding-and-death": ("boda y muerte", "زفاف وموت", "casamento e morte", "Hochzeit und Tod", "свадьба и смерть"),
    "wedding-and-blood": ("boda y sangre", "زفاف ودم", "casamento e sangue", "Hochzeit und Blut", "свадьба и кровь"),
    "teeth-and-blood": ("dientes y sangre", "أسنان ودم", "dentes e sangue", "Zähne und Blut", "зубы и кровь"),
    "fire-and-water": ("fuego y agua", "نار وماء", "fogo e água", "Feuer und Wasser", "огонь и вода"),
    "house-and-water": ("casa y agua", "بيت وماء", "casa e água", "Haus und Wasser", "дом и вода"),
}