ARPT = {}


def A(slug, ar, pt):
    ARPT[slug] = (ar, pt)


A("wolf", "غريزة، ولاء، انتماء اجتماعي، خطر، والتوتّر بين الاستقلال والقطيع", "instinto, lealdade, pertencimento social, perigo e a tensão entre independência e a alcateia")
A("black-wolf", "غريزة خفية، خطر غير مألوف، أو حضور قوي يصعب قراءته", "instinto escondido, perigo desconhecido ou uma presença poderosa difícil de ler")
A("white-wolf", "هدى، حماية، أو غريزة موثوقة تسيرك في الارتياب", "orientação, proteção ou um instinto confiável te guiando pela incerteza")
A("wolf-attack", "خيانة، نزاع اجتماعي، أو تهديد مفاجئ مرتبط بالولاء أو الثقة", "traição, conflito social ou uma ameaça súbita ligada à lealdade ou à confiança")
A("pack-of-wolves", "ضغط الجماعة، ديناميّات اجتماعية، أو شعور بأنك أقلّ عدداً أمام تهديد منسَّق", "pressão do grupo, dinâmicas sociais ou a sensação de estar em menor número diante de uma ameaça coordenada")
A("friendly-wolf", "غريزة موثوقة، ولاء، أو راحة مع طبيعتك الجامحة", "instinto confiável, lealdade ou conforto com a sua natureza indomada")
A("dead-wolf", "نهاية تهديد، ولاء ضائع، أو غريزة كُبتت أو أُهملت", "o fim de uma ameaça, lealdade perdida ou um instinto que foi silenciado ou ignorado")
A("howling-wolf", "نداء للصلة، إنذار، وحدة، أو إشارة ملحّة تطالب بالانتباه", "um chamado de ligação, aviso, solidão ou um sinal urgente pedindo atenção")
A("wolf-chasing-you", "خوف الخيانة، ضغط اجتماعي، أو تهديد غريزي يصعب الفرار منه", "medo de traição, pressão social ou uma ameaça instintiva difícil de deixar para trás")
A("bear", "قوّة، حماية، عزلة، وغريزة جبّارة قد تكون حانية أو خطرة", "força, proteção, solidão e um instinto poderoso que pode ser protetor ou perigoso")
A("black-bear", "قوّة خفية، تهديد غير مألوف، أو غريزة قويّة تحت سطح هادئ", "força escondida, ameaça desconhecida ou um instinto poderoso sob uma superfície calma")
A("brown-bear", "قوّة راسخة، غريزة حماية، أو قدرة يعتمد عليها حين تُحتاج", "força enraizada, instinto protetor ou um poder confiável que você pode chamar quando precisa")
A("bear-attack", "تهديد يطغى، حدّ حماية كُسر، أو خوف من قوّة جبّارة لا تُضبط", "ameaça avassaladora, um limite protetor rompido ou medo de uma força poderosa sem controle")
A("friendly-bear", "راحة مع قوّتك، سند حامٍ، أو قدرة موثوقة قريبة", "conforto com a própria força, apoio protetor ou um poder confiável por perto")
A("baby-bear", "إمكان هشّ، مسؤولية جديدة، أو قوّة ما زالت تنمو", "potencial vulnerável, uma responsabilidade nova ou uma força ainda em formação")
A("dead-bear", "حماية ضاعت، قوّة نقصت، أو نهاية مرحلة قويّة لكن شاقّة", "proteção perdida, força diminuída ou o fim de uma fase poderosa e difícil")
A("giant-bear", "تهديد مبالغ فيه، مسؤولية تطغى، أو قوّة تبدو أكبر من أن تُدار", "uma ameaça exagerada, responsabilidade avassaladora ou um poder grande demais para manejar")
A("running-from-bear", "تجنّب تهديد جدّي، خوف المواجهة، أو ضغط من قوّة جبّارة", "evitar uma ameaça séria, medo de confronto ou pressão de uma força poderosa")
A("lion", "شجاعة، سلطة، كبرياء، قيادة، والمواجهة بين الثقة والعدوان", "coragem, autoridade, orgulho, liderança e o confronto entre confiança e agressão")
A("lion-attack", "خوف السلطة، مواجهة مفاجئة، أو قوّة عدوانية تختبر شجاعتك", "medo da autoridade, confronto súbito ou uma força agressiva testando a sua coragem")
A("friendly-lion", "ثقة، احترام مكتسَب، أو حليف قوي يسند قيادتك", "confiança, respeito conquistado ou um aliado poderoso sustentando a sua liderança")
A("lion-chasing-you", "ضغط من سلطة، خوف المواجهة، أو تحدٍّ عدواني لثقتك", "pressão da autoridade, medo de confronto ou um desafio agressivo à sua confiança")
A("dead-lion", "سلطة ضاعت، ثقة نقصت، أو نهاية دور قيادة قوي", "autoridade perdida, confiança diminuída ou o fim de um papel poderoso de liderança")
A("roaring-lion", "إعلان جريء، إثبات سلطة، أو إنذار يطالب بالانتباه", "um anúncio ousado, afirmação de autoridade ou um aviso que exige atenção")
A("lion-cub", "ثقة تنمو، قيادة آخذة في الظهور، أو قوّة كامنة لم تكتمل بعد", "confiança em formação, liderança nascendo ou uma força potencial que ainda não cresceu por inteiro")
A("black-lion", "سلطة خفية، قوّة غير مألوفة، أو ثقة لم تُعرَف بعد", "autoridade escondida, poder desconhecido ou uma confiança que ainda não foi reconhecida")
A("white-lion", "سلطة صافية، قيادة نادرة، أو قوّة محترمة تنفرد عن غيرها", "autoridade pura, liderança rara ou uma força respeitada que se destaca do resto")
A("tiger", "شغف، عدوان، استقلال، وقوّة ضارية تطلب احتراماً وحدوداً حذرة", "paixão, agressão, independência e um poder feroz que exige respeito e limites cuidadosos")
A("tiger-attack", "عدوان مفاجئ، خوف مواجهة ضارية، أو تهديد قوي يختبر حدودك", "agressão súbita, medo de um confronto feroz ou uma ameaça poderosa testando os seus limites")
A("white-tiger", "قوّة نادرة، فرادة لافتة، أو غريزة قويّة تبرز عن المعتاد", "força rara, individualidade marcante ou um instinto poderoso que se destaca do comum")
A("black-tiger", "عدوان خفي، قوّة غير مألوفة، أو طاقة شديدة يصعب توقّعها", "agressão escondida, poder desconhecido ou uma força intensa difícil de prever")
A("friendly-tiger", "قوّة محترمة، ثقة، أو راحة مع طبيعتك الضارية والشغوفة", "força respeitada, confiança ou conforto com a sua natureza feroz e apaixonada")
A("dead-tiger", "حدّة ضاعت، شغف نقص، أو نهاية مرحلة عدوانية لكن قويّة", "intensidade perdida, paixão diminuída ou o fim de uma fase agressiva e poderosa")
A("tiger-chasing-you", "خوف مواجهة ضارية، ضغط من خصم شديد، أو قوّة عدوانية لا تُفلت", "medo de um confronto feroz, pressão de um rival intenso ou uma força agressiva inevitável")
A("baby-tiger", "قوّة تنمو، استقلال آخذ في الظهور، أو شغف لم ينضج تماماً", "força em formação, independência nascendo ou uma paixão que ainda não amadureceu")
A("giant-tiger", "تهديد مبالغ فيه، حدّة تطغى، أو قوّة تبدو أكبر من المقام", "uma ameaça exagerada, intensidade avassaladora ou um poder desproporcional à situação")
A("shark", "خطر، قسوة، خوف عميق، وتهديدات قويّة تسير خفية تحت السطح", "perigo, implacabilidade, medo fundo e as ameaças poderosas que se movem sem serem vistas sob a superfície")
A("shark-attack", "خطر مفاجئ، خوف الخيانة، أو تهديد قاسٍ يضرب بلا إنذار", "perigo súbito, medo de traição ou uma ameaça implacável que ataca sem aviso")
A("dead-shark", "نهاية تهديد جدّي، زوال خطر، أو خوف وُوجه أخيراً", "o fim de uma ameaça séria, um perigo removido ou um medo enfim enfrentado")
A("giant-shark", "تهديد مبالغ فيه، خوف يطغى، أو خطر يبدو أكبر بكثير من المقام", "uma ameaça exagerada, medo avassalador ou um perigo bem maior do que a situação pede")
A("swimming-with-sharks", "مخاطرة محسوبة، انكشاف للخطر، أو الإبحار في وضع مهدِّد بحذر متعمَّد", "risco calculado, exposição ao perigo ou navegar uma situação ameaçadora com cautela deliberada")
A("black-shark", "خطر خفي، قسوة غير مألوفة، أو تهديد يصعب رؤيته قادماً", "perigo escondido, implacabilidade desconhecida ou uma ameaça difícil de ver chegar")
A("shark-chasing-you", "خوف أن تكون الهدف، تهديد لا يُفلت، أو قلق من خصم قاسٍ", "medo de ser o alvo, uma ameaça sem saída ou ansiedade com um rival implacável")
A("shark-in-clear-water", "خطر ظاهر، مخاطرة معترَف بها، أو تهديد يسهل تقديره بوضوح", "um perigo visível, um risco reconhecido ou uma ameaça mais fácil de avaliar com clareza")
A("shark-bite", "فقد مفاجئ، خيانة موجعة، أو عاقبة فجائية من وضع خطر", "perda súbita, traição dolorosa ou uma consequência abrupta de uma situação perigosa")
A("owl", "حكمة، حدس، معرفة خفية، ووعي يرى بوضوح حتى في الظلام", "sabedoria, intuição, conhecimento escondido e uma consciência que enxerga mesmo no escuro")
A("white-owl", "بصيرة صافية، هدى روحي، أو حكمة تأتي في لحظة ذات معنى", "percepção pura, orientação espiritual ou sabedoria chegando num momento significativo")
A("black-owl", "معرفة خفية، حدس غير مألوف، أو حكمة مرتبطة بشيء لم يُفهم بعد", "conhecimento escondido, intuição desconhecida ou sabedoria ligada a algo ainda não compreendido")
A("owl-watching-you", "شعور بالمراقبة، هدى داخلي، أو وعي يطفو حول شأن كنت تتجنّبه", "a sensação de ser observado, orientação interior ou uma consciência emergindo sobre uma situação que você vinha evitando")
A("dead-owl", "حكمة ضاعت، حدس أُهمل، أو بصيرة جاءت متأخّرة عن نفعها", "sabedoria perdida, intuição ignorada ou uma percepção que chegou tarde demais para servir")
A("flying-owl", "حدس فاعل، منظور يُكتسَب بالمراقبة الهادئة، أو حكمة في حركة", "intuição ativa, perspectiva ganha pela observação quieta ou sabedoria em movimento")
A("owl-at-night", "بصيرة تطفو حين تنخفض الدفاعات، أو صفاء يُوجَد في زمن غير محسوم", "uma percepção que sobe quando as defesas baixam ou clareza achada num tempo incerto")
A("giant-owl", "شعور مبالغ فيه بالمراقبة، أو حكمة تبدو أكبر من المقام", "uma sensação exagerada de ser vigiado ou uma sabedoria maior do que a situação pede")
A("talking-owl", "هدى مباشر، صوت حكمة داخلي، أو رسالة يُراد لك أن تسجّلها بوعي", "orientação direta, uma voz interior de sabedoria ou uma mensagem que você precisa registrar de propósito")
A("butterfly", "تحوّل، خفّة، جمال هشّ، ومسار رقيق لأن تصير شيئاً جديداً", "transformação, leveza, beleza frágil e o processo delicado de tornar-se algo novo")
A("white-butterfly", "صفاء، سلام، أو علامة لطيفة ترافق تغيّراً شخصيّاً ذا معنى", "pureza, paz ou um sinal gentil acompanhando uma mudança pessoal significativa")
A("black-butterfly", "تحوّل غير مألوف، حزن، أو تغيّر يبدو غامضاً لا مهدِّداً", "uma transformação desconhecida, luto ou uma mudança que parece misteriosa em vez de ameaçadora")
A("colorful-butterfly", "تحوّل إبداعي، فرح، أو طور زاهٍ من التعبير الشخصي", "transformação criativa, alegria ou uma fase viva de expressão pessoal")
A("dead-butterfly", "تحوّل انقطع، أمل هشّ ضاع، أو تغيّر جميل لم يكتمل", "uma transformação interrompida, esperança frágil perdida ou uma mudança bela que não se completou")
A("giant-butterfly", "شعور مبالغ فيه بالتغيّر، أو تحوّل يبدو أكبر ممّا توقّعت", "uma sensação exagerada de mudança ou uma transformação maior do que o esperado")
A("butterfly-landing-on-you", "دلالة شخصية، علامة لطيفة، أو تحوّل يبدو موجَّهاً إليك أنت", "significado pessoal, um sinal gentil ou uma transformação que parece feita para você")
A("many-butterflies", "تغيّر واسع، تجدّد جماعي، أو تحوّلات صغيرة كثيرة تحدث معاً", "mudança espalhada, renovação coletiva ou muitas transformações pequenas acontecendo juntas")
A("butterfly-transformation", "جوهر مسار التغيّر نفسه: هشّ، تدريجي، ومُحرِّر في النهاية", "o processo central da mudança em si: frágil, gradual e no fim libertador")
A("fire", "تحوّل، شغف، غضب، تدمير، تطهير، وطاقة قد تدفئ أو تلتهم", "transformação, paixão, raiva, destruição, purificação e uma energia que aquece ou consome")
A("escaping-a-fire", "غريزة نجاة، تغيّر ملحّ، أو الخروج من وضع قبل أن يلتهمك", "instinto de sobrevivência, mudança urgente ou sair de uma situação antes que ela te consuma")
A("starting-a-fire", "مبادرة، غضب مكبوت، رغبة في فرض تغيّر، أو عواقب فعل متعمَّد", "iniciativa, raiva reprimida, o desejo de forçar uma mudança ou as consequências de um ato deliberado")
A("putting-out-a-fire", "إدارة أزمة، استعادة السيطرة، أو العمل المرهق لاحتواء وضع متقلّب", "gestão de crise, retomar o controle ou o trabalho exaustivo de conter uma situação instável")
A("wildfire", "تغيّر أو عاطفة ينتشران أسرع ممّا يُضبَط", "uma mudança ou emoção se espalhando mais rápido do que dá para controlar")
A("fire-smoke", "خطر محجوب، ارتباك حول وضع محتدم، أو إنذار مبكّر قبل الضرر الحقيقي", "um perigo encoberto, confusão em torno de uma situação acesa ou um aviso cedo antes do dano de verdade")
A("clothes-on-fire", "انكشاف علني، سمعة تضرّرت، أو هويّة تحت ضغط مفاجئ شديد", "exposição pública, reputação ferida ou uma identidade sob pressão súbita e intensa")
A("fire-in-the-sky", "اضطراب درامي، إنذار، أو رهبة أمام أحداث أكبر بكثير من السيطرة الشخصية", "um abalo dramático, um aviso ou o assombro diante de eventos bem maiores que o controle pessoal")
A("tornado", "عاطفة فوضوية، اضطراب مفاجئ، قلق، وتغيّر مدمّر يأتي بلا إنذار", "emoção caótica, reviravolta súbita, ansiedade e uma mudança destrutiva que chega sem aviso")
A("tornado-coming", "أزمة تقترب، رعب من تغيّر تراه ولا توقفه", "uma crise se aproximando, pavor de uma mudança que você vê e não consegue parar")
A("hiding-from-tornado", "حماية الذات، طلب الأمان، أو التأهّب لاضطراب خارج سيطرتك", "autoproteção, buscar segurança ou se preparar para um abalo fora do seu controle")
A("surviving-a-tornado", "صمود، ارتياح بعد اضطراب، أو اكتشاف قوّة في زمن مدمّر", "resiliência, alívio depois da turbulência ou descobrir força num período destrutivo")
A("multiple-tornadoes", "أوضاع متقلّبة عدّة معاً، أو قلق يتضاعف عبر مجالات الحياة", "várias situações voláteis ao mesmo tempo ou uma ansiedade se multiplicando por áreas da vida")
A("tornado-destroying-house", "اضطراب يضرب إحساسك بالبيت أو ثبات الأسرة أو أسسك الشخصية", "um abalo atingindo o seu senso de lar, a estabilidade da família ou os seus alicerces pessoais")
A("tornado-far-away", "مشاهدة اضطراب من بعيد، أو تهديد حقيقي لم يصر شخصيّاً بعد", "testemunhar a turbulência à distância ou uma ameaça real que ainda não ficou pessoal")
A("earthquake", "أسس تهتزّ، عدم استقرار مفاجئ، انعدام أمان، وتغيّر يضرب ما بدا دائماً", "alicerces abalados, instabilidade súbita, insegurança e uma mudança atingindo o que parecia permanente")
A("ground-shaking", "اهتزاز في ما حسبته صلباً: عمل أو علاقة أو عقيدة أو خطّة", "instabilidade no que você achava sólido: um emprego, uma relação, uma crença ou um plano")
A("building-collapsing", "انهيار بنية كنت تعتمد عليها، أو خوف أن الإنجازات لا تصمد", "a falha de uma estrutura de que você dependia ou o medo de que as conquistas não aguentem")
A("surviving-an-earthquake", "صمود في الاضطراب وإعادة التقييم التي تلي الصدمة الكبرى", "resistência no abalo e a reavaliação que vem depois de um choque grande")
A("earthquake-cracks", "انقسامات تنمو، صدع في علاقة، أو عدم استقرار خفي يصير ظاهراً", "divisões crescendo, uma fenda numa relação ou uma instabilidade escondida ficando visível")
A("earthquake-at-home", "عدم استقرار أسري، نزاع منزلي، أو انعدام أمان في أكثر أسسِك حميمية", "instabilidade familiar, conflito doméstico ou insegurança nos seus alicerces mais íntimos")
A("aftershocks", "آثار أزمة باقية، أو قلق أن الاضطراب لم ينتهِ بعد", "os efeitos que ficam de uma crise ou a ansiedade de que a ruptura ainda não acabou")
A("storm", "اضطراب عاطفي، نزاع، ضغط متراكم، وموسم صعب ينقضي في النهاية", "turbulência emocional, conflito, pressão acumulada e uma estação difícil que no fim passa")
A("thunder-and-lightning", "بصيرة مفاجئة، صدمة، غضب يتفرّغ، أو تفريج عاطفي درامي", "uma percepção súbita, choque, raiva se descarregando ou um alívio emocional dramático")
A("caught-in-a-storm", "شعور بالانكشاف وسط نزاع أو اضطراب بلا مأوى كافٍ", "sentir-se exposto no meio de um conflito ou tumulto sem abrigo suficiente")
A("storm-approaching", "توتّر يتصاعد، نزاع تحسّه قادماً، أو رعب قبل حديث صعب", "tensão crescendo, um conflito que você sente chegar ou pavor antes de uma conversa difícil")
A("sheltering-from-storm", "حماية الذات، صبر، وانتظار فترة لا تُقاتَل مباشرة", "autoproteção, paciência e esperar passar um período que não se enfrenta de frente")
A("storm-passing", "ارتياح، انفراج بعد نزاع، أو منظور هادئ يلي الاضطراب", "alívio, resolução depois do conflito ou a perspectiva calma que vem depois da turbulência")
A("storm-at-sea", "أزمة عاطفية في مياه عميقة: اضطراب في أقلّ أجزاء الحياة قابلية للضبط", "crise emocional em águas fundas: turbulência nas partes menos controláveis da vida")
A("blood", "قوّة حياة، حيوية، جرح، تضحية، روابط أسرية، وطاقة تُنفَق أو تُفقَد", "força vital, vitalidade, ferimento, sacrifício, laços de família e energia sendo gasta ou perdida")
A("bleeding", "طاقة تنزف، جرح عاطفي ما زال مفتوحاً، أو فقد لم يُعالَج", "energia escorrendo, uma ferida emocional ainda aberta ou uma perda que não foi olhada")
A("blood-on-hands", "ذنب، مسؤولية عن أذى، أو قلق من عواقب أفعالك", "culpa, responsabilidade por um dano ou ansiedade com as consequências dos seus atos")
A("blood-on-clothes", "أثر ظاهر لنزاع، انكشاف شيء كنت تأمل إبقاءه خاصّاً", "uma marca visível de conflito ou a exposição de algo que você esperava manter privado")
A("someone-else-bleeding", "قلق على آخر، تعاطف مع كفاحه، أو مشاهدة أذى لا توقفه", "preocupação com outra pessoa, empatia com o embate dela ou testemunhar um dano que você não consegue parar")
A("blood-on-the-floor", "ما بعد النزاع، دليل الضرر، أو وضع كلّف شيئاً بالفعل", "o depois do conflito, a evidência do dano ou uma situação que já cobrou um preço")
A("coughing-blood", "قلق صحّي، كلام حُبس طويلاً، أو حيوية تُنفَق من الداخل", "ansiedade de saúde, palavras guardadas tempo demais ou vitalidade sendo gasta por dentro")
A("hair", "هويّة، قوّة، جاذبية، صورة الذات، والسيطرة على كيف تعرض نفسك", "identidade, força, atrativo, imagem de si e o controle sobre como você se apresenta")
A("hair-falling-out", "فقدان ثقة، قلق صحّي، تقدّم العمر، أو خوف فقدان القوّة والجاذبية", "perda de confiança, ansiedade de saúde, o passar dos anos ou medo de perder força e atrativo")
A("cutting-hair", "تغيير متعمَّد للهويّة، إفلات من الماضي، أو إثبات سيطرة على صورتك", "uma mudança deliberada de identidade, soltar o passado ou afirmar controle sobre a própria imagem")
A("long-hair", "حرّية، قوّة، حسّية، صبر، أو هويّة نمت عبر زمن طويل", "liberdade, força, sensualidade, paciência ou uma identidade crescida ao longo de muito tempo")
A("white-or-gray-hair", "تقدّم العمر، حكمة، قلق من مرور الزمن، أو احترام اكتُسب بالتجربة", "envelhecer, sabedoria, ansiedade com o tempo passando ou respeito ganhado pela experiência")
A("someone-cutting-your-hair", "شخص آخر يؤثّر في هويّتك، أو سيطرة على صورتك أخذها سواك", "outra pessoa influenciando a sua identidade ou o controle da sua imagem nas mãos de outra pessoa")
A("washing-hair", "تصفية الذهن، تجدّد، أو إطلاق أفكار وهموم قديمة", "limpar a mente, renovação ou soltar pensamentos e preocupações antigas")
A("ex", "مشاعر معلّقة، إغلاق، حنين، أنماط تتكرّر، ودروس علاقة ماضية", "sentimentos sem fecho, encerramento, saudade, padrões que se repetem e lições de uma relação passada")
A("ex-boyfriend", "عاطفة لم تُتم، نمط من تلك العلاقة يتردّد في حياتك الآن", "emoção inacabada, um padrão daquela relação ecoando na sua vida atual")
A("ex-girlfriend", "حنين، مقارنة بالحاضر، أو سؤال معلّق من رابطة سابقة", "saudade, comparação com o presente ou uma pergunta sem resposta de um laço antigo")
A("ex-coming-back", "رغبة في إغلاق أو لقاء، أو نمط قديم يحاول العودة إلى حياتك", "um desejo de fecho ou reencontro ou um padrão antigo tentando voltar à sua vida")
A("arguing-with-ex", "غضب لم يُعبَّر، شأن لم يُغلق، أو جدال داخلي لم يُحسَم", "raiva sem voz, assunto inacabado ou um debate interno que nunca se resolveu")
A("ex-apologizing", "شوق إلى اعتراف، إصلاح للذات، أو منحك أنت الإغلاق الذي لم يقدّمه", "um anseio de reconhecimento, um conserto de si ou dar a si o fecho que a outra pessoa nunca ofereceu")
A("ex-with-someone-else", "غيرة، مقارنة، قبول نهاية، أو قلق من أن تُستبدَل", "ciúme, comparação, aceitação de um fim ou ansiedade de ser substituído")
A("ex-family", "تعلّقات باقية بعالم مشترك، أو حزن على صلات ضاعت مع العلاقة", "apegos que ficam a um mundo compartilhado ou luto pelas ligações perdidas junto com a relação")
A("cheating", "ثقة، انعدام أمان، ذنب، خيانة، ومخاوف الولاء في علاقة وثيقة", "confiança, insegurança, culpa, traição e medos sobre lealdade numa relação próxima")
A("partner-cheating", "انعدام أمان، خوف الهجر، أو حاجات لم تُلبَّ في العلاقة — لا دليل خيانة واقعة", "insegurança, medo de abandono ou necessidades sem resposta na relação — não evidência de uma traição real")
A("cheating-on-partner", "ذنب، رغبة لم تُقضَ، التزام منقسم، أو انتباه انسحب من العلاقة", "culpa, um desejo sem resposta, um compromisso dividido ou a atenção puxada para longe da relação")
A("being-caught-cheating", "خوف الانكشاف، خجل من اختيار خفي، أو قلق إخفاق من تحبّ", "medo da exposição, vergonha de uma escolha escondida ou ansiedade de decepcionar quem você ama")
A("confronting-a-cheater", "إثبات قيمتك، المطالبة بالصدق، أو التدرّب على مواجهة صعبة", "afirmar o seu valor, exigir honestidade ou ensaiar um confronto difícil")
A("forgiving-cheating", "معالجة الأذى، وزن الثقة مقابل التعلّق، أو استكشاف ما يتطلّبه الإصلاح", "processar a ferida, pesar a confiança contra o apego ou explorar o que um conserto exigiria")
A("recurring-cheating-dreams", "انعدام أمان عنيد أو سؤال ثقة يظلّ يطالب بالانتباه", "uma insegurança persistente ou uma pergunta de confiança que não para de pedir atenção")
A("wedding", "التزام، اتّحاد، انتقال، وعود علنية، ووصل أجزاء مختلفة من الحياة", "compromisso, união, transição, promessas públicas e a junção de partes diferentes da vida")
A("your-own-wedding", "التزام كبير يقترب، جاهزية للاتّحاد، أو قلق من اختيار مُلزِم", "um compromisso grande se aproximando, prontidão para a união ou ansiedade com uma escolha que amarra")
A("someone-elses-wedding", "مشاهدة تغيّر في الآخرين، مقارنة، أو أسئلتك أنت عن الالتزام", "testemunhar mudança nos outros, comparação ou as suas próprias perguntas sobre compromisso")
A("wedding-going-wrong", "شكوك في التزام، خوف فشل علني، أو ضغط حول قرار كبير", "dúvidas sobre um compromisso, medo de um fracasso público ou pressão em torno de uma decisão grande")
A("wedding-dress", "هويّة داخل الالتزام، صفاء النيّة، أو كيف تعرض اختياراً حياتيّاً كبيراً", "identidade dentro do compromisso, pureza de intenção ou o jeito como você apresenta uma escolha grande de vida")
A("marrying-a-stranger", "التزام بشيء مجهول: دور جديد أو مسار أو جانب منك لم يُفهم بعد", "compromisso com algo desconhecido: um papel novo, um caminho ou uma parte de você ainda sem compreensão")
A("runaway-bride-or-groom", "تردّد في اللحظة الأخيرة، تجنّب الالتزام، أو شكوك لم تُقَل", "recuo na última hora, evitação de compromisso ou dúvidas que não foram ditas")
A("kissing", "مودة، رغبة، صلة، قبول، وحميمية تُقدَّم أو تُتلقَّى", "afeto, desejo, ligação, aceitação e uma intimidade oferecida ou recebida")
A("kissing-a-stranger", "انجذاب إلى شيء غير مألوف، إمكان جديد، أو رغبة لم يُعتَرف بها", "atração por algo desconhecido, uma possibilidade nova ou um desejo ainda sem reconhecimento")
A("kissing-an-ex", "حنين، انجذاب معلّق، أو عودة إلى من كنت في تلك العلاقة", "saudade, atração sem fecho ou religar-se a quem você era naquela relação")
A("kissing-a-friend", "مودة تتعمّق، حدود تتلاشى، أو فضول حول إمكان العلاقة", "afeto se aprofundando, limites se embaralhando ou curiosidade sobre o potencial de uma relação")
A("being-kissed-unexpectedly", "مودة مفاجئة، حدود تُتجاوز، أو انتباه لم تتوقّعه", "afeto de surpresa, limites atravessados ou uma atenção que você não tinha previsto")
A("refusing-a-kiss", "حدود، احترام للذات، أو رفض حميمية لا تبدو صحيحة", "limites, respeito por si ou recusar uma intimidade que não se sente certa")
A("kissing-a-celebrity", "تطلّع، رغبة في الاعتراف، أو انجذاب إلى صفات يمثّلها ذلك الشخص", "aspiração, desejo de reconhecimento ou atração pelas qualidades que aquela pessoa representa")
A("sex", "رغبة، حميمية، قوّة، هشاشة، والجوانب منك أو من غيرك تريد الاقتراب منها", "desejo, intimidade, poder, vulnerabilidade e as partes de você ou dos outros das quais você quer se aproximar")
A("sex-with-a-coworker", "اعتراف، نفوذ، قرب، وإعجاب في العمل أكثر منه انجذاباً حرفيّاً بالشخص", "reconhecimento, poder, proximidade e admiração no trabalho mais do que atração literal pela pessoa")
A("sex-with-an-ex", "تعلّق لم يُتم، حنين إلى من كنت مع ذلك الشخص، أو حاجة كانت تلك العلاقة تقضيها", "apego inacabado, saudade de quem você era com aquela pessoa ou uma necessidade que aquela relação um dia atendeu")
A("sex-with-a-stranger", "فضول حول جانب غير مألوف منك، جدّة، أو رغبة لم تُسمَّ بعد", "curiosidade sobre uma parte desconhecida de você, novidade ou um desejo que ainda não tem nome")
A("sex-with-a-friend", "قرب يتعمّق، حدود تتلاشى، أو صفة فيه تريدها أقرب إلى حياتك", "proximidade se aprofundando, limites se embaralhando ou uma qualidade nele que você quer mais perto da sua vida")
A("sex-with-your-boss", "نفوذ، إقرار، وطموح — تريد انتباه السلطة أكثر من الشخص الذي يمسكها", "poder, aprovação e ambição — querer a atenção da autoridade mais do que a pessoa que a exerce")
A("sex-with-someone-you-dislike", "صفة مرفوضة تطالب بالاندماج، أو نزاع يحمل شحنة أكبر ممّا تعترف", "um traço rejeitado pedindo integração ou um conflito com mais carga do que você admite")
A("sex-with-your-partner", "طمأنينة، إصلاح، أو رغبة في قرب تزاحمه حياة النهار", "um consolo, um conserto ou o desejo de uma proximidade que a vida comum vem empurrando para o lado")
A("mother", "رعاية، أصل، حماية، أنماط أسرية، وأوّل قالب للحبّ والعناية", "nutrição, origem, proteção, padrões da família e o primeiro molde de amor e cuidado")
A("walking-with-my-mother", "مسيرة حياة مشتركة، هدى، قرب أو مسافة عاطفية، أنماط أسرية موروثة، وانتقال تسيران فيه معاً", "uma jornada compartilhada, orientação, proximidade ou distância emocional, padrões herdados e uma transição que vocês atravessam juntas")
A("mother-dying", "خوف فقدان السند، علاقة بها تتغيّر، أو تحوّل في دورك أنت الراعي", "medo de perder o apoio, uma relação com ela em mudança ou uma virada no seu próprio papel de cuidado")
A("deceased-mother", "حزن، عزاء، رابطة مستمرّة، أو هدى مرتبط بذكراها", "luto, consolo, um laço que continua ou uma orientação ligada à memória dela")
A("arguing-with-mother", "نزاع على الاستقلال، أنماط أسرية قديمة، أو صدام داخلي مع قيم موروثة", "conflito sobre autonomia, padrões antigos da família ou um embate interno com valores herdados")
A("mother-hugging-you", "حاجة إلى عزاء، مصالحة، أو طمأنينة في موسم متطلّب", "necessidade de consolo, reconciliação ou um aconchego numa estação exigente")
A("becoming-a-mother", "دور رعاية جديد، مسؤولية إبداعية، أو تماهي مع الجانب الحاني منك", "um papel novo de cuidado, responsabilidade criativa ou identificação com a parte nutridora de você")
A("angry-mother", "ذنب، خوف الرفض، أو صوت نقد داخلي مرتبط بسلطة مبكّرة", "culpa, medo de desaprovação ou uma voz crítica interior ligada a uma autoridade precoce")
A("father", "سلطة، هدى، حماية، توقّع، وأوّل قالب للبنية والإقرار", "autoridade, orientação, proteção, expectativa e o primeiro molde de estrutura e aprovação")
A("father-dying", "خوف فقدان الهدى، علاقة بالسلطة تتغيّر، أو تحوّل في دورك الحامي", "medo de perder a orientação, uma relação com a autoridade em mudança ou uma virada no seu próprio papel protetor")
A("deceased-father", "حزن، رابطة مستمرّة، أحاديث لم تُتم، أو هدى مرتبط بذكراه", "luto, um laço que continua, conversas inacabadas ou uma orientação ligada à memória dele")
A("arguing-with-father", "نزاع مع السلطة، كفاح من أجل الإقرار، أو صدام داخلي مع توقّعات موروثة", "conflito com a autoridade, uma luta por aprovação ou um embate interno com expectativas herdadas")
A("father-hugging-you", "حاجة إلى إقرار، مصالحة، أو طمأنينة من مصدر بنية وحماية", "necessidade de aprovação, reconciliação ou um aconchego vindo de uma fonte de estrutura e proteção")
A("absent-father", "هدى ناقص، حاجات سند لم تُلبَّ، أو اعتماد على النفس بُني حيث انتُظرت الحماية", "orientação em falta, necessidades de apoio sem resposta ou uma autonomia construída onde se esperava proteção")
A("angry-father", "خوف الحكم، نقد داخلي، أو ضغط مرتبط بسلطة مبكّرة", "medo de julgamento, crítica interiorizada ou pressão ligada a uma autoridade precoce")
A("brother", "ولاء، تنافس، تاريخ مشترك، حماية، ومرآة لصفاتك في هيئة مألوفة", "lealdade, rivalidade, história compartilhada, proteção e um espelho dos seus traços numa forma familiar")
A("brother-dying", "خوف فقدان رابطة العمر، علاقة تتغيّر، أو قلق على مساره", "medo de perder um laço de uma vida inteira, uma relação em mudança ou preocupação com o caminho dele")
A("arguing-with-brother", "تنافس، احتكاك أسري قديم، أو نزاع داخلي يُسقَط على خصم مألوف", "rivalidade, atrito antigo da família ou um conflito interno projetado num oponente conhecido")
A("brother-in-danger", "حماية، ذنب بسبب المسافة، أو قلق من وضع لا تضبطه لأجله", "proteção, culpa pela distância ou ansiedade com uma situação que você não controla por ele")
A("older-brother", "هدى، مقارنة، حماية، أو سلطة تُعاش من داخل جيلك", "orientação, comparação, proteção ou uma autoridade vivida de dentro da sua própria geração")
A("younger-brother", "مسؤولية، حنين، أو جانب أصغر منك يطلب الانتباه", "responsabilidade, saudade ou uma parte mais jovem de você pedindo atenção")
A("estranged-brother", "تاريخ أسري معلّق، رغبة في إصلاح، أو حزن على رابطة بردت", "história familiar sem fecho, um desejo de conserto ou luto por um laço que esfriou")
A("sister", "قرب، مقارنة، تعاطف، تاريخ مشترك، وانعكاس مألوف لحياتك الداخلية", "proximidade, comparação, empatia, história compartilhada e um reflexo familiar da sua vida interior")
A("sister-dying", "خوف فقدان القرب، رابطة تتغيّر، أو قلق على سلامتها", "medo de perder a proximidade, um laço em mudança ou preocupação com o bem-estar dela")
A("arguing-with-sister", "تنافس، أحقاد قديمة، أو خلاف مع جانب منك تمثّله هي", "competição, mágoas antigas ou um desacordo com uma parte de você que ela representa")
A("sister-crying", "تعاطف مع كفاحها، ذنب، أو حزن داخل الأسرة يطلب الاعتراف", "empatia com o embate dela, culpa ou uma tristeza da família pedindo ser reconhecida")
A("older-sister", "هدى، مقارنة، رعاية تلقّيتها، أو معايير تقيس نفسك بها", "orientação, comparação, o cuidado que você recebeu ou padrões contra os quais você se mede")
A("younger-sister", "حماية، مسؤولية، أو جانب أصغر رقيق منك", "proteção, responsabilidade ou uma parte mais jovem e terna de você")
A("protecting-your-sister", "ولاء تحت التهديد، واجب أسري، أو الدفاع عن جانب هشّ من حياتك", "lealdade sob ameaça, dever de família ou defender uma parte vulnerável da sua própria vida")
A("god", "معنى، ضمير، تسليم، مساءلة، والشوق إلى هدى أكبر من الذات", "sentido, consciência, entrega, responsabilidade e o anseio de uma orientação maior que o eu")
A("talking-to-god", "بحث عن اتجاه، حوار داخلي مع الضمير، أو سؤال أكبر من أن يُحمَل وحدك", "uma busca de direção, um diálogo interior com a consciência ou uma pergunta grande demais para carregar sozinho")
A("seeing-god", "رهبة، حاجة إلى طمأنينة، أو لقاء أعمق مصدر معنى في حياتك", "assombro, necessidade de consolo ou contato com a fonte mais funda de sentido na sua vida")
A("praying-to-god", "تسليم عبء، تأمّل صادق، أو طلب عون لم تجهر به", "entregar um fardo, reflexão sincera ou pedir uma ajuda que você ainda não falou em voz alta")
A("gods-voice", "بصيرة تطالب بالانتباه، ضمير يتكلّم بوضوح، أو هدى تحسّه أصلاً", "uma percepção pedindo atenção, a consciência falando com clareza ou uma orientação que você já sente")
A("being-judged-by-god", "ذنب، فحص أخلاقي للذات، أو خوف التقصير عن أعمق معاييرك", "culpa, exame moral de si ou medo de ficar aquém dos seus próprios padrões mais fundos")
A("receiving-a-blessing", "طمأنينة، امتنان، إذن بالمضي، أو أمل في الارتياب", "um consolo, gratidão, permissão para seguir ou esperança no meio da incerteza")
A("illness", "هشاشة، حاجات مُهملة، قلق على الصحّة، وجانب من الحياة يطلب رعاية وراحة", "vulnerabilidade, necessidades abandonadas, ansiedade com a saúde e uma parte da vida pedindo cuidado e descanso")
A("being-sick", "طاقة نضبت، حاجة أُهملت، أو قلق على جسدك وطاقتك", "energia esgotada, uma necessidade abandonada ou ansiedade com o corpo e a capacidade")
A("terminal-illness", "خوف نهاية، إلحاح الزمن، أو صورة درامية لشيء يبدو بلا علاج", "medo de um fim, urgência do tempo ou uma imagem dramática de algo que parece sem conserto")
A("sick-family-member", "قلق على حبيب، حزن استباقي، أو همّ على ثبات الأسرة", "preocupação com alguém querido, luto antecipado ou inquietação com a estabilidade da família")
A("recovering-from-illness", "شفاء، قوّة مستعادة، أو خروج من فترة مستنزِفة", "cura, força restaurada ou a saída de um período que drenava")
A("undiagnosed-illness", "همّ بلا اسم، مشكلة تُحسّ ولم تُفهم بعد، أو قلق صحّي يطلب تعريفاً", "uma preocupação sem nome, um problema sentido e ainda sem compreensão ou ansiedade de saúde buscando definição")
A("vomiting-in-a-dream", "رفض شيء سامّ، إطلاق ما لا يُستبقى، أو تطهير عاطفي ملحّ", "rejeitar algo tóxico, soltar o que não dá para reter ou um esvaziamento emocional urgente")
A("ghost", "ماضٍ معلّق، ذاكرة، ذنب، حضور ما انتهى، ومشاعر تأبى أن تبقى مدفونة", "passado sem fecho, memória, culpa, presença do que terminou e sentimentos que se recusam a ficar enterrados")
A("ghost-of-a-loved-one", "روابط مستمرّة، حزن لم يُتم، أو عزاء ورسائل مرتبطة بمن رحل", "laços que continuam, luto inacabado ou consolo e recados ligados a alguém que morreu")
A("haunted-by-a-ghost", "حدث ماضٍ أو خطأ أو ذاكرة يظلّ يقتحم الحياة الحاضرة", "um evento passado, um erro ou uma memória que não para de invadir a vida presente")
A("friendly-ghost", "ذاكرة حميدة، حنين لطيف، أو صلح مع الماضي", "uma memória benigna, uma saudade gentil ou a paz sendo feita com o passado")
A("ghost-attacking-you", "الماضي يتدخّل بنشاط في الحاضر، أو ذنب يشعر بالعقاب", "o passado interferindo ativamente no presente ou uma culpa que se sente punitiva")
A("ghost-in-your-house", "تاريخ أسري معلّق، أو تأثير قديم ما زال يسكن فضاءك الداخلي", "história familiar sem fecho ou uma influência antiga ainda ocupando o seu espaço interior")
A("becoming-a-ghost", "شعور بأنك غير مرئي، منقطع، أو تتلاشى من وضع كنت تنتمي إليه", "sentir-se invisível, desligado ou sumindo de uma situação em que você um dia pertenceu")
A("demon", "نزاع داخلي، إغراء، خوف، خجل، وقوى مدمّرة يعطيها الحلم وجهاً", "conflito interno, tentação, medo, vergonha e forças destrutivas ganhando um rosto na mente que sonha")
A("being-attacked-by-demon", "معركة داخلية مع خوف أو إدمان أو غضب أو خجل يبدو أقوى منك", "uma batalha interior com medo, vício, raiva ou vergonha que parece mais forte do que você")
A("demon-possession", "شعور بأن عاطفة أو عادة أو نفوذاً يتجاوز قصدك ويسيطر عليك", "sentir-se controlado por uma emoção, um hábito ou uma influência que atropela as suas intenções")
A("fighting-a-demon", "مقاومة فاعلة لنمط مدمّر، وجهد استعادة السيطرة", "resistência ativa contra um padrão destrutivo e o esforço de retomar o controle")
A("demon-in-your-house", "نفوذ مدمّر داخل حياتك الخاصّة أو أسرتك أو عالمك الداخلي", "uma influência destrutiva dentro da vida privada, da família ou do seu mundo interior")
A("demon-watching-you", "رعب، ذنب، أو نفوذ مهدِّد يُحسّ ولم يُواجَه بعد", "pavor, culpa ou uma influência ameaçadora sentida e ainda sem confronto")
A("casting-out-a-demon", "تحرّر، وضع حدود، أو طرد تأثير ضارّ من حياتك", "libertação, traçar um limite ou expulsar uma influência nociva da sua vida")
A("angel", "حماية، هدى، أمل، ضمير، وطمأنينة تأتي في موسم صعب", "proteção, orientação, esperança, consciência e um consolo chegando numa estação difícil")
A("angel-visiting-you", "حاجة إلى طمأنينة، شعور بأنك تُهدى، أو أمل في الارتياب", "necessidade de consolo, a sensação de ser guiado ou esperança no meio da incerteza")
A("guardian-angel", "حماية، سند قد تستخفّ به، أو رغبة في أن يرعاك أحد", "proteção, um apoio que você talvez esteja subestimando ou o desejo de que alguém vigie por você")
A("angel-delivering-message", "بصيرة يريد ذهنك الأعمق أن يعترف بها الوعي", "uma percepção que a sua mente mais funda quer que a consciência registre")
A("angel-wings", "تطلّع، حرّية روحية، أو رغبة في الارتفاع فوق وضع ثقيل", "aspiração, liberdade espiritual ou o desejo de subir acima de uma situação pesada")
A("crying-angel", "رحمة، حزن يُشهَد، أو أسى على وضع لا يطيقه الضمير", "compaixão, um luto testemunhado ou tristeza diante de uma situação que a consciência não aceita")
A("angel-and-demon-together", "نزاع أخلاقي، قرار بين مسار بنّاء وآخر مدمّر", "um conflito moral, uma decisão entre um caminho construtivo e um destrutivo")
A("rat", "ارتياب، ذنب، بقاء، مشكلات خفية، وقلق يقرض في الخلفية بهدوء", "desconfiança, culpa, sobrevivência, problemas escondidos e ansiedades roendo quietas no fundo")
A("rats-in-the-house", "مشكلة خفية تنخر حياتك الخاصّة، أو قلق داخل مكان يُفتَرض أن يطمئن", "um problema escondido corroendo a vida privada ou um desassossego dentro de um lugar que deveria ser seguro")
A("rat-biting-you", "خيانة صغيرة، ذنب مزعج، أو شأن بسيط بدأ يؤذي حقّاً", "uma traição pequena, uma culpa insistente ou um assunto menor que começou a ferir de verdade")
A("many-rats", "هموم تتراكم، وضع موبوء بمشكلات صغيرة، أو ارتياب اجتماعي", "preocupações acumulando, uma situação infestada de problemas pequenos ou desconfiança social")
A("white-rat", "حليف غير متوقَّع، إنذار في هيئة ألطف، أو ارتياب قد يكون في غير محلّه", "um aliado inesperado, um aviso numa forma mais gentil ou uma desconfiança que pode estar no lugar errado")
A("dead-rat", "نهاية همّ يقرض، أو مشكلة خفية انكشفت وانتهت", "o fim de uma preocupação roedora ou um problema escondido enfim exposto e encerrado")
A("rat-running-away", "مشكلة تتفادى الانكشاف، أو شخص ينسحب بدل مواجهة نزاع", "um problema fugindo da detecção ou alguém se retirando em vez de enfrentar um conflito")
A("alligator", "خطر خفي، غريزة أوّلية، خداع، وتهديدات تكمن تحت سطح هادئ", "perigo escondido, instinto primordial, engano e ameaças à espreita sob uma superfície calma")
A("alligator-attack", "تهديد خفي يضرب فجأة، أو خيانة ممّا بدا نائماً", "uma ameaça escondida atacando de súbito ou uma traição vinda do que parecia dormente")
A("alligator-in-water", "خطر مستتر في وضع عاطفي، أو غريزة تحذّرك من الخوض على عمى", "perigo oculto numa situação emocional ou um instinto avisando para não entrar às cegas")
A("alligator-in-house", "تهديد جدّي داخل حياتك الشخصية، أو ديناميّة خطرة قريبة من البيت", "uma ameaça séria dentro da vida pessoal ou uma dinâmica perigosa perto de casa")
A("running-from-alligator", "تجنّب خوف أوّلي أو تهديد تحسّه صبوراً ومثابراً", "evitar um medo primordial ou uma ameaça que você sente paciente e persistente")
A("baby-alligator", "خطر صغير يكبر إن أُهمل، أو إنذار مبكّر يستحق الجدّية", "um perigo pequeno que cresce se for ignorado ou um aviso cedo que vale levar a sério")
A("dead-alligator", "تهديد نُجي منه، خداع انتهى، أو خوف أوّلي فقد قوّته", "uma ameaça sobrevivida, um engano encerrado ou um medo primordial que perdeu a força")
A("elephant", "ذاكرة، صبر، ولاء، مسؤولية كبيرة، وشأن أكبر من أن يُتجاهل", "memória, paciência, lealdade, uma responsabilidade grande e um assunto grande demais para continuar ignorando")
A("friendly-elephant", "سند ثابت، قوّة صبورة، أو مسؤولية كبيرة تُحمَل برشاقة", "apoio firme, força paciente ou uma responsabilidade grande carregada com graça")
A("elephant-chasing-you", "شأن كبير كنت تتجنّبه وصار يطالب بالانتباه", "um assunto grande que você vinha evitando e agora exige atenção")
A("baby-elephant", "مسؤولية جديدة بوزن طويل الأمد، أو إمكان لطيف سيكبر كثيراً", "uma responsabilidade nova com peso de longo prazo ou um potencial gentil que vai crescer")
A("white-elephant", "بركة نادرة أو عبء متنكّر في هيئة هبة — شيء ثمين لكن مكلف", "uma bênção rara ou um fardo disfarçado de presente — algo valioso e caro de manter")
A("elephant-in-water", "ذاكرة عميقة وعاطفة تُعالَج بصبر، أو شؤون ثقيلة تسير في الشعور", "memória funda e emoção tratadas com paciência ou assuntos pesados se movendo pelo sentimento")
A("dead-elephant", "نهاية حقبة طويلة، حكمة ضاعت، أو حزن على شيء عظيم الوزن", "o fim de uma era longa, sabedoria perdida ou luto por algo de grande peso")
A("being-naked", "انكشاف، هشاشة، خجل، أصالة، وخوف أن تُرى بلا دفاعات", "exposição, vulnerabilidade, vergonha, autenticidade e o medo de ser visto sem defesas")
A("naked-at-school", "قلق أداء، خوف الحكم، أو انعدام أمان اجتماعي قديم يعود", "ansiedade de desempenho, medo de julgamento ou inseguranças sociais antigas voltando")
A("naked-at-work", "هشاشة مهنية، شعور المتطفّل، أو خوف أن تُكشَف عدم جاهزيتك", "vulnerabilidade profissional, sensação de impostor ou medo de ser exposto como despreparado")
A("nobody-noticing-you-naked", "مخاوف انكشاف أكبر في ذهنك منها في الواقع", "medos de exposição maiores na sua mente do que na realidade")
A("trying-to-cover-up", "احتواء ضرر، إخفاء عيب متوهَّم، أو حماية صورة تحت الضغط", "controle de dano, esconder um defeito percebido ou proteger uma imagem sob pressão")
A("partially-naked", "مجال هشاشة بعينه، أو شعور بعدم الجاهزية في جانب واحد من الحياة", "uma área específica de vulnerabilidade ou a sensação de estar despreparado num único aspecto da vida")
A("comfortable-being-naked", "قبول الذات، أصالة، ويسر أن تُرى بالكامل", "aceitação de si, autenticidade e a facilidade de ser visto por inteiro")
A("work", "واجب، هويّة، أداء، أمان، والتوازن بين الجهد وبقية الحياة", "dever, identidade, desempenho, segurança e o equilíbrio entre o esforço e o resto da vida")
A("being-fired", "انعدام أمان حول موقعك، خوف الرفض، أو جاهزية لترك دور لم يعد يناسب", "insegurança sobre a sua posição, medo de rejeição ou prontidão para deixar um papel")
A("being-late-for-work", "خوف التقصير، إثقال، أو قلق من إخلاف توقّعات لا تهدأ", "medo de ficar aquém, sobrecarga ou ansiedade de cumprir expectativas implacáveis")
A("old-job", "دروس لم تُغلق من دور سابق، مقارنة بالحاضر، أو حنين إلى هويّة عمل قديمة", "lições inacabadas de um papel antigo, comparação com o presente ou saudade de uma identidade profissional passada")
A("angry-boss", "ضغط من سلطة، نقد للذات، أو خوف التقييم والرفض", "pressão da autoridade, autocrítica ou medo de avaliação e desaprovação")
A("new-job", "هويّة أو مسؤولية جديدة، طموح، أو ارتياب في دور غير مألوف", "uma identidade ou responsabilidade nova, ambição ou incerteza sobre um papel desconhecido")
A("overwhelmed-at-work", "ضغط عمل حقيقي يظهر في النوم، أو واجب يزاحم بقية الحياة", "estresse real de carga de trabalho subindo no sono ou o dever ocupando o resto da vida")
A("phone", "صلة، تواصل، إلحاح، اعتماد، والقنوات التي تربطك بالآخرين", "conexão, comunicação, urgência, dependência e os canais que te ligam aos outros")
A("losing-your-phone", "خوف الانقطاع، فقدان منفذ إلى الآخرين، أو اعتماد على اتصال دائم", "medo de desconexão, perda de acesso aos outros ou dependência de um contato constante")
A("broken-phone", "تواصل فاشل، قناة علاقة تضرّرت، أو رسائل لا تصل", "comunicação falha, um canal de relação danificado ou recados que não atravessam")
A("phone-not-working", "إلحاح بلا وسيلة، عجز عن بلوغ العون أو قول ما يلزم", "urgência sem meio, não conseguir alcançar ajuda ou dizer o que precisa ser dito")
A("unknown-caller", "جانب غير متعرَّف منك أو رسالة غير متوقّعة تحاول بلوغ الوعي", "uma parte não reconhecida de você ou uma mensagem inesperada tentando alcançar a consciência")
A("missed-calls", "علاقات أُهملت، إشارات فائتة، أو ذنب الغياب", "relações abandonadas, sinais ignorados ou culpa por estar indisponível")
A("phone-ringing", "شيء يطالب بانتباهك الآن، أو فرصة تتطلّب ردّاً", "algo pedindo a sua atenção agora ou uma oportunidade que exige uma resposta")
A("crawling", "تقدّم بطيء، هشاشة، نكوص، تواضع، والمضي حين يبدو الوقوف مستحيلاً", "progresso lento, vulnerabilidade, regressão, humildade e seguir em frente quando ficar de pé parece impossível")
A("crawling-on-the-floor", "تواضع، بداية من الصفر، أو تقدّم يبدو قليل الكرامة لكنّه لازم", "humildade, recomeçar ou um progresso que parece sem dignidade e ainda assim necessário")
A("crawling-like-a-baby", "عودة إلى مرحلة أسبق، اعتماد، أو الرجوع إلى الأسس قبل النهوض", "regressão a uma fase anterior, dependência ou voltar às bases antes de se levantar")
A("crawling-through-a-tunnel", "ممرّ ضيّق عبر صعوبة، أو تقدّم يتطلّب الانخفاض والصبر", "uma passagem estreita pela dificuldade ou um progresso que pede se abaixar e persistir")
A("crawling-through-small-spaces", "تقدّم خانق، الانحشار في قيد، أو المضي فقط بالتصغير من نفسك", "progresso claustrofóbico, passar por um aperto ou avançar só se diminuindo")
A("unable-to-stand-crawling", "قوّة نضبت، مكانة ضاعت، أو موسم الحركة المتاحة فيه هي الزحف فقط", "força esgotada, posição perdida ou uma estação em que o único movimento disponível é rastejar")
A("crawling-away-from-danger", "هروب تحت قيد، بقاء بلا قوّة كاملة، أو الابتعاد عن تهديد", "escapar sob restrição, sobreviver sem força plena ou se afastar de uma ameaça")
A("someone-crawling-toward-you", "حاجة أو خوف أو شخص يقترب من موضع هشّ أو مقلق", "uma necessidade, um medo ou uma pessoa se aproximando de um lugar vulnerável ou inquietante")
A("tunnel", "ممرّ، انتقال، المجهول أمامك، والسير في طور ضيّق نحو نور أو ظلام أعمق", "passagem, transição, o desconhecido à frente e atravessar uma fase estreita rumo à luz ou a um escuro mais fundo")
A("light-at-end-of-tunnel", "أمل بعد مشقّة، مخرج ظاهر من موسم صعب، أو إيمان بأن الممرّ ينتهي", "esperança depois do aperto, uma saída visível de uma estação difícil ou fé de que a passagem termina")
A("dark-tunnel", "ارتياب، خوف المرحلة التالية، أو المضي بلا رؤية واضحة للنهاية", "incerteza, medo da próxima fase ou seguir sem uma visão clara do fim")
A("endless-tunnel", "إرهاق من انتقال يبدو بلا نهاية، أو انتظار فرج يتأخّر", "cansaço de uma transição que parece sem fim ou a espera de um alívio que não chega")
A("blocked-tunnel", "مسار أمامك يبدو مسدوداً، تقدّم توقّف، أو مقاومة دخول المرحلة التالية", "um caminho à frente que parece selado, progresso travado ou resistência a entrar na fase seguinte")
A("train-in-a-tunnel", "أن تُحمَل عبر تغيّر بلا سيطرة كاملة، أو زخم جماعي في مرحلة ضيّقة", "ser carregado por uma mudança sem controle pleno ou um ímpeto coletivo atravessando uma fase estreita")
A("exiting-a-tunnel", "خروج، صفاء بعد حصر، أو أوّل نفس لطور جديد", "emergência, clareza depois do confinamento ou o primeiro fôlego de uma fase nova")
