ARPT = {}


def A(slug, ar, pt):
    ARPT[slug] = (ar, pt)


A("heights", "انكشاف، طموح، دوار على حافّة حياة، وخوف أو نشوة الوقوف فوق أرض مألوفة", "exposição, ambição, vertigem numa beira da vida e o medo ou o arrepio de ficar acima do chão conhecido")
A("standing-at-great-height", "موقع رؤية بعد تقدّم، أو انكشاف يأتي مع دور أو مخاطرة جديدة", "um ponto de vista depois de um avanço ou a exposição que chega com um papel ou risco novo")
A("looking-down-from-heights", "تقدير مدى السقوط الممكن، مقارنة بالآخرين، أو دوار أمام اختيار", "avaliar até onde você poderia cair, comparação com os outros ou vertigem diante de uma escolha")
A("climbing-to-heights", "طموح، جهد نحو مكانة، أو مشقّة الصعود بلا موطئ ثابت", "ambição, esforço rumo a uma posição mais alta ou o cansaço de subir sem um piso firme")
A("high-ledge-no-railing", "نجاح هشّ، سند ناقص، أو وضع يبدو مكشوفاً وغير آمن", "sucesso precário, apoio em falta ou uma situação que se sente exposta e insegura")
A("afraid-on-a-bridge", "قلق انتقال، عبور بين فصلين، أو خوف الفشل في منتصف الطريق", "ansiedade de transição, atravessar entre capítulos ou medo de falhar no meio da passagem")
A("heights-without-falling", "الحافّة نفسها هي الرسالة — رعب الانكشاف لا السقوط", "a beira em si é o recado — pavor da exposição mais do que da queda")
A("nightmare", "أحلام مزعجة، خوف معلّق، تفريغ توتّر ليلي، وصور يعالج بها الذهن التهديد", "sonhos aflitivos, medo sem resolução, alívio noturno de estresse e imagens que a mente usa para processar ameaça")
A("recurring-nightmare", "مصدر توتّر أو خوف معلّق يظلّ يطالب بالانتباه حتى يُواجَه في اليقظة", "um estressor ou medo sem fecho que não para de pedir atenção até ser enfrentado acordado")
A("horrible-dream", "بقايا عاطفية شديدة من النهار، أو محاكاة تهديد بدت أصدق ممّا ينبغي عند الاستيقاظ", "resíduo emocional intenso do dia ou uma simulação de ameaça que pareceu real demais ao acordar")
A("waking-from-nightmare", "الجسد يقطع حملاً زائداً، أو ارتياح بعد أن أنهى الذهن بروفة مرهقة", "o corpo interrompendo um excesso ou o alívio depois de a mente terminar um ensaio estressante")
A("childhood-nightmare", "مخاوف قديمة تعود، قلق نموّ، أو شأن معلّق من مرحلة أسبق", "medos antigos voltando, ansiedade de crescimento ou um assunto inacabado de uma fase anterior")
A("nightmare-about-death", "خوف النهايات أو التغيّر أو الفقد — رمزي في العادة لا نبوئي", "medo de fins, mudança ou perda — em geral simbólico, não profético")
A("sharing-a-nightmare", "طلب عزاء، إضعاف سلطان الحلم، أو حاجة إلى أن يُشهَد الخوف", "buscar consolo, diminuir o poder do sonho ou precisar que o medo seja testemunhado")
A("tsunami", "عاطفة تطغى، رعب استباقي، وقوّة شعور أكبر من أن تُوقَف أو تُفاوَض", "emoção avassaladora, pavor antecipado e uma força de sentimento grande demais para parar ou negociar")
A("tsunami-coming", "أزمة تراها تقترب وتشعر بالعجز عن إيقافها", "uma crise que você vê chegar e se sente sem poder para parar")
A("running-from-tsunami", "هروب من طغيان عاطفي، أو إلحاح للابتعاد عن مطلب يرتفع", "fuga de uma sobrecarga emocional ou urgência de sair de uma exigência que sobe")
A("surviving-a-tsunami", "صمود بعد فيض عاطفي، وإعادة البناء التي تلي الصدمة", "resistência depois de uma enchente emocional e a reconstrução que vem após o choque")
A("tsunami-and-family", "حماية تحت الطغيان، أو أزمة مشتركة داخل علاقات وثيقة", "proteção sob sobrecarga ou uma crise compartilhada em relações próximas")
A("watching-tsunami-from-afar", "مشاهدة اضطراب من بعيد، أو رعب لم يصر شخصيّاً بعد", "testemunhar um abalo à distância ou um pavor que ainda não ficou pessoal")
A("underwater-after-tsunami", "انغماس في عاطفة ما بعد الموجة، أو سكون بعد مرور الموجة", "imersão na emoção do depois ou quietude depois de a onda passar")
A("swimming", "السير في العاطفة بمهارة أو بكدح، ثقة في الشعور، وكيف تبحر في العمق", "atravessar a emoção com habilidade ou esforço, confiança no sentir e o jeito como você navega a profundidade")
A("swimming-easily", "طلاقة عاطفية، ثقة في وضع مثقل بالشعور، أو انسياب في موسم صعب", "fluência emocional, confiança numa situação carregada de sentimento ou fluxo numa estação difícil")
A("struggling-to-swim", "جهد بلا تقدّم في وضع عاطفي، أو إرهاق من البقاء طافياً", "esforço sem progresso numa situação emocional ou cansaço de se manter à tona")
A("swimming-underwater", "استكشاف عميق للشعور، انغماس في اللاوعي، أو حبس النفس في الشدّة", "exploração funda do sentimento, imersão no inconsciente ou prender o fôlego no meio da intensidade")
A("swimming-in-dirty-water", "الإبحار في وضع عاطفي عكر، دوافع مختلطة، أو حدود غير واضحة", "navegar uma situação emocional turva, motivos misturados ou limites pouco claros")
A("swimming-to-shore", "طلب الأمان، الرسو بعد العمق، أو جهد نحو أرض شعورية يابسة", "buscar segurança, aterrar depois da profundidade ou o esforço rumo a uma terra emocional seca")
A("unable-to-swim", "شعور بعدم الجاهزية لعمق عاطفي، أو خوف من وضع يتطلّب معرفة الشعور", "sentir-se despreparado para a profundidade emocional ou medo de uma situação que exige saber sentir")
A("mirror", "صورة الذات، حقيقة، مواجهة الهويّة، وكيف ترى نفسك — أو ترفض أن تراها", "autoimagem, verdade, confronto com a identidade e o jeito como você se vê — ou se recusa a ver")
A("broken-mirror", "صورة ذات محطّمة، حقيقة موجعة، أو هويّة تبدو متشظّية", "autoimagem estilhaçada, uma verdade dolorosa ou uma identidade que se sente fragmentada")
A("not-recognizing-yourself", "تحوّل هويّة، انفصال عمّن صرت، أو دور لم يعد يناسب", "mudança de identidade, distanciamento de quem você se tornou ou um papel que não cabe mais")
A("someone-else-in-mirror", "صفات تسقطها على الآخرين، أو جانب منك لم تدّعه بعد", "qualidades que você projeta nos outros ou uma parte de você que ainda não reivindicou")
A("cracked-mirror", "رؤية مشوَّهة للذات، ثقة تضرّرت، أو حقيقة تُرى قطعاً فقط", "visão distorcida de si, confiança ferida ou uma verdade vista só em pedaços")
A("mirror-in-dark-room", "تأمّل الذات في الارتياب، أو مواجهة الهويّة بلا ضوء واضح", "autorreflexão na incerteza ou confrontar a identidade sem uma luz clara")
A("smashing-a-mirror", "رفض صورة ذات، غضب من كيف تُرى، أو رفض انعكاس موجع", "rejeitar uma autoimagem, raiva do jeito como você é visto ou recusar um reflexo doloroso")
A("train", "اتجاه حياة على سكّة ثابتة، زخم جماعي، توقيت، وهل اخترت المحطّة الأخيرة", "direção de vida num trilho fixo, ímpeto coletivo, hora certa e se você escolheu o destino")
A("missing-a-train", "خوف توقيت ضائع، فرصة رحلت دونك، أو ندم على التردّد", "medo de uma hora perdida, uma chance que partiu sem você ou arrependimento da hesitação")
A("train-crash", "خطّة جماعية تصطدم بالواقع، أو خوف أن مساراً ملتزَماً ينتهي سيئاً", "um plano coletivo colidindo com a realidade ou medo de que um caminho assumido acabe mal")
A("wrong-train", "مسار حياة لم يعد يناسب، أو إدراك أنك تبعت الزخم لا النيّة", "um caminho de vida que não cabe mais ou perceber que você seguiu o ímpeto em vez da intenção")
A("empty-train", "تقدّم وحيد، عزلة في الرحلة، أو مسار تركه الآخرون", "progresso solitário, isolamento numa jornada ou um caminho que os outros abandonaram")
A("train-station", "انتظار الفصل التالي، انتقالات، أو الاختيار بين اتجاهات متاحة", "esperar o próximo capítulo, transições ou escolher entre direções disponíveis")
A("stopping-a-train", "فرض وقف لزخم آلي، أو استعادة الفاعلية من مسار ثابت", "forçar uma parada num ímpeto automático ou retomar a agência de um rumo fixo")
A("plane", "طموح، انتقال بعيد، ثقة بأنظمة خارج سيطرتك، ومنظور مرتفع", "ambição, transição de longa distância, confiança em sistemas fora do seu controle e uma perspectiva elevada")
A("plane-crash", "خوف أن خطّة طموحة تفشل كارثيّاً، أو فقدان الثقة بمسار لا تقوده وحدك", "medo de que um plano ambicioso falhe de forma catastrófica ou perda de confiança num caminho que você não pilota sozinho")
A("flying-in-a-plane", "تقدّم نحو هدف بعيد، انتقال، أو تسليم السيطرة لعملية أكبر", "progresso rumo a um objetivo distante, transição ou entregar o controle a um processo maior")
A("turbulence-on-plane", "عدم استقرار في منتصف الرحلة، أو قلق أثناء انتقال لا تخرج منه مبكّراً", "instabilidade no meio da viagem ou ansiedade numa transição da qual você não sai cedo")
A("missing-a-plane", "فرصة كبيرة ضاعت بالتوقيت أو الاستعداد أو التردّد", "uma oportunidade grande perdida por hora, preparo ou hesitação")
A("piloting-a-plane", "مسؤولية غير معتادة، فاعلية عالية الرهان، أو أن تُطلب قيادة شيء أكبر منك", "responsabilidade incomum, agência de alto risco ou ser pedido para conduzir algo maior do que você")
A("plane-landing", "وصول بعد طموح، رسو بعد ارتفاع، أو نهاية انتقال طويل", "chegada depois da ambição, aterrissagem depois da elevação ou o fim de uma transição longa")
A("grandparents", "أصل، حكمة، إرث، ذاكرة أسرية، والقصّة الأطول التي تقع حياتك داخلها", "ancestralidade, sabedoria, herança, memória familiar e a história mais longa dentro da qual a sua vida se senta")
A("deceased-grandparent", "عزاء، كلام لم يُتم، قيم موروثة، أو حزن يجد وجهاً مألوفاً", "consolo, palavras inacabadas, valores herdados ou um luto achando um rosto conhecido")
A("grandmother-in-dream", "رعاية عبر الأجيال، حكايات الأسرة، أو صورة ألطف من العناية الأمومية", "nutrição através das gerações, histórias da família ou uma forma mais suave de cuidado materno")
A("grandfather-in-dream", "هدى، إرث، معايير، أو رعاية أبوية على خطّ زمني أطول", "orientação, legado, padrões ou um cuidado masculino ao longo de um tempo mais longo")
A("visiting-grandparents", "العودة إلى الجذور، طلب الحكمة، أو حاجة إلى أمان بيت أسبق", "voltar às raízes, buscar sabedoria ou precisar da segurança de uma casa mais antiga")
A("grandparents-house", "أساس أسلاف، ذاكرة طفولة، أو هويّة متجذّرة في تاريخ الأسرة", "alicerce ancestral, memória de infância ou identidade enraizada na história da família")
A("arguing-with-grandparent", "صدام مع قيم موروثة، أو إعادة التفاوض على الولاء لتقليد الأسرة", "embate com valores herdados ou renegociar a lealdade à tradição da família")
A("stairs", "صعود ونزول، جهد بين مستويات الحياة، والخطوات اللازمة لتغيير المكانة أو المنظور", "subida e descida, esforço entre níveis da vida e os degraus necessários para mudar posição ou perspectiva")
A("climbing-stairs", "جهد نحو موضع أعلى، طموح، أو تقدّم يتطلّب خطوة فخطوة", "esforço rumo a uma posição mais alta, ambição ou um progresso que pede um degrau de cada vez")
A("falling-down-stairs", "نكسة مفاجئة بعد تقدّم، فقدان موطئ في المكانة، أو خوف فشل علني في منتصف الصعود", "um revés súbito depois de avançar, pé perdido na posição ou medo de um fracasso público no meio da subida")
A("endless-stairs", "جهد بلا وصول، احتراق من الصعود، أو هدف يظلّ يرتفع", "esforço sem chegada, esgotamento de subir ou um objetivo que não para de subir")
A("broken-stairs", "مسار غير موثوق إلى المستوى التالي، سند ناقص، أو خطّة لا تحمل وزنك", "um caminho instável para o próximo nível, apoio em falta ou um plano que não segura o seu peso")
A("descending-stairs", "العودة إلى الأسس، تواضع، أو تراجع طوعي عن موضع عالٍ", "voltar aos alicerces, humildade ou um recuo voluntário de um lugar alto")
A("spiral-staircase", "تقدّم يدور حول موضوعات مألوفة، أو صعود مع إعادة زيارة الأرض العاطفية نفسها", "progresso que circula temas conhecidos ou subir revisitando o mesmo chão emocional")
A("trapped", "لا مخرج، فاعلية عالقة، ضغط بلا مهرب، ووضع يبدو مغلقاً من كل جهة", "sem saída, agência travada, pressão sem escape e uma situação que parece selada de todos os lados")
A("trapped-in-a-room", "فصل مغلق من الحياة، حبس خاصّ، أو خيارات ضاقت إلى أربعة جدران", "um capítulo fechado da vida, confinamento privado ou opções que estreitaram até quatro paredes")
A("trapped-underwater", "طغيان عاطفي بلا سطح في الأفق، أو شعور بأنك محبوس داخل شعور لا تسمّيه", "sobrecarga emocional sem superfície à vista ou a sensação de estar selado dentro de um sentimento sem nome")
A("trapped-in-a-crowd", "ضغط اجتماعي، فردية ضائعة، أو أن يحملك توقّع الآخرين", "pressão social, individualidade perdida ou ser carregado pelas expectativas dos outros")
A("cant-open-door", "مخرج مسدود، اختيار لا ينقاد، أو عون يبقى قريباً ولا يُبلَغ", "uma saída bloqueada, uma escolha que não cede ou uma ajuda que fica logo fora do alcance")
A("trapped-in-elevator", "تعليق بين مستويات الحياة، تقدّم توقّف، أو عجز علني", "suspenso entre níveis da vida, progresso travado ou um desamparo público")
A("escaping-being-trapped", "ارتياح بعد قيد، استعادة الفاعلية، أو أوّل نفس بعد موسم مغلق", "alívio depois da restrição, retomar a agência ou o primeiro fôlego depois de uma estação selada")
A("being-lost", "تيه، اتجاه ناقص، بحث بلا خريطة، وقلق ألا تعرف المنعطف التالي", "desorientação, rumo em falta, busca sem mapa e a ansiedade de não saber a próxima curva")
A("lost-in-a-city", "طغيان في أنظمة معقّدة، قواعد غير مألوفة، أو طموح بلا مسار واضح", "sobrecarga em sistemas complexos, regras desconhecidas ou ambição sem um roteiro claro")
A("lost-and-cant-find-home", "انزياح هويّة، انتماء ناقص، أو خوف أن حياتك الخاصّة لم تعد تهديك", "deriva de identidade, pertencimento em falta ou medo de que a vida privada já não te oriente")
A("lost-with-no-phone", "انقطاع عن العون، اعتماد على أدوات، أو وحدة حين يُحتاج الهدى", "desconexão da ajuda, dependência de ferramentas ou solidão quando a orientação é necessária")
A("asking-directions-dream", "تواضع، طلب مشورة، أو الاعتراف بأنك لا تبحر وحدك", "humildade, buscar conselho ou admitir que você não navega sozinho")
A("lost-child-in-dream", "جانب هشّ منك ينقصه الرعاية، أو قلق على من يعتمد عليك", "uma parte vulnerável de você sem cuidado ou preocupação com alguém que depende de você")
A("finding-your-way", "عودة الاتجاه، معلم معنى، أو ارتياح حين يتّضح الغرض", "orientação voltando, um marco de sentido ou alívio quando o propósito clareia")
A("twins", "ازدواج، انعكاس، انتباه منقسم، ونماءان يكبران جنباً إلى جنب", "duplicação, espelhamento, atenção dividida e dois desenvolvimentos crescendo lado a lado")
A("having-twins", "مسؤولية مزدوجة، مشروعان معاً، أو وفرة تقسم طاقتك أيضاً", "responsabilidade em dobro, dois projetos ao mesmo tempo ou uma fartura que também divide a sua energia")
A("identical-twins", "انعكاس، ارتباك هويّة، أو مساران يبدوان واحداً وليسا كذلك", "espelhamento, confusão de identidade ou dois caminhos que parecem iguais e não são")
A("twin-babies", "بدايتان هشّتان مزدوجتان، أو رعاية تنقسم بين نماءين محتاجين", "começos frágeis em dobro ou o cuidado dividido entre dois desenvolvimentos necessitados")
A("meeting-your-twin", "لقاء جانب مُهمل منك، أو علاقة تعكسك أكثر ممّا ينبغي", "encontrar um lado abandonado de você ou uma relação que te reflete de perto demais")
A("twins-fighting", "نزاع داخلي بين مطلبين متساويين، أولويات متنافسة، أو ولاءات منقسمة", "conflito interno entre reivindicações iguais, prioridades rivais ou lealdades partidas")
A("losing-one-twin", "حزن على نصف أمل مزدوج، أو خوف أن مساراً يكلّف الآخر", "luto por metade de uma esperança duplicada ou medo de que um caminho custe o outro")
A("lottery", "حظ مفاجئ، أمنيات، صدفة، وخيال حياة تتغيّر بلا الجهد العادي", "fortuna súbita, desejo ilusório, acaso e a fantasia de uma vida mudada sem o esforço comum")
A("winning-the-lottery", "أمل في فرج مفاجئ، رغبة في تجاوز الوسط الشاقّ، أو اعتقاد أن الحظ يعيد كتابة قصّتك", "esperança de um alívio súbito, o desejo de pular o meio difícil ou a crença de que a sorte reescreveria a sua história")
A("losing-lottery-ticket", "فرصة فائتة، إعاقة ذاتية للفرصة، أو خوف أن الحظ انزلق من يديك", "uma chance perdida, autossabotagem de uma oportunidade ou medo de que a fortuna tenha escorregado das mãos")
A("sharing-lottery-win", "أسئلة العدل، كرم تحت الوفرة، أو من تتخيّله إلى جانب ثراء مفاجئ", "perguntas de justiça, generosidade sob fartura ou quem você imagina ao lado de uma riqueza súbita")
A("fake-lottery-win", "خيبة بعد آمال ارتفعت، أو ارتياب أن الحلّ السهل ليس حقيقيّاً", "decepção depois de esperanças altas ou a suspeita de que uma solução fácil não é real")
A("buying-lottery-ticket", "استثمار الأمل في الصدفة، شعيرة صغيرة للإمكان، أو إيكال التغيّر إلى الحظ", "investir esperança no acaso, um rito pequeno de possibilidade ou terceirizar a mudança para a sorte")
A("lottery-numbers", "البحث عن شيفرة تغيّر القدر، أو محاولة الذهن ترتيب العشوائية", "procurar um código para mudar o destino ou a tentativa da mente de ordenar o acaso")
A("debt", "التزام، ثقل ما يُدان به، قلق السداد، وتبادلات خرجت عن التوازن", "obrigação, o peso do que se deve, ansiedade com o pagamento e trocas que saíram do equilíbrio")
A("unable-to-pay-debt", "طغيان الالتزام، خجل، أو فاتورة — حرفية أو عاطفية — تفوق الطاقة", "sobrecarga de obrigação, vergonha ou uma conta — literal ou emocional — que passa da capacidade")
A("someone-owes-you", "اعتراف غير مدفوع، تبادل لم يُتم، أو انتظار أن يعدّل آخر الميزان", "reconhecimento sem pagamento, reciprocidade inacabada ou esperar que outra pessoa acerte as contas")
A("debt-collectors", "ضغط يأتي من الخارج، مساءلة لا تُؤجَّل، أو خوف انكشاف حول المال", "pressão chegando de fora, responsabilidade que não se adia ou medo de exposição em torno do dinheiro")
A("paying-off-debt", "ارتياح، توازن مستعاد، أو العمل الشاقّ لتسوية ما كان مستحقّاً", "alívio, equilíbrio restaurado ou o trabalho duro de acertar o que era devido")
A("hidden-debt", "التزام سرّي، ذنب يُحفَظ خاصّاً، أو كلفة لم تعترف بها بعد", "uma obrigação secreta, culpa guardada no privado ou um custo que você ainda não admitiu")
A("inheriting-debt", "أعباء أسرية تُورَث، التزامات لم تخترها، أو تكاليف إرث", "fardos de família passados adiante, obrigações que você não escolheu ou custos de legado")
A("rabbit", "خصوبة، خجل، غريزة سريعة، وفرة، وهشاشة تتجمّد أو تفرّ", "fertilidade, timidez, instinto rápido, fartura e uma vulnerabilidade que trava ou foge")
A("white-rabbit", "براءة، دليل إلى غير المتوقَّع، أو دعوة لطيفة لاتباع الفضول", "inocência, um guia para o inesperado ou um convite gentil a seguir a curiosidade")
A("rabbit-running-away", "تجنّب، فرصة فائتة، أو جانب خجول منك يفرّ من المواجهة", "evitação, oportunidade perdida ou uma parte tímida de você fugindo do confronto")
A("many-rabbits", "وفرة، موضوعات خصوبة، أو هموم صغيرة تتضاعف أسرع ممّا تدير", "fartura, temas de fertilidade ou preocupações pequenas se multiplicando mais rápido do que você dá conta")
A("dead-rabbit", "براءة ضاعت، هشاشة انتهت، أو حزن على شيء لطيف لم يصمد", "inocência perdida, vulnerabilidade encerrada ou luto por algo gentil que não sobreviveu")
A("holding-a-rabbit", "رعاية غريزة هشّة، رقّة، أو مسؤولية عن شيء يُفزع بسهولة", "cuidado de um instinto frágil, ternura ou responsabilidade por algo que se assusta fácil")
A("rabbit-in-house", "خجل يدخل الحياة الخاصّة، أو حاجة ناعمة تطلب أماناً في البيت", "timidez entrando na vida privada ou uma necessidade macia pedindo segurança em casa")
A("eating", "تغذية، شهية، تلقٍّ، لذّة، ندرة، والتجارب التي تحاول إدخالها", "nutrição, apetite, receber, prazer, escassez e as experiências que você tenta absorver")
A("eating-with-family", "انتماء، رعاية مشتركة، أدوار أسرية، أو توتّر حول ما يُعطى ويُتلقَّى في البيت", "pertencimento, cuidado compartilhado, papéis da família ou tensão em torno do que se dá e se recebe em casa")
A("eating-alone", "استقلال، وحدة، خصوصية، أو حاجة تقضيها بلا سند", "independência, solidão, privacidade ou uma necessidade que você atende sem apoio")
A("eating-at-restaurant", "اختيار، لذّة، عرض اجتماعي، أو الاعتماد على آخرين ليوفّروا ما تحتاج", "escolha, prazer, apresentação social ou depender dos outros para fornecer o que você precisa")
A("eating-delicious-food", "رضا، مكافأة، امتنان، لذّة حسّية، أو جاهزية للاستمتاع بما تقدّمه الحياة", "satisfação, recompensa, gratidão, prazer dos sentidos ou prontidão para gozar o que a vida oferece")
A("eating-spoiled-food", "قبول شيء ضارّ، خيبة، ارتياب، أو إدراك أن عرضاً لم يعد صالحاً لك", "aceitar algo nocivo, decepção, desconfiança ou reconhecer que uma oferta já não te faz bem")
A("unable-to-eat", "تلقٍّ مسدود، قلق، رفض، حزن، أو صعوبة قبول الرعاية والفرصة", "receber bloqueado, ansiedade, recusa, luto ou dificuldade de aceitar cuidado e oportunidade")
A("overeating", "إفراط، جوع عاطفي لم يُقضَ، فقدان حدود، أو ملء حاجة لا يشبعها الطعام", "excesso, fome emocional sem resposta, perda de limites ou tentar encher uma necessidade que comida não resolve")
A("sharing-food", "كرم، تبادل، حميمية، والتوزيع العادل للانتباه أو الموارد", "generosidade, reciprocidade, intimidade e a distribuição justa de atenção ou recursos")
A("cake", "احتفال، مكافأة، حلاوة قد تشعر أو لا تشعر أنك تستحقّها، أو شعيرة تمييزك", "celebração, recompensa, uma doçura que você talvez sinta ou não que merece ou um rito de ser marcado como especial")
A("cooking-food", "إعداد غذاء، تحويل مادّة نيئة، أو جهد جعل شيء جاهزاً للتلقّي", "preparar nutrição, transformar matéria crua ou o trabalho de deixar algo pronto para ser recebido")
A("boat", "الإبحار في العاطفة بوعاء، عبور ماء غير محسوم، ومدى صلاحية مركب حياتك الآن", "navegar a emoção com uma embarcação, atravessar água incerta e o quanto a sua embarcação de vida parece à prova d'água")
A("sinking-boat", "خطّة أو علاقة تأخذ ماء، أو خوف أن مركبك لا يحمل الثقل العاطفي", "um plano ou relação fazendo água ou medo de que a sua embarcação não aguente a carga emocional")
A("rowing-a-boat", "جهد شخصي عبر العاطفة، تقدّم بطيء بقوّتك أنت", "esforço pessoal através da emoção, progresso lento pela própria força")
A("boat-in-storm", "الإبحار في اضطراب، الثبات على المسار تحت الضغط، أو قيادة حين تعادي المياه", "navegar a turbulência, manter o rumo sob pressão ou liderar quando as águas viram hostis")
A("empty-boat", "وعاء بلا غرض، خطط متروكة، أو وحدة على الماء", "uma embarcação sem propósito, planos abandonados ou solidão na água")
A("luxury-yacht", "مكانة على بحار عاطفية، راحة تعزلك عن العمق، أو تطلّع متنكّر في هيئة سفر", "posição nos mares emocionais, conforto te isolando da profundidade ou aspiração vestida de viagem")
A("docking-a-boat", "وصول بعد عبور، تأمين ما حملت، أو إنهاء رحلة عبر الشعور", "chegada depois da travessia, firmar o que você carregou ou encerrar uma jornada através do sentimento")
A("celebrity", "اعتراف، إسقاط، هويّة عامّة، وصفات تعجب بها أو تريد ادّعاءها", "reconhecimento, projeção, identidade pública e qualidades que você admira ou quer reivindicar")
A("meeting-a-celebrity", "لقاء صفة عامّة تريدها — اعتراف أو يسر أو موهبة — أو بروفة لأن تُرى", "contato com uma qualidade pública que você quer — reconhecimento, leveza, talento — ou um ensaio de ser visto")
A("becoming-famous", "رغبة في أن تُرى، ضغط الظهور، أو هويّة تتّسع أسرع ممّا تحتمل الخصوصية", "o desejo de ser visto, a pressão da visibilidade ou uma identidade crescendo mais rápido do que a privacidade aguenta")
A("celebrity-ignoring-you", "اعتراف لم يُقضَ، باب مكانة مغلق، أو ألم أن يتجاهلك من استثمرت فيه معنى", "reconhecimento sem resposta, uma porta de posição fechada ou a dor de ser invisível para quem você investiu de sentido")
A("dating-a-celebrity", "حميمية مع صورة عامّة، رغبة في الحياة التي يمثّلها، أو علاقة هي أيضاً أداء", "intimidade com uma imagem pública, querer a vida que a pessoa representa ou uma relação que também é um palco")
A("celebrity-ex", "نسخة سابقة منك كانت أكثر ظهوراً، أو حنين إلى بريق لم يكن لك تماماً", "uma versão antiga de você que era mais visível ou saudade de um brilho que nunca foi bem seu")
A("old-friend", "تاريخ معلّق، ذات سابقة، حنين، والشخص الذي ما زال يمسك فصلاً لم تغلقه", "história inacabada, um eu antigo, saudade e a pessoa que ainda guarda um capítulo sem fecho")
A("old-friend-from-school", "هويّة أسبق، مقارنة معلّقة، أو درس من ذلك العهد ما زال يطلب الانتباه", "uma identidade mais antiga, comparação inacabada ou uma lição daquela época ainda pedindo atenção")
A("talking-to-old-friend", "اللحاق بذات سابقة، كلام لم يُقَل، أو عزاء من رابطة قطعها الزمن", "alcançar um eu antigo, palavras sem voz ou o consolo de um laço que o tempo interrompeu")
A("dead-old-friend", "حزن، ذاكرة، أو صفة كان يحملها ذلك الشخص وما زلت تحتاجها", "luto, memória ou uma qualidade que aquela pessoa carregava e de que você ainda precisa")
A("arguing-with-old-friend", "تنافس قديم يعود، ضغينة لم تُصفَّ، أو توتّر بين من كنت ومن صرت", "rivalidade antiga voltando, uma mágoa que nunca se limpou ou tensão entre quem você era e quem é")
A("old-friend-changed", "مسافة، صدمة الزمن، أو إدراك أن علاقة لم تعد تناسب الحاضر", "distância, o choque do tempo ou perceber que uma relação já não cabe no presente")
A("test", "تقييم، استعداد، قلق أداء، وخوف أن تُقاس وتُوجَد غير مكتمل", "avaliação, preparo, ansiedade de desempenho e o medo de ser medido e achado inacabado")
A("unprepared-for-test", "تقييم حقيقي تشعر أنك متأخّر عنه، أو خوف أعمق أن تُسأل عمّا لم تدرسه", "uma avaliação real em que você se sente atrasado ou o medo mais fundo de ser cobrado por algo que não estudou")
A("failing-a-test", "خجل بعد حكم، معيار لم تبلغه، أو بروفة عاقبة ترهبها أصلاً", "vergonha depois de um julgamento, um padrão que você não atingiu ou o ensaio de uma consequência que você já teme")
A("late-to-a-test", "الوقت ينفد، جاهزية فائتة، أو الوصول بعد أن بدأ وقت الإثبات", "o tempo acabando, prontidão perdida ou chegar depois de o momento da prova ter começado")
A("cannot-find-exam-room", "ألا تعرف أين الاختبار حقّاً — قواعد غير واضحة، معيار خفي، أو امتحان حياة بلا خريطة", "não saber onde a prova de fato está — regras pouco claras, um padrão escondido ou um exame de vida sem mapa")
A("blank-test-paper", "ذهن يفرغ تحت الضغط، أو سؤال عن حياتك لا تجيب عنه بعد", "a mente esvaziando sob pressão ou uma pergunta sobre a própria vida que você ainda não sabe responder")
A("ring", "التزام، انتماء، رابطة تُرى، ودائرة وعد تصنعه أو تكسره", "compromisso, pertencimento, um laço tornado visível e o círculo de uma promessa que você faz ou quebra")
A("wedding-ring", "زواج، عهد مُلزِم، أو الشكل العلني لالتزام خاصّ", "casamento, um voto que amarra ou a forma pública de um compromisso privado")
A("losing-a-ring", "خوف فقدان رابطة، التزام ارتخى، أو وعد لم يعد يستقرّ", "medo de perder um laço, um compromisso afrouxado ou uma promessa que já não assenta bem")
A("broken-ring", "عهد تضرّر، دائرة لا تُغلق، أو علاقة تشقّق شكلها", "um voto danificado, um círculo que não fecha ou uma relação cuja forma rachou")
A("engagement-ring", "التزام عتبة، أمل ممتزج بضغط، أو سؤال إن كنت ستقول نعم", "um compromisso de limiar, esperança misturada com pressão ou a pergunta de se você vai dizer sim")
A("finding-a-ring", "رابطة غير متوقّعة، فرصة انتماء، أو وعد يصل قبل أن تطلبه", "um laço inesperado, uma chance de pertencimento ou uma promessa chegando antes de você pedir")
A("flowers", "جمال، مودة، ازدهار، حزن لُطِّف، وشعور يُقدَّم أو يُتلقَّى في هيئة مرئية", "beleza, afeto, florescimento, luto tornado gentil e um sentimento oferecido ou recebido em forma visível")
A("receiving-flowers", "مودة تصل، اعتذار، مغازلة، أو اعتراف لم تحتاج أن تطلبه", "afeto chegando, desculpa, cortejo ou um reconhecimento que você não precisou pedir")
A("wilted-flowers", "جمال فات أوانه، مودة أُهملت، أو شعور لم يُسقَ", "beleza fora de estação, afeto abandonado ou um sentimento que não foi regado")
A("roses", "رومانسية، شغف، أو حبّ له أيضاً أشواك — جمال بثمن", "romance, paixão ou um amor que também tem espinhos — beleza com um custo")
A("picking-flowers", "اختيار ما تجمع، أخذ الجمال بين يديك، أو إنهاء شيء كي تبقيه", "escolher o que colher, tomar a beleza nas mãos ou encerrar algo para poder guardá-lo")
A("dead-flowers", "هدية انتهت، حزن، أو حبّ أكمل موسمه", "uma oferenda encerrada, luto ou um amor que completou a sua estação")
A("keys", "منفذ، إذن، الخطوة التالية، والشيء الصغير الذي يقرر إن كان باب أو خطّة سيفتح", "acesso, permissão, o próximo passo e o objeto pequeno que decide se uma porta ou um plano abre")
A("lost-keys", "منفذ تأخّر: خطّة تراها ولا تبدأها، أو إذن ضاع", "acesso adiado: um plano que você vê e não consegue começar ou uma permissão que sumiu")
A("finding-keys", "طريق احتياطي إلى الفاعلية، مورد نسيت أنك تملكه، أو باب يمكنه أن يفتح أخيراً", "um caminho reserva para a agência, um recurso que você esqueceu que tinha ou uma porta que enfim pode abrir")
A("house-keys", "منفذ إلى الحياة الخاصّة، انتماء، أو من يُسمَح له بدخول غرفك الداخلية", "acesso à vida privada, pertencimento ou quem tem permissão de entrar nos seus cômodos interiores")
A("broken-key", "بداية انكسرت، أداة خطأ للقفل، أو إذن فشل تحت الضغط", "um começo que quebrou, a ferramenta errada para a fechadura ou uma permissão que falhou sob pressão")
A("bunch-of-keys", "خيارات كثيرة، أدوار أكثر من اللازم، أو مسؤولية عن أبواب عدّة معاً", "muitas opções, papéis demais ou responsabilidade por várias portas ao mesmo tempo")
A("shoes", "الطريق الذي تمشي، هويّة عامّة، جاهزية لرحلة، وكيف تعرض نفسك على الأرض", "o caminho que você anda, identidade pública, prontidão para uma jornada e o jeito como você se apresenta no chão")
A("lost-shoes", "عدم جاهزية لمشي الطريق التالي، هويّة عامّة ناقصة، أو رحلة لا تبدأ حافياً", "despreparo para o próximo caminho, identidade pública em falta ou uma jornada que você não começa descalço")
A("new-shoes", "مسار جديد، عرض ترقّى، أو دور ما زلت تليّنه", "um caminho novo, apresentação atualizada ou um papel que você ainda está amaciando")
A("barefoot", "انكشاف، تواضع، تماس مباشر مع الأرض، أو طريق تمشيه بلا حماية", "exposição, humildade, contato direto com o chão ou um caminho que você anda sem proteção")
A("worn-shoes", "طريق كلّفك، هويّة استُنزفت، أو الاستمرار في عدّة لم تعد تمسك", "um caminho que te custou, identidade esgotada ou continuar num equipamento que já não segura")
A("high-heels", "عرض مرتفع، مكانة، صعوبة المشي، أو دور يبدو قويّاً ويصعب الثبات فيه", "apresentação elevada, posição, dificuldade de andar ou um papel que parece poderoso e é difícil de sustentar")
A("dragon", "قوّة هائلة، حارس أو ملتهم، تحوّل بالنار، وقوّة أكبر من أن تُعامَل كخوف عادي", "poder imenso, um guardião ou um devorador, transformação pelo fogo e uma força grande demais para tratar como medo comum")
A("flying-dragon", "قوّة ذات مدى، طاقة تقدر أن تفارق الأرض، أو طموح أُعطي جسداً أسطوريّاً", "poder com alcance, uma força que pode deixar o chão ou ambição ganhando um corpo mítico")
A("dragon-attack", "قوّة تطغى تتّجه إليك — غضب أو سلطة أو مشكلة كبرت حتى صارت أسطورة", "poder avassalador vindo na sua direção — raiva, autoridade ou um problema que cresceu até ficar lendário")
A("dragon-fire", "قوّة مدمّرة أو مطهِّرة، غضب يحرق، أو تحوّل لا يكون لطيفاً", "força destrutiva ou purificadora, raiva que queima ou uma transformação que não consegue ser gentil")
A("friendly-dragon", "قوّة إلى جانبك، حارس، أو طاقة يُسمَح لك أخيراً بمصادقتها", "poder do seu lado, um guardião ou uma força que você enfim tem permissão de ter como amiga")
A("chinese-dragon", "حظ، قوّة إمبراطورية، حكمة في حركة، أو صورة ثقافية لقوّة تخلق ولا تدمّر فقط", "sorte, poder imperial, sabedoria em movimento ou uma imagem cultural de força que cria em vez de só destruir")
A("moon", "دورات، حدس، ذهن الليل، ارتباط أنثوي، ونور لا يأتي من شمس اليقظة", "ciclos, intuição, a mente da noite, associação feminina e uma luz que não vem do sol acordado")
A("full-moon", "اكتمال، ظهور ما كان خفيّاً، أو دورة في أسطع شحناتها", "culminação, visibilidade do que estava escondido ou um ciclo no seu ponto mais brilhante e carregado")
A("crescent-moon", "بداية في الظلام، إمكان يزيد أو ينقص، أو نور نحيل يكفي للاهتداء", "um começo no escuro, potencial crescendo ou minguando ou uma luz fina que já basta para se orientar")
A("red-moon", "شعور نذير، أزمة في دورة، شغف أو إنذار يلوّن الليل", "sensação de presságio, crise num ciclo, paixão ou aviso tingindo a noite")
A("moonlight", "إضاءة ناعمة، رؤية بالحدس لا بضوء النهار، أو طريق لا يُرى إلا ليلاً", "iluminação suave, ver pela intuição mais do que à luz do dia ou um caminho visível só à noite")
A("moon-over-water", "لقاء الشعور والحدس: عاطفة تعكس دورة تراها ولا تأمرها", "sentimento e intuição se encontrando: a emoção refletindo um ciclo que você vê e não comanda")
A("colors", "مزاج صار مرئيّاً، شعور يصل كلون، والطقس العاطفي لمشهد قبل أن يشرحه الحكي", "humor tornado visível, um sentimento que chega como cor e o clima emocional de uma cena antes do enredo explicar")
A("seeing-red", "غضب، إلحاح، حيوية، أو إنذار يعرفه الجسد أصلاً", "raiva, urgência, vitalidade ou um aviso que o corpo já conhece")
A("wearing-black", "حزن، حماية، رسمية، قوّة خفية، أو مزاج ترتديه", "luto, proteção, formalidade, força escondida ou um humor que você veste")
A("wearing-white", "صفاء، جدّة، انكشاف، أو رغبة في أن تُقرأ نظيفاً وغير مكتمل", "clareza, novidade, exposição ou o desejo de ser lido como limpo e inacabado")
A("blue-in-a-dream", "هدوء، حزن، مسافة، أو مناخ عاطفي بارد", "calma, tristeza, distância ou um clima emocional frio")
A("yellow-in-a-dream", "انتباه، فرح، حذر، أو شعور ساطع قد يشير أيضاً إلى قلق", "atenção, alegria, cautela ou um sentimento brilhante que também pode sinalizar ansiedade")
A("insects", "قوى صغيرة مثابرة، إزعاج، همّ يتزاحم، وغريزة بحجم تقدر أن تطرده ولا تتجاهله", "forças pequenas e persistentes, irritação, preocupação em enxame e um instinto numa escala que você espanta e não ignora")
A("bees", "سرب منتج، عمل حلو، جماعة، أو لسعة تتبع جهداً نافعاً", "enxame produtivo, trabalho doce, comunidade ou uma ferroada que segue um labor útil")
A("cockroach", "ما يبقى في الظلام، خجل، إصرار مشكلة تظلّ تحاول قتلها", "o que sobrevive no escuro, vergonha, a persistência de um problema que você insiste em matar")
A("ants", "عمل صغير منسَّق، غزو للفضاء الخاصّ، أو مهامّ دقيقة تصير ثقلاً", "trabalho pequeno e coordenado, invasão do espaço privado ou muitas tarefas mínimas virando um peso")
A("flies", "إزعاج، عفن قريب، أو شيء غير نظيف لا يغادر الغرفة", "irritação, decomposição por perto ou algo impuro que não sai do cômodo")
A("insect-swarm", "طغيان ضغوط صغيرة كثيرة، قلق بلا وجه واحد، أو مشكلة تتفرّق ولا تُمسَك", "sobrecarga de muitas pressões pequenas, ansiedade sem um rosto só ou um problema que se espalha e não se pega")
A("intruder", "حدّ تُجُوِز، فضاء خاصّ اقتُحم، وخوف أن شيئاً غير مرغوب قد دخل", "um limite atravessado, espaço privado invadido e o medo de que algo indesejado já tenha entrado")
A("intruder-in-house", "حياة خاصّة دُخلت بلا إذن — شخص أو شعور أو مطلب لا ينتمي", "vida privada entrada sem consentimento — uma pessoa, um sentimento ou uma exigência que não pertence")
A("hiding-from-intruder", "حماية الذات، أمل ألا تُكتشَف، أو تهديد لن تواجهه بعد", "autoproteção, a esperança de não ser achado ou uma ameaça que você ainda não confronta")
A("fighting-an-intruder", "الدفاع عن حدّ، رفض الغزو، أو نزاع وصل إلى الباب", "defender um limite, recusar a invasão ou um conflito que chegou à porta")
A("intruder-at-window", "تهديد ما زال خارجاً لكنّه يراقب — إنذار أو إغراء أو مشكلة تنظر إلى الداخل", "uma ameaça ainda do lado de fora e já olhando — aviso, tentação ou um problema espiando para dentro")
A("unknown-intruder", "قلق بلا وجه: تغيّر أو مرض أو نفوذ لا تسمّيه وقد دخل", "ansiedade sem rosto: uma mudança, uma doença ou uma influência que você não nomeia e já sentiu entrar")
A("being-ignored", "اختفاء، صوت لا يقع، انتباه يُحبَس، وجرح أن تهمّ أقلّ ممّا تحتاج", "invisibilidade, uma voz que não pousa, atenção retida e a ferida de importar menos do que você precisa")
A("ignored-by-friend", "رابطة تبرد، إقصاء اجتماعي، أو صداقة لم تعد تردّ نداءك", "um laço esfriando, exclusão social ou uma amizade que já não devolve o seu chamado")
A("ignored-by-family", "صمت أسري قديم، دور لم تُسمَع فيه، أو حاجة ما زالت تنتظر", "um silêncio antigo da família, um papel em que você não foi ouvido ou uma necessidade que ainda espera")
A("ignored-in-a-crowd", "مجهولية تؤلم، ذات عامّة لا تُسجَّل، أو الصراخ في غرفة لا تردّ", "anonimato que dói, um eu público que não registra ou gritar numa sala que não responde")
A("partner-ignoring-you", "انسحاب عاطفي، حديث لا يبدأ، أو حميمية صارت باردة", "retirada emocional, uma conversa que não começa ou uma intimidade que esfriou")
A("calling-and-being-ignored", "نداء بلا ردّ — رسالة أو حاجة أو جانب منك يظلّ يطرق", "um chamado sem resposta — um recado, uma necessidade ou uma parte de você que não para de bater")
