ARPT = {}


def A(slug, ar, pt):
    ARPT[slug] = (ar, pt)


A("crocodile", "صبر قديم، تهديد ينتظر، دموع زائفة، وغريزة أقدم من حديث السطح", "paciência ancestral, uma ameaça que espera, lágrimas falsas e um instinto mais velho que a conversa da superfície")
A("crocodile-attack", "تهديد صبور تحرّك أخيراً، أو خيانة ممّا بدا ساكناً", "uma ameaça paciente que enfim se moveu ou uma traição vinda do que parecia parado")
A("crocodile-in-water", "خطر داخل العاطفة، سطح هادئ وأسنان تحته، أو غريزة تحذّرك من الخوض على عمى", "perigo dentro da emoção, uma superfície calma com dentes por baixo ou um instinto avisando para não entrar às cegas")
A("crocodile-tears", "حزن ممثَّل، اعتذار غير صادق، أو أن تضبط نفسك أو غيرك تتألّم بلا تغيّر حقيقي", "luto encenado, desculpa sem verdade ou pegar a si ou a outra pessoa fingindo ferida sem se transformar")
A("baby-crocodile", "خطر صغير يكبر إن أُهمل، أو إنذار مبكّر يسهل الاستخفاف به", "um perigo pequeno que cresce se for ignorado ou um aviso cedo fácil demais de subestimar")
A("dead-crocodile", "خوف قديم نُجي منه، خداع انتهى، أو تهديد فقد صبره وقوّته", "um medo ancestral sobrevivido, um engano encerrado ou uma ameaça que perdeu a paciência e o poder")
A("dolphin", "لعب ذكي، هدى عبر العاطفة، ثقة في الماء، ومعين يلقاك في العمق", "brincadeira inteligente, orientação através da emoção, confiança na água e um ajudante que te encontra na profundidade")
A("swimming-with-dolphins", "يسر في العاطفة، هدى موثوق في العمق، أو لعب يعود إلى موسم مثقل بالشعور", "facilidade na emoção, orientação confiável na profundidade ou a brincadeira voltando a uma estação carregada de sentimento")
A("dolphin-jumping", "فرح يخترق السطح، رسالة تقفز إلى النظر، أو ذكاء يأبى البقاء خفيّاً", "alegria rompendo a superfície, um recado saltando à vista ou uma inteligência que não aceita ficar escondida")
A("injured-dolphin", "حدس مجروح، دليل يحتاج رعاية، أو مرح جُرح", "intuição ferida, um guia que precisa de cuidado ou uma brincadeira que foi machucada")
A("many-dolphins", "انتماء في جماعة تُجيد الشعور، أو سند يأتي من أكثر من جهة", "pertencimento num grupo fluente em sentimento ou apoio chegando de mais de uma direção")
A("dead-dolphin", "هدى ضائع في العاطفة، حزن على جانب مرح منك، أو معين لم يستطع البقاء", "orientação perdida na emoção, luto por uma parte brincalhona de você ou um ajudante que não pôde ficar")
A("frog", "تحوّل، قفزة، ماء غير نظيف أو خصيب، وتغيّر يبدو غير جاهز حتى يصير مفاجئاً", "transformação, um salto, água impura ou fértil e uma mudança que parece crua até ser súbita")
A("frog-turning-into-something", "تغيّر هيئة، شيء محتقَر يكشف قيمته، أو قفزة لم تصدّق أنها ممكنة", "mudança de forma, uma coisa desprezada revelando valor ou um salto que você não acreditava possível")
A("many-frogs", "تغيّرات صغيرة تتضاعف، موسم انتقال صاخب، أو موضوعات خصوبة تصل دفعة واحدة", "mudanças pequenas se multiplicando, uma estação barulhenta de transição ou temas de fertilidade chegando todos de uma vez")
A("catching-a-frog", "محاولة تثبيت تغيّر، أو الإمساك بتحوّل يحتاج أن يقفز", "tentar segurar uma mudança quieta ou agarrar uma transformação que precisa pular")
A("frog-in-the-house", "تغيّر يدخل الحياة الخاصّة، أو مسار غير مألوف يجلس في غرفة كانت مرتّبة", "mudança entrando na vida privada ou um processo desconhecido sentado num cômodo que costumava ser arrumado")
A("dead-frog", "تحوّل توقّف، قفزة لم تُؤخَذ، أو حزن على تغيّر جفّ", "uma transformação que travou, um salto não dado ou luto por uma mudança que secou")
A("fox", "دهاء، كتمان، معين أو خصم ماكر، والجانب منك الذي يعيش بقراءة المكان", "astúcia, discrição, um ajudante ou rival ladino e a parte de você que sobrevive lendo o ambiente")
A("red-fox", "دهاء ظاهر، شغف باستراتيجية، أو ذكاء لافت يأبى أن يُملَك", "astúcia visível, paixão com estratégia ou uma inteligência marcante que não se deixa possuir")
A("fox-in-the-house", "مكر داخل الحياة الخاصّة، مشكلة ذكية في البيت، أو جانب منك يأبى التدجين", "astúcia dentro da vida privada, um problema esperto em casa ou uma parte de você que não se domestica")
A("being-chased-by-a-fox", "أن تُغلب بالحيلة، مطاردة أذكى من القوّة، أو مكرك يرتدّ عليك", "ser superado na manha, caçado por algo mais esperto que a força ou a sua própria astúcia virando contra você")
A("friendly-fox", "دهاء إلى جانبك، دليل لا يجامل، أو إذن بأن تكون حادّ الفطنة", "astúcia do seu lado, um guia sem sentimentalismo ou permissão para ser sagaz")
A("dead-fox", "مكر ضائع، استراتيجية فشلت، أو حزن على تكيّف ذكي لم يعد يعمل", "astúcia perdida, uma estratégia que falhou ou luto por uma adaptação esperta que já não serve")
A("goat", "تسلّق عنيد، شهية، كبش فداء، وإرادة ثابتة القدم لا تستأذن لتواصل", "subida teimosa, apetite, bode expiatório e uma vontade pé-firme que não pede licença para seguir")
A("climbing-goat", "تقدّم غير مرجَّح، موطئ في طريق شديد الانحدار، أو إصرار حيث يرجع الآخرون", "progresso improvável, piso num caminho íngreme ou persistência onde os outros voltariam")
A("goat-attack", "نزاع عنيد، تصادم إرادات رأساً لرأس، أو نطحة مطلب استخففت به", "conflito teimoso, colisão de vontades de frente ou uma chifrada de uma exigência que você desprezou")
A("white-goat", "عناد أنظف، تسلّق بنيّة أوضح، أو كبش فداء ترفض أن تصير", "uma teimosia mais limpa, uma subida com motivo mais claro ou um bode expiatório que você recusa ser")
A("herd-of-goats", "شهية جماعة، إرادات صغيرة كثيرة، أو جماعة تعيش على أرض خشنة", "apetite de grupo, muitas vontades pequenas ou uma comunidade que sobrevive em chão áspero")
A("dead-goat", "عناد انتهى، تسلّق تُرك، أو ثمن أن تُجعَل كبش فداء", "teimosia encerrada, uma subida abandonada ou o custo de ter sido feito bode expiatório")
A("giraffe", "رؤية أطول، مدّ العنق، طول محرج، وأن ترى أبعد من الزحام عند قدميك", "uma vista mais longa, esticar o pescoço, altura desajeitada e ver mais longe que a multidão aos seus pés")
A("tall-giraffe", "منظور يعزلك، رؤية لا يشاركك الآخرون، أو الوقوف فوق وضع بثمن", "perspectiva que isola, uma vista que os outros não compartilham ou ficar acima de uma situação com um custo")
A("giraffe-eating", "غذاء يتطلّب مدّ اليد، صبر، أو الارتفاع فوق الطعام الظاهر", "nutrição que pede alcance, paciência ou ir mais alto que a comida óbvia")
A("baby-giraffe", "رؤية طويلة جديدة ما زالت غير ثابتة، أو هبة منظور لم تتعلّم طولها بعد", "uma vista longa nova ainda instável ou um dom de perspectiva que ainda não aprendeu a própria altura")
A("running-giraffe", "سرعة محرجة، فرار برؤية طويلة، أو إلحاح يبدو أخرق وما زال يقطع المسافة", "velocidade desajeitada, fuga com uma vista longa ou urgência que parece feia e ainda assim cobre chão")
A("dead-giraffe", "منظور ضائع، عنق لم يعد يُمَدّ، أو حزن على رؤية سقطت", "perspectiva perdida, um pescoço que já não se estica ou luto por uma vista que caiu")
A("camel", "صمود عبر الندرة، ذخيرة مخزونة، عبور طويل، والحمل الذي وافقت أن تحمله في بلد جاف", "resistência na escassez, reservas guardadas, uma travessia longa e a carga que você aceitou carregar em terra seca")
A("riding-a-camel", "صمود بإيقاع، ثقة بمركبة بطيئة في موسم شاقّ، أو ترك القوّة المخزونة تحملك", "resistência no ritmo, confiar numa condução lenta numa estação dura ou deixar a força guardada te carregar")
A("thirsty-camel", "ذخيرة تنفد، عبور أطول ممّا خُطِّط، أو حاجة كنت تقنّنها", "reservas acabando, uma travessia mais longa que o planejado ou uma necessidade que você vinha racionando")
A("camel-caravan", "صمود مشترك، عبور جماعة، أو عمل لا يستقيم إلا كقطار طويل من الجهد", "resistência compartilhada, uma travessia em grupo ou um trabalho que só faz sentido como um trem longo de esforço")
A("loaded-camel", "مسؤولية مخزونة على ظهرك، صبر تحت الثقل، أو سؤال كم تستطيع أن تزيد", "responsabilidade guardada nas costas, paciência sob o peso ou a pergunta de quanto mais você aguenta")
A("dead-camel", "صمود فشل، عبور انتهى، أو حزن على الجانب منك الذي كان يصبر على الجفاف", "resistência que falhou, uma travessia encerrada ou luto pela parte de você que sobrevivia à seca")
A("bat", "رؤية ليلية، ما لا يُرى، انقلاب، ومخلوق يقرأ الظلام كما يقرأ غيره النهار", "visão noturna, o invisível, inversão e uma criatura que lê o escuro do jeito que os outros leem a luz do dia")
A("bats-in-the-house", "مادّة ليلية داخل الحياة الخاصّة، غرفة مظلمة من الذات تصير مسموعة، أو خوف ما يطير وأنت نائم", "material da noite dentro da vida privada, um cômodo escuro do eu ficando audível ou medo do que voa enquanto você dorme")
A("bat-flying-at-you", "ما لا يُرى يقترب، فزعة من الظلام، أو حدس يصل أسرع من أن يُرحَّب به", "o invisível chegando perto, um susto do escuro ou uma intuição chegando rápido demais para ser bem-vinda")
A("many-bats", "طغيان أفكار الليل، مخاوف صغيرة كثيرة تأخذ جناحاً، أو غسق يأبى البقاء خارجاً", "sobrecarga de pensamentos noturnos, muitos medos pequenos ganhando asa ou um crepúsculo que não fica do lado de fora")
A("white-bat", "هدى ليلي نادر، شعور نذير، أو قدرة مظلمة تظهر في هيئة لم تتوقّعها", "orientação noturna rara, uma sensação de presságio ou uma capacidade escura aparecendo numa forma que você não esperava")
A("dead-bat", "خوف ليلي انتهى، رؤية مظلمة ضاعت، أو جانب منك كان يبحر بلا ضوء", "medo noturno encerrado, visão escura perdida ou uma parte de você que navegava sem luz")
A("deer", "لطف، تيقّظ، جمال خجول، والجانب منك الذي يتجمّد أو يفرّ عند أوّل صوت خطأ", "gentileza, alerta, uma beleza tímida e a parte de você que trava ou foge no primeiro som errado")
A("white-deer", "لطف نادر، دليل عبر الغابة، أو لقاء مقدّس الشعور مع خجلك", "uma gentileza rara, um guia pela mata ou um encontro de tom sagrado com a sua própria timidez")
A("deer-running-away", "فرار قبل اللقاء، فرصة لطيفة فائتة، أو جانب خجول يغادر الفسحة", "fuga antes do contato, uma oportunidade gentil perdida ou uma parte tímida saindo da clareira")
A("injured-deer", "براءة مجروحة، هشاشة لا تقدر أن تركض، أو رقّة جُرحت", "inocência ferida, vulnerabilidade que não consegue correr ou uma ternura que foi machucada")
A("stag-with-antlers", "قوّة لطيفة صارت مرئية، كرامة، أو قوّة موسمية تنمو وتُطرح", "força gentil tornada visível, dignidade ou um poder sazonal que você cresce e deixa cair")
A("dead-deer", "لطف ضائع، براءة انتهت، أو حزن على جانب خجول من الحياة لم يصمد أمام الضجيج", "gentileza perdida, inocência encerrada ou luto por uma parte tímida da vida que não sobreviveu ao barulho")
A("dinosaur", "قوّة عتيقة ما زالت تمشي، رهبة طفولة، نفوذ منقرض، وشيء ضخم لا ينتمي إلى زمن الحاضر", "uma força ultrapassada ainda andando, assombro de infância, poder extinto e algo enorme que não cabe no tempo presente")
A("t-rex", "قوّة عتيقة تطغى، مفترس من فصل أسبق، أو خوف طفولة أُعطي جسد متحف", "poder ultrapassado avassalador, um predador de um capítulo anterior ou um medo de infância ganhando corpo de museu")
A("dinosaur-chasing-you", "قوّة قديمة ما زالت تطارد، عصر ماضٍ يأبى الانقراض، أو رهبة تصير فراراً", "uma força antiga que ainda caça, uma era passada que não aceita ficar extinta ou o assombro virando fuga")
A("friendly-dinosaur", "صلح مع جانب عتيق منك، أو اكتشاف أن القوّة القديمة يمكن المشي إلى جانبها", "fazer as pazes com uma parte ultrapassada de você ou descobrir que o poder antigo pode ser acompanhado")
A("baby-dinosaur", "نمط قديم يبدأ من جديد، أو طبيعة هائلة ما زالت صغيرة بما يكفي لتُحمَل", "um padrão ancestral começando de novo ou uma natureza enorme ainda pequena o bastante para segurar")
A("dead-dinosaur", "عصر انتهى حقّاً، أحفورة ذات سابقة، أو ارتياح أن الشيء الضخم القديم توقّف عن المشي", "uma era de fato encerrada, um fóssil de um eu antigo ou alívio de que a coisa enorme parou de andar")
A("beaver", "بناء دؤوب، سدّ التيّار، عمل أسري، وغريزة صنع بيت بإعادة تشكيل الماء", "construção industriosa, represamento do fluxo, trabalho de família e o instinto de fazer um lar remodelando a água")
A("beaver-dam", "إيقاف تيّار عن قصد، بناء أمان ممّا تقضم، أو حجب العاطفة لصنع بيت", "parar um fluxo de propósito, construir segurança do que você consegue roer ou bloquear a emoção para fazer um lar")
A("beaver-building", "بناء ثابت، عمل يبدو صغيراً قضمة قضمة ويصير بيتاً", "construção firme, um trabalho que parece pequeno mordida a mordida e vira um abrigo")
A("beaver-in-the-house", "غريزة بناء داخل الحياة الخاصّة، أو بنّاء يعيد ترتيب غرف حسبتها منتهية", "instinto industrioso dentro da vida privada ou um construtor rearranjando cômodos que você achava prontos")
A("injured-beaver", "عمل انقطع، بنّاء لا يقدر أن يقضم، أو جهد أسري كلّف أكثر ممّا ينبغي", "trabalho interrompido, um construtor que não consegue roer ou um labor familiar que custou demais")
A("dead-beaver", "دأب انتهى، سدّ لن يُحفَظ، أو حزن على الجانب منك الذي بنى أماناً من التيّار", "indústria encerrada, uma barragem que não será mantida ou luto pela parte de você que construía segurança a partir da corrente")
A("clothes", "الذات التي ترتديها، هويّة عامّة، غطاء، والزيّ الذي يطلبه الدور قبل أن تغادر البيت", "o eu que você veste, identidade pública, cobertura e o traje que um papel exige antes de você sair de casa")
A("shopping-for-clothes", "تجربة ذات مستقبلية، اختيار هويّة عامّة، أو ألا تجد ثوباً يناسب من تصير", "provar um eu futuro, escolher uma identidade pública ou não achar uma peça que caiba em quem você está se tornando")
A("torn-clothes", "دور يتفكّك، انكشاف من تمزّق، أو عرض لم يعد يمسك", "um papel se desfazendo, exposição por um rasgo ou uma apresentação que já não segura")
A("childhood-clothes", "هويّة أقدم ما زالت تناسب أو لا تناسب، دور تجاوزته، أو الجسد يذكر ذاتاً أصغر", "uma identidade mais antiga que ainda cabe ou não, um papel que você cresceu demais ou o corpo lembrando um eu menor")
A("wrong-clothes", "عدم تطابق الدور والذات، حرج اجتماعي، أو الوصول مرتدياً حياة ليست هذه", "descompasso de papel e eu, constrangimento social ou chegar vestido para uma vida que não é esta")
A("new-clothes", "هويّة جديدة، عرض ترقّى، أو ذات لم ترتدها بعد في ضوء النهار", "uma identidade nova, apresentação atualizada ou um eu que você ainda não vestiu à luz do dia")
A("numbers", "قياس، شعور بالقدر، شيفرة تريد فكّها، ورغبة الذهن في جعل الصدفة تبدو رسالة", "medida, sensação de destino, um código que você quer decifrar e o desejo da mente de fazer o acaso parecer recado")
A("repeating-numbers", "نمط لا يُتجاهل، شعور بإشارة، أو الذهن يختم القياس نفسه على الليل", "um padrão que você não ignora, a sensação de um sinal ou a mente carimbando a mesma medida na noite")
A("unlucky-number", "رعب أُعطي رقماً، خرافة تستيقظ، أو قياس تعاملُه كحكم", "pavor ganhando um dígito, uma superstição acordando ou uma medida que você trata como veredito")
A("counting-in-a-dream", "محاولة السيطرة بالقياس، جرد حياة، أو قلق لا يعرف إلا العدّ", "tentar ter controle pela medida, inventariar uma vida ou uma ansiedade que só sabe contar")
A("wrong-number", "صلة فائتة، شيفرة لا تفتح، أو بلوغ المقياس الخطأ لوضع", "uma ligação errada, um código que não abre ou alcançar a medida errada de uma situação")
A("golden-number", "خيال الشيفرة الصحيحة، مفتاح يغيّر كل شيء، أو حظ متنكّر في هيئة حساب", "a fantasia do código certo, uma chave que mudaria tudo ou a sorte vestida de matemática")
A("eyes", "أن ترى وأن تُرى، بصيرة، شهادة، والعضو الذي يقرر ما يُسمَح له بدخول القصّة", "ver e ser visto, percepção, testemunho e o órgão que decide o que entra na história")
A("losing-an-eye", "رفض رؤية، بصيرة مجروحة، أو طريقة نظر أُخذت أو تُركت", "recusar uma vista, percepção ferida ou um jeito de ver que foi tomado ou entregue")
A("someone-watching-you", "شعور بأنك تُشهَد، تدقيق، أو جانب منك يأبى أن ينظر بعيداً", "a sensação de ser testemunhado, escrutínio ou uma parte de você que não desvia o olhar")
A("blindness", "ألا تريد أن ترى، موسم بلا بصيرة، أو حقيقة لا تطيق النظر إليها بعد", "não querer ver, uma estação sem percepção ou uma verdade que você ainda não consegue olhar")
A("third-eye", "بصر داخلي، انتباه روحي، أو ادّعاء رؤية أكثر ممّا يسمح به نهار عادي", "visão interior, atenção espiritual ou a pretensão de ver mais do que o dia comum permite")
A("injured-eyes", "رؤية موجعة، منظور يكلّفك، أو بصيرة جاءت كجرح", "ver com dor, uma vista que te custa ou uma percepção que chegou como ferida")
A("hands", "فاعلية، صنع، لمس، إمساك، والجانب منك الذي يفعل أو يرفض الفعل العملي التالي", "agência, fazer, tocar, segurar e a parte de você que faz ou recusa o próximo ato prático")
A("dirty-hands", "ذنب يُلمَس، عمل يلطّخ، أو شعور أن ما لمسته ليس نظيفاً", "culpa que se sente nas mãos, trabalho que mancha ou a sensação de que o que você tocou não está limpo")
A("injured-hands", "فاعلية مسدودة، صانع لا يقدر أن يصنع، أو ألم في الجزء الذي كان يُفتَرض أن يفعل", "agência bloqueada, um fazedor que não consegue fazer ou dor na parte que deveria agir")
A("holding-hands", "تماس مختار، تحالف، أو رابطة تُرى بأبسط لمس عملي", "contato escolhido, aliança ou um laço tornado visível pelo toque prático mais pequeno")
A("cut-off-hands", "فقدان جذري للفاعلية، عقاب الفعل، أو خوف ألا يُسمَح لك أن تفعل", "perda radical de agência, punição do fazer ou medo de que você não será deixado agir")
A("washing-hands", "رغبة في النقاء من فعل، إعادة ضبط شعائرية، أو أمل البراءة ممّا لمسته أصلاً", "querer limpar-se de um feito, um reset ritual ou o desejo de ser inocente do que você já tocou")
A("crying", "تفريج، حزن يصل في الجسد، شعور وجد ماء أخيراً، وطريقة الليل لإتمام بكاء أجّله النهار", "alívio, luto chegando no corpo, um sentimento que enfim tem água e o jeito da noite de terminar um choro que o dia adiou")
A("crying-in-public", "حزن بلا غرفة خاصّة، خجل من الشعور، أو حاجة لا تنتظر موضعاً أفضل", "luto sem um quarto privado, vergonha de sentir ou uma necessidade que não espera um cenário melhor")
A("unable-to-cry", "تفريج مسدود، شعور عالق خلف العينين، أو خوف ممّا يحدث إن سمحت له بالبدء", "alívio bloqueado, um sentimento travado atrás dos olhos ou medo do que aconteceria se você deixasse começar")
A("someone-else-crying", "حزن مشهود، جانب منك يتكلّم بوجه آخر، أو رعاية لا تعرف كيف تعطيها", "luto testemunhado, uma parte de você falando por outro rosto ou um cuidado que você não sabe como dar")
A("crying-with-relief", "توتّر ينكسر، أمان يصل، أو الجسد يُتمّ نفساً طويلاً محبوساً", "uma tensão quebrando, segurança chegando ou o corpo terminando um fôlego longo que estava preso")
A("inconsolable-crying", "حزن أكبر من العزاء، فقد لا يقبل سبباً، أو شعور يحتاج وقتاً أكثر من نصيحة", "luto maior que o consolo, uma perda que não aceita razão ou um sentimento que precisa de tempo mais do que de conselho")
A("anger", "حرارة تريد هدفاً، حدّ وصل كنار، والشعور الذي لم يُسمَح لك به في الغرفة", "calor que quer um alvo, um limite que chegou como fogo e o sentimento que você não teve permissão de ter na sala")
A("screaming-in-anger", "صوت وجد حجمه أخيراً، حدّ قيل متأخّراً وبصوت عالٍ، أو حرارة ترفض الأدب", "uma voz que enfim tem volume, um limite dito tarde demais e alto demais ou um calor que não fica educado")
A("someone-angry-at-you", "حرارة مُسقَطة، ضمير بوجه، أو نزاع كنت تمتصّه", "calor projetado, uma consciência com rosto ou um conflito que você vinha absorvendo")
A("unable-to-get-angry", "حرارة ابتُلعت، حدّ لا تقدر أن تشكّله، أو أدب كلّفك الشعور الذي احتجت", "calor engolido, um limite que você não consegue formar ou uma educação que te custou o sentimento de que precisava")
A("breaking-things-in-anger", "شعور يحتاج شيئاً يكسره، ضرر ككلام، أو حرارة لا مكان آخر تذهب إليه", "um sentimento que precisa de um objeto, dano como fala ou um calor que não tem para onde ir")
A("calm-after-anger", "حرارة أدّت عملها، حدّ صار مرئيّاً، أو هدوء يلي ناراً لازمة", "calor que fez o seu trabalho, um limite agora visível ou o quieto que segue um fogo necessário")
A("snake-and-water", "وضع عاطفي يحمل تهديداً خفيّاً، أو تحوّل يسير عبر شعور عميق", "uma situação emocional que carrega uma ameaça escondida ou uma transformação se movendo por um sentimento fundo")
A("snake-and-baby", "بداية جديدة هشّة يظلّلها خوف، أو تيقّظ حامٍ حول شيء رقيق", "um começo novo e vulnerável sombreado de medo ou um alerta protetor em torno de algo frágil")
A("snake-and-fire", "تهديد ممتزج بتغيّر سريع: غضب أو إغراء أو تحوّل يبدو خطراً", "uma ameaça combinada com mudança rápida: raiva, tentação ou uma transformação que se sente perigosa")
A("snake-and-house", "تهديد أو تحوّل داخل حياتك الخاصّة أو أسرتك أو أسسك الشخصية", "uma ameaça ou transformação dentro da vida privada, da família ou dos seus alicerces pessoais")
A("snake-and-pregnancy", "قلق وحماية وغريزة مشحونة حول شيء مهمّ ما زال ينمو", "ansiedade, proteção e instinto aguçado em torno de algo importante que ainda está se formando")
A("baby-and-death", "نهاية وبداية متشابكتان: فصل يُغلق بينما يبدأ آخر هشّ", "um fim e um começo entrelaçados: um capítulo fechando enquanto outro, frágil, começa")
A("baby-and-water", "حياة جديدة تحيط بها عاطفة عميقة، أو هشاشة بداية داخل تيّار شعوري متغيّر", "vida nova cercada de emoção funda ou a vulnerabilidade de um começo dentro de uma corrente emocional em mudança")
A("death-and-water", "حزن وإفلات يسيران معاً، أو نهاية تُعالَج عبر عاطفة عميقة", "luto e soltura se movendo juntos ou um fim processado através de uma emoção funda")
A("death-and-fire", "نهاية عبر تدمير وتطهير: شيء يُلتَهم كي يبدأ شيء آخر", "um fim pela destruição e pela purificação: algo consumido para que outra coisa possa começar")
A("spider-and-snake", "شكلان من التهديد معاً: تشابك صبور وضربة مفاجئة، أو ارتياب متراكب", "duas formas de ameaça ao mesmo tempo: enredamento paciente e golpe súbito, ou uma desconfiança em camadas")
A("cat-and-dog", "التوتّر بين الاستقلال والولاء، أو أسلوبان للعلاقة في نزاع", "a tensão entre independência e lealdade ou dois estilos de relação em conflito")
A("dog-and-snake", "ثقة وتهديد جنباً إلى جنب: ولاء يُختبَر، أو إنذار داخل علاقة موثوقة", "confiança e ameaça lado a lado: lealdade testada ou um aviso dentro de uma relação de confiança")
A("wedding-and-death", "التزام ونهاية متشابكان: هويّة قديمة تُغلق مع بدء فصل جديد مُلزِم", "compromisso e fim entrelaçados: uma identidade antiga fechando enquanto um capítulo novo e vinculante começa")
A("wedding-and-blood", "التزام موسوم بثمن أو تضحية أو توتّر أسري، أو اتّحاد يبدو ملطَّخاً بنزاع أو فقد", "um compromisso marcado por custo, sacrifício ou tensão familiar ou uma união que se sente manchada de conflito ou perda")
A("teeth-and-blood", "فقد يكلّف شيئاً حيويّاً: ثقة أو صحّة أو كلمات تجرح وهي تخرج", "uma perda que custa algo vital: confiança, saúde ou palavras que ferem no caminho para fora")
A("fire-and-water", "قوّتان متعارضتان في مشهد واحد: شغف ضد عاطفة، تدمير ضد تجدّد، أو نزاع يطلب توازناً", "forças opostas numa só cena: paixão contra emoção, destruição contra renovação ou um conflito buscando equilíbrio")
A("house-and-water", "عاطفة تفيض إلى الحياة الخاصّة: مشاعر ترتفع داخل الأسرة أو الذاكرة أو الأسس الشخصية", "emoção alagando a vida privada: sentimentos subindo dentro da família, da memória ou dos alicerces pessoais")
