ARPT = {}


def A(slug, ar, pt):
    ARPT[slug] = (ar, pt)


A("snake", "تحوّل، خوف خفي، غريزة، شفاء، ومواقف تستدعي التيقّظ", "transformação, medo escondido, instinto, cura e situações que pedem alerta")
A("black-snake", "تهديد مجهول، خوف مكبوت، غموض، أو تغيّر يصعب قراءته", "uma ameaça desconhecida, medo reprimido, mistério ou uma mudança difícil de ler")
A("white-snake", "حكمة غير مألوفة، صفاء، شفاء، أو حقيقة تأتي في هيئة غير متوقّعة", "sabedoria inesperada, clareza, cura ou uma verdade que chega de um jeito insólito")
A("green-snake", "نمو، تجدّد، غيرة، صحّة، أو غريزة مرتبطة بفرصة جديدة", "crescimento, renovação, ciúme, saúde ou instinto ligado a uma oportunidade nova")
A("snake-bite", "تنبيه مفاجئ، حقيقة موجعة، نزاع، أو مسألة حدود لا تحتمل التأجيل", "um aviso brusco, uma verdade dolorosa, um conflito ou um limite que não pode esperar")
A("dead-snake", "نهاية تهديد، اكتمال تحوّل، أو غريزة كُبتت", "o fim de uma ameaça, uma transformação concluída ou um instinto que foi silenciado")
A("many-snakes", "ضغوط متعدّدة، ارتياب اجتماعي، فرط إثارة، أو تغيّرات تحدث معاً", "várias pressões ao mesmo tempo, desconfiança social, excesso de estímulos ou várias mudanças juntas")
A("big-snake", "خوف أو إغراء أو مسؤولية أو قوّة شخصية يستحيل تجاهلها", "um medo, tentação, responsabilidade ou poder pessoal que já não dá para ignorar")
A("snakes-in-water", "تهديد خفي داخل الشعور، حدس ممتزج بالخوف، أو تغيّر يسير في عاطفة عميقة", "ameaça escondida na emoção, intuição misturada com medo ou uma mudança atravessando um sentimento fundo")
A("teeth", "ثقة، تواصل، مظهر، سيطرة، تقدّم العمر، وقلق من التغيّر أو الفقد", "confiança, comunicação, aparência, controle, o passar do tempo e ansiedade diante da mudança ou da perda")
A("teeth-falling-out", "فقدان السيطرة، حرج، مرحلة انتقال، أو قلق من نظرة الآخرين إليك", "perda de controle, vergonha, uma transição ou preocupação com o jeito que os outros te veem")
A("broken-teeth", "ثقة متصدّعة، ندم بعد نزاع، أو ضغط تجاوز طاقتك", "confiança abalada, arrependimento depois de um conflito ou uma pressão que passou do limite")
A("loose-teeth", "ارتياب، قرار غير ثابت، أو إدراك أن تغيّراً لم يعد يقبل التأجيل", "incerteza, uma decisão instável ou a certeza de que uma mudança não pode mais ser adiada")
A("pulling-teeth", "اختيار فراق موجع، فرض تغيّر، أو إزالة مشكلة بثمن شخصي", "escolher um corte doloroso, forçar uma mudança ou tirar um problema com custo pessoal")
A("rotten-teeth", "شأن أُهمل، خجل باقٍ، كلام يؤذي، أو خوف من تفاقم أمر", "um assunto descuidado, vergonha persistente, palavras que ferem ou medo de que algo piore")
A("losing-teeth", "هشاشة، تقدّم العمر، قلق اجتماعي، أو صعوبة التمسّك بهويّة مألوفة", "vulnerabilidade, o passar dos anos, ansiedade social ou dificuldade de sustentar uma identidade conhecida")
A("water", "عاطفة، حدس، تطهير، ارتياب، وحالة عالمك الداخلي وهي تتغيّر", "emoção, intuição, limpeza, incerteza e o estado cambiante do seu mundo interior")
A("flood", "مشاعر أو مطالب أو تغيّرات تبدو أكبر من طاقتك الآن", "sentimentos, exigências ou mudanças que parecem passar da sua capacidade atual")
A("ocean", "عاطفة شاسعة، حرّية، ارتياب، أو لقاء قوى أكبر من الذات الواعية", "emoção vasta, liberdade, incerteza ou contato com forças maiores que o eu consciente")
A("river", "اتجاه الحياة، جريان الشعور، مرور الزمن، أو حركة في مرحلة انتقال", "a direção da vida, o fluxo emocional, a passagem do tempo ou o movimento numa transição")
A("drowning", "طغيان عاطفي، إرهاق، فقدان السيطرة، أو صعوبة طلب الدعم", "sobrecarga emocional, exaustão, perda de controle ou dificuldade de pedir apoio")
A("dirty-water", "ارتباك، بقايا شعورية، دوافع مختلطة، أو موقف يصعب قراءته بوضوح", "confusão, resíduo emocional, motivos misturados ou uma situação difícil de ler com clareza")
A("clear-water", "سلام، صدق، صفاء عاطفي، تعافٍ، أو ثقة باتجاه حياتك", "paz, honestidade, clareza emocional, recuperação ou confiança na direção da sua vida")
A("rain", "تفريج، تجدّد، حزن، خصوبة، أو تطهير لا يُستعجل", "alívio, renovação, tristeza, fertilidade ou uma limpeza que não se apressa")
A("waterfall", "عاطفة تأتي بقوّة وجمال، سقوط لا يُصعد، أو شعور ينهمر من علو لا يُحبس", "emoção que chega com força e beleza, uma queda que não se sobe ou um sentimento que desaba de uma altura que você não segura")
A("death", "نهايات، تحوّل، حزن، فناء، إفلات، وإغلاق هويّة قديمة", "fins, transformação, luto, mortalidade, soltura e o fechamento de uma identidade antiga")
A("someone-dying", "خوف الفراق، علاقة تتغيّر، حزن، أو إدراك أن شخصاً آخر يتبدّل", "medo da separação, uma relação mudando, luto ou o reconhecimento de que outra pessoa está mudando")
A("dead-person", "ذاكرة، عاطفة لم تُغلق، شوق، عزاء، أو صفات مرتبطة بمن رحل", "memória, emoção inacabada, saudade, consolo ou qualidades ligadas a alguém que morreu")
A("funeral", "الاعتراف بنهاية، تكريم ما مضى، وبدء مسار الوداع", "reconhecer um fim, honrar o que passou e começar o processo de soltar")
A("being-killed", "شعور بالتغليب، تغيّر مفاجئ، إسكات، أو عجز عن ضبط نهاية مهمّة", "sentir-se sobrepujado, mudado de súbito, silenciado ou sem controle sobre um fim importante")
A("killing-someone", "نزاع شديد، صفات مرفوضة، غضب مدفون، أو محاولة عنيفة لإنهاء نمط", "conflito intenso, traços rejeitados, raiva enterrada ou uma tentativa forte de encerrar um padrão")
A("dead-relative", "حزن، ذاكرة عائلية، قيم موروثة، كلام معلّق، أو رغبة في عزاء وصلة", "luto, memória familiar, valores herdados, palavras sem fecho ou um desejo de consolo e ligação")
A("own-death", "نهاية هويّة أو فصل أو دور — لا نبوءة بموت حرفي", "o fim de uma identidade, de um capítulo ou de um papel — não uma previsão de morte literal")
A("dead-parent", "حزن، أحاديث لم تُتم، أنماط موروثة، أو عزاء مرتبط بوالد رحل", "luto, conversas inacabadas, padrões herdados ou o consolo ligado a um pai ou mãe que morreu")
A("baby", "بدايات جديدة، هشاشة، إمكان، مسؤولية، وجانب رقيق من الحياة يحتاج رعاية", "começos novos, vulnerabilidade, potencial, responsabilidade e uma parte terna da vida que pede cuidado")
A("newborn-baby", "إمكان حديث جدّاً، بداية هشّة، أو مسؤولية وصلت للتوّ", "um potencial recém-chegado, um começo frágil ou uma responsabilidade que acabou de nascer")
A("crying-baby", "حاجة عاطفية لم تُلبَّ، مشروع مُهمل، أو شأن هش يطلب الانتباه مباشرة", "uma necessidade emocional sem resposta, um projeto abandonado ou um assunto frágil pedindo atenção agora")
A("baby-boy", "طاقة فاعلة جديدة، ثقة آخذة في الظهور، آمال عائلية، أو بداية بطابع ذكوري", "energia ativa nova, confiança nascendo, esperanças da família ou um começo com tom masculino")
A("baby-girl", "طاقة مستقبِلة جديدة، رقّة، آمال عائلية، أو بداية بطابع أنثوي", "energia receptiva nova, ternura, esperanças da família ou um começo com tom feminino")
A("holding-a-baby", "قبول المسؤولية، حماية إمكان، أو عقد رابطة مع شيء صار مهمّاً للتوّ", "aceitar responsabilidade, proteger um potencial ou criar um laço com algo que acabou de importar")
A("lost-baby", "خوف الفشل، إمكان مُهمل، قلق الفراق، أو ارتياب في رعاية ما يهمّ", "medo de falhar, potencial abandonado, ansiedade de separação ou incerteza sobre cuidar do que importa")
A("pregnancy", "خلق، نماء، ترقّب، مسؤولية، وشيء مهمّ يكبر قبل أن يحين ظهوره", "criação, desenvolvimento, expectativa, responsabilidade e algo importante crescendo antes de estar pronto para nascer")
A("being-pregnant", "حملك أنت لفكرة أو هويّة أو مسؤولية أو تغيّر ما زال يتكوّن", "carregar pessoalmente uma ideia, uma identidade, uma responsabilidade ou uma mudança ainda em formação")
A("pregnancy-test", "انتظار التأكيد، خوف العواقب، أو حاجة إلى وضوح حول إمكان يغيّر الحياة", "esperar uma confirmação, temer as consequências ou precisar de clareza sobre uma possibilidade que muda a vida")
A("giving-birth", "إخراج مشروع أو دور أو علاقة أو مرحلة جديدة إلى واقع ظاهر ومتطلّب", "trazer um projeto, um papel, uma relação ou uma fase nova para uma realidade visível e exigente")
A("miscarriage", "حزن، خوف من إمكان ضائع، خطط انقطعت، أو معالجة تجربة شخصية عميقة", "luto, medo de um potencial perdido, planos interrompidos ou o processamento direto de uma experiência muito íntima")
A("pregnant-woman", "مشاهدة إمكان، الإحساس بتغيّر في آخر، أو إدراك نموّ من حولك", "testemunhar um potencial, sentir mudança em outra pessoa ou reconhecer um crescimento ao seu redor")
A("pregnant-with-twins", "إمكان مزدوج، انقسام الانتباه، أو نماءان يكبران معاً ويتنافسان على الرعاية", "potencial em dobro, atenção dividida ou dois desenvolvimentos crescendo juntos e competindo pelo cuidado")
A("dog", "ولاء، صداقة، حماية، غريزة، رفقة، وحدود تحت الضغط", "lealdade, amizade, proteção, instinto, companhia e limites sob pressão")
A("black-dog", "غريزة مجهولة، حزن، حماية، كآبة، أو حضور وفيّ يصعب فهمه", "instinto desconhecido, luto, proteção, depressão ou uma presença leal difícil de entender")
A("white-dog", "سند موثوق، سلام، حماية، براءة، أو طمأنينة من رابطة مألوفة", "apoio confiável, paz, proteção, inocência ou o consolo de um laço conhecido")
A("dog-bite", "خيانة، حدود مهدَّدة، نزاع، أو غضب يخترق علاقة بُنيت على الثقة", "traição, limites ameaçados, conflito ou raiva furando uma relação feita de confiança")
A("friendly-dog", "رفقة، أمان عاطفي، سند يعتمد عليه، أو راحة مع غرائزك", "companhia, segurança emocional, apoio firme ou conforto com os próprios instintos")
A("aggressive-dog", "غضب دفاعي، نزاع اجتماعي، خوف الخيانة، أو ردّ حماية يخرج عن الضبط", "raiva defensiva, conflito social, medo de traição ou uma resposta protetora que saiu do controle")
A("dead-dog", "حزن، نهاية صداقة، ثقة ضاعت، أو جانب يعتمد عليه في الحياة وقد تبدّل", "luto, o fim de uma amizade, confiança perdida ou uma parte confiável da vida que mudou")
A("cat", "استقلال، حدس، فضول، حسّية، حدود، وعلاقات تأبى الضبط", "independência, intuição, curiosidade, sensualidade, limites e relações que resistem ao controle")
A("black-cat", "غموض، حدس، تفاؤل أو تشاؤم شعبي، استقلال، أو قلق ممّا لا يُتوقَّع تماماً", "mistério, intuição, superstição, independência ou ansiedade com algo que você não prevê por inteiro")
A("white-cat", "حدس لطيف، براءة ظاهرة، مسافة عاطفية، أو شأن خفي تحت سطح هادئ", "intuição suave, inocência aparente, distância emocional ou um assunto sutil sob uma superfície calma")
A("cat-attack", "حدود مخدوشة، نزاع غير مباشر، ارتياب، أو شخص مستقل يقاوم الضغط", "limites arranhados, conflito indireto, desconfiança ou uma pessoa independente resistindo à pressão")
A("kittens", "لعب، استقلال هشّ، مسؤوليات صغيرة، أو فضول جديد يحتاج حماية", "brincadeira, independência frágil, pequenas responsabilidades ou uma curiosidade nova que pede proteção")
A("dead-cat", "استقلال ضائع، حدس مُتجاهَل، حزن، أو نهاية مرحلة خاصّة وحامية للذات", "independência perdida, intuição ignorada, luto ou o fim de uma fase privada e autoprotectora")
A("flying", "حرّية، طموح، منظور، هروب، ثقة، ورغبة في تجاوز الحدود", "liberdade, ambição, perspectiva, fuga, confiança e o desejo de ir além dos limites")
A("flying-high", "طموح كبير، منظور متّسع، ثقة، أو ابتعاد عن هموم الأرض العملية", "grande ambição, perspectiva ampliada, confiança ou distância das preocupações práticas do chão")
A("flying-over-water", "اكتساب منظور على مشاعر قويّة، أو حركة بين الحرّية وعمق العاطفة", "ganhar perspectiva sobre emoções fortes ou transitar entre liberdade e profundidade emocional")
A("flying-without-wings", "فاعلية غير متوقّعة، خيال، إمكان روحي، أو ثقة بلا سند مألوف", "agência inesperada, imaginação, possibilidade espiritual ou confiança sem o apoio de sempre")
A("falling-while-flying", "خوف فقدان النجاح أو المكانة أو الثقة أو السيطرة أو فرصة واعدة", "medo de perder sucesso, prestígio, confiança, controle ou uma oportunidade promissora")
A("falling", "فقدان السيطرة، انعدام الأمن، استسلام، تغيّر مفاجئ، وقلق من الفشل أو ضياع السند", "perda de controle, insegurança, rendição, mudança súbita e ansiedade de falhar ou perder o apoio")
A("falling-from-height", "خوف الفشل بعد تقدّم، فقدان مكانة، أو قلق من مخاطرة بعواقب جدّية", "medo de falhar depois de avançar, perda de prestígio ou ansiedade com um risco de consequências sérias")
A("falling-off-building", "اهتزاز في مجال منظَّم من الحياة: العمل أو السمعة أو الخطط أو الإنجاز", "instabilidade numa área estruturada da vida — trabalho, reputação, planos ou conquista")
A("falling-into-water", "انغماس مفاجئ في العاطفة، استسلام للارتياب، أو فقدان مفاجئ للمسافة الشعورية", "imersão súbita na emoção, rendição à incerteza ou perda abrupta da distância emocional")
A("falling-and-waking-up", "رجفة جسدية، توتّر متراكم، أو خوف يبلغ من الإلحاح ما يقطع النوم", "um sobressalto do corpo, estresse acumulado ou um medo urgente o bastante para interromper o sono")
A("fear-of-heights", "رهاب المرتفعات، انكشاف بعد تقدّم، دوار على حافّة حياة، ورعب فقدان الموطئ", "medo de altura, exposição depois de um avanço, vertigem numa beira da vida e o pavor de perder o chão")
A("being-chased", "تجنّب، ضغط، نزاع معلّق، أمان مهدَّد، ومشكلة تظلّ تطالب بالانتباه", "evitação, pressão, conflito sem fecho, segurança ameaçada e um problema que não para de pedir atenção")
A("chased-by-man", "ضغط مرتبط بسلطة أو نزاع أو قصد مجهول أو حضور ذكوري مهدِّد", "pressão ligada a autoridade, conflito, intenção desconhecida ou uma presença masculina ameaçadora")
A("chased-by-animal", "غريزة، خوف، غضب، رغبة، أو ردّ طبيعي يتجنّبه العقل الواعي", "instinto, medo, raiva, desejo ou uma reação natural que a mente consciente está evitando")
A("chased-by-monster", "خوف مبالغ فيه، خجل، أثر جرح، أو مشكلة كبرت بالتجنّب", "um medo exagerado, vergonha, uma ferida antiga ou um problema que cresceu justamente porque foi evitado")
A("hiding-from-someone", "حماية الذات، سرّية، تجنّب المواجهة، أو حاجة إلى حدّ أكثر أماناً", "autoproteção, segredo, evitação de confronto ou a necessidade de um limite mais seguro")
A("house", "الذات، الأسرة، الخصوصية، الذاكرة، الأسس العاطفية، وغرف الحياة الداخلية", "o eu, a família, a privacidade, a memória, as bases emocionais e os cômodos da vida interior")
A("old-house", "هويّة ماضية، تاريخ عائلي، ذكريات مُهملة، أو أساس يحتاج ترميماً وانتباهاً", "identidade antiga, história familiar, memórias abandonadas ou uma base que pede conserto e atenção")
A("new-house", "هويّة جديدة، ظروف تبدّلت، خطط مستقبل، أو فضاء عاطفي ما زال غريباً", "uma identidade nova, circunstâncias mudadas, planos de futuro ou um espaço emocional ainda estranho")
A("burning-house", "تغيّر عنيف، نزاع عائلي، فيض شعوري، تطهير، أو خوف فقدان الأمان", "mudança intensa, conflito familiar, sobrecarga emocional, purificação ou medo de perder a segurança")
A("empty-house", "وحدة، إمكان غير مستعمل، غياب عاطفي، أو جزء من الذات ينتظر أن يُسكَن", "solidão, potencial sem uso, ausência emocional ou uma parte de si esperando ser habitada")
A("childhood-house", "ذاكرة تكوينيّة، أنماط أسرية، أمان، تاريخ معلّق، أو مقارنة بين الأمس واليوم", "memória formativa, padrões da família, segurança, história sem fecho ou comparação entre o passado e o agora")
A("haunted-house", "ذاكرة عنيدة، خوف لم يُحسم، تاريخ عائلي، أو جانب متجنَّب من عالمك الداخلي", "memória persistente, medo sem resolução, história familiar ou uma parte evitada do seu mundo interior")
A("attic", "ذاكرة مؤرشفة، أفكار غير مستعملة، أو غرفة عليا في الذهن تنتظر أن تُفتح", "memória arquivada, ideias sem uso ou um cômodo alto da mente esperando ser aberto")
A("basement", "شعور مخزون، أسس، أو مادّة أخفيتها وها أنت تهبط للقاها", "sentimento guardado, alicerces ou material que você tirou de vista e agora desce para encontrar")
A("bathroom", "خصوصية، تفريج، تطهير، أو حاجة لا تُقضى والناس ينظرون", "privacidade, alívio, limpeza ou uma necessidade que você não consegue atender com gente olhando")
A("cannot-find-bathroom", "حاجة خاصّة بلا مكان خاصّ — تأجيل الراحة، خجل، أو تأخير نفسك طويلاً", "uma necessidade privada sem lugar privado — alívio adiado, vergonha ou deixar-se por último tempo demais")
A("kitchen", "تغذية، عمل رعاية، حرارة الأسرة، أو الغرفة التي يُعدّ فيها شيء جديد", "nutrição, trabalho de cuidado, o calor da família ou o cômodo onde algo novo está sendo preparado")
A("unused-room", "طاقة لم تُدَّعَ، جزء من الذات لم تعرفه، أو إمكان فارغ في بيتك أنت", "capacidade sem dono, uma parte de si que você não sabia que tinha ou um potencial vazio na sua própria casa")
A("bedroom", "حميمية، راحة، الذات الخاصّة، أو ما يحدث حين تظلم الغرف العامّة", "intimidade, descanso, o eu privado ou o que acontece quando os cômodos públicos apagam")
A("money", "قيمة، أمان، فرصة، تقدير للذات، تبادل، قوّة، وقلق من الموارد المتاحة", "valor, segurança, oportunidade, autoestima, troca, poder e ansiedade com os recursos disponíveis")
A("finding-money", "فرصة غير متوقّعة، قيمة مستعادة، ثقة، أو إدراك مورد تملكه أصلاً", "oportunidade inesperada, valor reencontrado, confiança ou o reconhecimento de um recurso que você já tem")
A("losing-money", "انعدام أمان، فرصة فائتة، طاقة نضبت، أو قلق على القيمة والثبات العملي", "insegurança, oportunidade perdida, energia esgotada ou preocupação com valor e estabilidade prática")
A("coins", "قيمة صغيرة لكن ملموسة، جهد متراكم، خيارات يومية، حظ، أو انتباه للموارد المتواضعة", "valor pequeno mas concreto, esforço acumulado, escolhas do dia a dia, sorte ou atenção a recursos modestos")
A("gold", "قيمة باقية، تطلّع، غنى روحي، مكانة، إغراء، أو شيء ثمين يحتاج تمييزاً", "valor duradouro, aspiração, riqueza espiritual, prestígio, tentação ou algo precioso que pede discernimento")
A("wallet", "هويّة، موارد شخصية، خصوصية، منفذ مالي، أو الوعاء العملي لما تقدّره", "identidade, recursos pessoais, privacidade, acesso financeiro ou o recipiente prático do que você valoriza")
A("stealing-money", "ذنب، تبادل غير عادل، اضطرار، حسد، أو أخذ قيمة بلا شعور راسخ بالاستحقاق", "culpa, troca injusta, desespero, inveja ou tomar valor sem um senso seguro de merecer")
A("spider", "صبر، إبداع، تشابك، خوف، استراتيجية دقيقة، وشبكات تُنسَج من حولك", "paciência, criatividade, enredamento, medo, estratégia cuidadosa e as redes que se tecem ao seu redor")
A("big-spider", "خوف أو نفوذ أو مهمّة إبداعية أو موقف معقّد صار يصعب تجاهله", "um medo, uma influência, uma tarefa criativa ou uma situação complicada que ficou difícil de ignorar")
A("black-spider", "قلق خفي، استراتيجية صبورة، نفوذ مجهول، أو شأن معقّد يعمل في صمت", "ansiedade escondida, estratégia paciente, uma influência desconhecida ou um assunto complicado operando em silêncio")
A("spider-bite", "نزاع صغير لكن نافذ، خيانة، إنذار، أو عاقبة موقف متشابك", "um conflito pequeno mas potente, traição, aviso ou consequência de uma situação enredada")
A("killing-spider", "مواجهة الخوف، إنهاء تلاعب، كسر نمط، أو رفض مسار إبداعي صبور", "enfrentar o medo, encerrar uma manipulação, quebrar um padrão ou recusar um processo criativo paciente")
A("spider-web", "صلة، إبداع، تخطيط دقيق، فخ، أو عواقب نُسجت مع الزمن", "conexão, criatividade, planejamento cuidadoso, armadilha ou consequências tecidas ao longo do tempo")
A("car", "اتجاه، فاعلية، تقدّم، مكانة، سيطرة، وطريقة سيرك في الحياة العملية", "direção, agência, progresso, posição, controle e o jeito como você atravessa a vida prática")
A("car-accident", "تصادم خطط، خوف العواقب، اضطراب مفاجئ، أو قلق على اتجاه الحياة", "colisão de planos, medo das consequências, interrupção súbita ou preocupação com a direção da vida")
A("driving-car", "فاعليتك أنت، مسؤولية، ثقة، ومقدار السيطرة التي تشعر بها على اتجاهك", "agência pessoal, responsabilidade, confiança e quanto controle você sente sobre a direção atual")
A("losing-car", "اتجاه ضائع، استقلال نقص، ارتباك في التقدّم، أو صعوبة بلوغ فاعليتك المعتادة", "direção perdida, independência reduzida, confusão sobre o progresso ou dificuldade de acessar a agência de sempre")
A("stolen-car", "استقلال مُنتهَك، فرصة مسروقة، اضطراب هويّة، أو خوف أن يوجّه غيرك مسارك", "autonomia violada, oportunidade roubada, identidade abalada ou medo de que outra pessoa controle a sua direção")
A("car-crash", "أهداف متضاربة، فشل مفاجئ، ضغط متراكم، أو حاجة ملحّة لتغيير المسار", "metas em conflito, falha abrupta, pressão acumulada ou a urgência de mudar o rumo")
A("brake-failure", "عجز عن الإبطاء، حدود واهية، ضغط يتسارع، أو خوف أن العواقب لا تُوقَف", "incapacidade de desacelerar, limites fracos, pressão acelerando ou medo de que as consequências não parem")
A("buying-a-car", "اختيار اتجاه جديد، الالتزام بموارد، وتقرير أيّ قيادة تريد امتلاكها", "escolher uma direção nova, comprometer recursos e decidir que tipo de condução você topa assumir")
A("passenger-in-car", "سيطرة مُفوَّضة، الركوب في اتجاه غيرك، وشعور الجلوس بينما آخر يقود", "controle delegado, seguir a direção de outra pessoa e o que se sente ao sentar enquanto outro dirige")
A("new-car", "اندفاع جديد، هويّة ترقّت، وانتقال ما زال غريباً بين يديك", "um impulso novo, identidade atualizada e uma transição que ainda parece estranha nas suas mãos")
A("car-keys", "منفذ إلى الحركة، فرصة ناقصة، والشيء الصغير الذي يقرر إن كنت تبدأ أصلاً", "acesso ao movimento, uma oportunidade em falta e o objeto pequeno que decide se você consegue sequer partir")
A("car-in-water", "مسارك يلتقي العاطفة، قيادة غمرها الشعور، أو تقدّم فارق الأرض اليابسة", "o seu caminho encontrando a emoção, um rumo alagado de sentimento ou um progresso que deixou o chão seco")
A("school", "ضغط الأداء، تقييم، نموّ، انتماء اجتماعي، ودروس لم تُغلق من حياة أسبق", "pressão de desempenho, avaliação, crescimento, pertencimento social e lições inacabadas de uma vida anterior")
A("old-school", "حنين، ذكريات معلّقة من مرحلة أسبق، أو مقارنة النموّ الماضي بمكانك الآن", "saudade, memórias sem fecho de uma fase anterior ou comparar o crescimento de outrora com onde você está agora")
A("being-late-to-school", "خوف التخلّف، مسؤولية فائتة، أو قلق من إخلاف توقّع مهمّ", "medo de ficar para trás, responsabilidade perdida ou ansiedade de não cumprir uma expectativa importante")
A("school-exam", "ضغط أداء، شكّ في النفس، أو شعور بأنك غير جاهز لتقييم حقيقي في اليقظة", "pressão de desempenho, dúvida de si ou a sensação de estar despreparado para uma avaliação real na vida acordada")
A("empty-school", "وحدة، مرحلة نموّ توقّفت، أو غياب البنية والسند اللذين كنت تعتمد عليهما", "solidão, uma fase de crescimento pausada ou a falta da estrutura e do apoio de que você dependia")
A("getting-lost-in-school", "ارتباك في الاتجاه، مسار غير واضح، أو صعوبة الإبحار في توقّعات جديدة", "confusão de rumo, um caminho pouco claro ou dificuldade de navegar expectativas novas")
A("childhood-school", "ذاكرة تكوينيّة، هويّة مبكّرة، أو أنماط أسرية واجتماعية تُعلَّم في الصغر", "memória formativa, identidade precoce ou padrões familiares e sociais aprendidos cedo")
A("school-classroom", "تعلّم منظَّم، مقارنة بالأقران، أو موضع يُراقَب فيه أداؤك ويُقاس", "aprendizagem estruturada, comparação com os pares ou um lugar em que o seu desempenho parece vigiado e medido")
A("failing-at-school", "خوف إخفاق الآخرين، نقد الذات، أو قلق من ثغرة جدّية في الكفاءة أو الاستعداد", "medo de decepcionar os outros, autocrítica ou ansiedade com um lapso grave de competência ou preparo")
A("hospital", "هشاشة، شفاء، حاجة ملحّة، اعتماد على الآخرين، ونداء الجسد للرعاية", "vulnerabilidade, cura, urgência, dependência dos outros e o chamado do corpo por atenção e cuidado")
A("being-in-hospital", "هشاشة، اعتماد على الآخرين، أو جانب من الحياة يحتاج رعاية عاجلة", "vulnerabilidade, dependência dos outros ou uma parte da vida que precisa de atenção e cuidado agora")
A("hospital-bed", "راحة مفروضة، تسليم السيطرة، أو تعافٍ بطيء لا يُستعجل", "descanso forçado, entrega do controle ou uma recuperação lenta que não se apressa")
A("visiting-someone-in-hospital", "قلق على آخر، ذنب، أو رغبة في سند شخص في زمن صعب", "preocupação com outra pessoa, culpa ou o desejo de apoiar alguém num tempo difícil")
A("empty-hospital", "عزلة، حاجة رعاية لم تُلبَّ، أو خوف مواجهة أزمة بلا سند", "isolamento, uma necessidade de cuidado sem resposta ou medo de enfrentar uma crise sem apoio")
A("hospital-emergency", "إلحاح، أزمة مفاجئة، خوف فقدان السيطرة، أو مشكلة لم يعد تأجيلها ممكناً", "urgência, crise súbita, medo de perder o controle ou um problema que não dá mais para adiar")
A("surgery-in-hospital", "تغيّر عميق، انكشاف، ثقة بالآخرين، أو تدخّل ضروري لكن مخيف", "mudança profunda, exposição, confiança nos outros ou uma intervenção necessária e assustadora")
A("lost-in-hospital", "ارتباك حول شأن صحّي، صعوبة إيجاد العون، أو تيه في زمن هشّ", "confusão sobre uma questão de saúde, dificuldade de achar ajuda ou desorientação num tempo vulnerável")
A("hospital-room", "صراع خاصّ، تعافٍ، أو انتظار هادئ في وضع شخصي غير محسوم", "um embate privado, recuperação ou a espera quieta numa situação pessoal incerta")
A("church", "إيمان، جماعة، ضمير، شعيرة، والبحث عن معنى أو غفران أو صفاء أخلاقي", "fé, comunidade, consciência, rito e a busca de sentido, perdão ou clareza moral")
A("praying-in-church", "تأمّل صادق، حاجة إلى هدى، أو تسليم عبء أثقل من أن يُحمَل وحدك", "reflexão sincera, necessidade de orientação ou a entrega de um fardo pesado demais para carregar sozinho")
A("empty-church", "وحدة روحية، شكّ، أو فضاء هادئ ينتظر أن يُملأ بمعنى متجدّد", "solidão espiritual, dúvida ou um espaço quieto esperando se encher de um sentido renovado")
A("old-church", "عقيدة موروثة، تقليد، تاريخ عائلي، أو قيم انتقلت عبر زمن طويل", "crença herdada, tradição, história familiar ou valores passados ao longo de muito tempo")
A("church-wedding", "التزام، عهود علنية، أسر تمتزج، أو انتقال مهمّ تشهده الجماعة", "compromisso, votos públicos, famílias que se misturam ou uma transição importante testemunhada pela comunidade")
A("church-bells", "نداء للانتباه، إعلان، إلحاح، أو علامة زمن وشعيرة", "um chamado à atenção, um anúncio, urgência ou um marco de tempo e rito")
A("burning-church", "أزمة إيمان، فقدان أساس أخلاقي، أو اضطراب شديد داخل منظومة اعتقاد", "crise de fé, perda de um alicerce moral ou um abalo intenso dentro de um sistema de crença")
A("church-service", "جماعة، شعيرة مشتركة، مساءلة، أو تأمّل يهديه إطار أوسع للمعنى", "comunidade, rito compartilhado, responsabilidade ou uma reflexão guiada por uma estrutura maior de sentido")
A("abandoned-church", "إيمان ضائع، قيم مُهملة، أو عقيدة كانت مهمّة ولم تعد حيّة", "fé perdida, valores abandonados ou uma crença que já foi importante e não parece mais ativa")
A("cemetery", "حزن، ذاكرة، إغلاق، والحضور الهادئ لما انتهى ولم يُنسَ", "luto, memória, fechamento e a presença quieta do que terminou mas não foi esquecido")
A("walking-through-cemetery", "معالجة الحزن، التأمّل في الفناء، أو السير في ذكريات معلّقة على مهل", "processar o luto, refletir sobre a mortalidade ou atravessar memórias sem fecho no seu próprio ritmo")
A("graveyard", "نهايات، ذاكرة، احترام الماضي، أو مواجهة صادقة للفقد", "fins, memória, respeito pelo passado ou um confronto honesto com a perda")
A("visiting-a-grave", "حزن لم يُتم، رغبة في وصلة، أو تكريم من انتهى أو ما انتهى", "luto inacabado, um desejo de religar ou honrar alguém ou algo que chegou ao fim")
A("open-grave", "فقد متوقَّع، خوف نهاية، أو قلق من تغيّر يبدو نهائياً", "perda antecipada, medo de um fim ou ansiedade com uma mudança que parece definitiva")
A("old-cemetery", "ذاكرة طويلة، تاريخ أسلاف، أو حزن استقرّ في قبول هادئ مع الزمن", "memória antiga, história ancestral ou um luto que assou numa aceitação quieta com o tempo")
A("cemetery-at-night", "خوف المجهول، حزن معلّق، أو قلق يطفو حين تنخفض الدفاعات", "medo do desconhecido, luto sem resolução ou ansiedade que sobe quando as defesas baixam")
A("seeing-your-own-grave", "مواجهة الفناء، تحوّل كبير في الهويّة، أو نهاية رمزية لنسخة قديمة منك", "enfrentar a mortalidade, uma virada grande de identidade ou o fim simbólico de uma versão antiga de você")
A("flowers-on-a-grave", "تحية، حبّ مستمر، إغلاق، أو طريقة رقيقة لتكريم ما فُقد", "tributo, amor que continua, fechamento ou um jeito gentil de honrar o que se perdeu")
A("hotel", "انتقال، هويّة مؤقّتة، خصوصية بين غرباء، وحياة خارج روتينك المعتاد", "transição, identidade temporária, privacidade entre estranhos e a vida fora da sua rotina")
A("staying-in-hotel", "مرحلة مؤقّتة، انتقال، أو هويّة مريحة لكن غير دائمة", "uma fase temporária, uma transição ou uma identidade confortável mas sem permanência")
A("luxury-hotel", "تطلّع، مكافأة، تقدير للذات، أو رغبة في راحة واعتراف", "aspiração, recompensa, autoestima ou o desejo de conforto e reconhecimento")
A("dirty-hotel-room", "خيبة، إهمال للرعاية الذاتية، أو وضع يبدو مقبولاً ويشعر بالخطأ عن قرب", "decepção, autocuidado abandonado ou uma situação que parece aceitável e se sente errada de perto")
A("getting-lost-in-hotel", "تيه أثناء انتقال، أو صعوبة إيجاد ثبات في وضع غير مألوف", "desorientação numa transição ou dificuldade de achar estabilidade numa situação estranha")
A("hotel-elevator", "تغيّر سريع في المكانة أو المزاج، انتقال بين مستويات وضع، أو قلق فقدان السيطرة", "mudança rápida de posição ou humor, trânsito entre níveis de uma situação ou ansiedade de perder o controle")
A("empty-hotel", "عزلة أثناء انتقال، أو مرحلة مؤقّتة تأتي بوحدة غير متوقّعة", "isolamento numa transição ou uma fase temporária que se sente solitária demais")
A("hotel-check-in", "دخول مرحلة جديدة، عرض هويّة للآخرين، أو بدء فصل غير مألوف", "entrar numa fase nova, apresentar uma identidade aos outros ou começar um capítulo desconhecido")
A("strange-hotel-room", "غرابة، هشاشة، أو ضيق من وضع مؤقّت يبدو خارج سيطرتك", "estranheza, vulnerabilidade ou desconforto com uma situação temporária que escapa ao seu controle")
A("airport", "انتقال، رحيل، ترقّب، وضغط التوقيت في تغيّر حياتي كبير", "transição, partida, expectativa e a pressão do tempo numa mudança grande de vida")
A("missing-flight", "خوف فرصة ضائعة، توقيت سيئ، أو قلق من فرصة قد لا تعود", "medo de oportunidade perdida, hora errada ou ansiedade com uma chance que pode não voltar")
A("waiting-at-airport", "ترقّب، خطط معلّقة، أو نفاد صبر أثناء انتقال لم يُحسم", "expectativa, planos suspensos ou impaciência numa transição sem resolução")
A("running-through-airport", "إلحاح، سباق مع الوقت، أو ضغط لمنع خطّة من الانهيار", "urgência, corrida contra o tempo ou pressão para impedir que um plano desmorone")
A("empty-airport", "عزلة أثناء انتقال، أو ارتياب في رحلة تبدو بلا سند", "isolamento numa transição ou incerteza sobre uma viagem que parece sem apoio")
A("airport-security", "تدقيق، انكشاف، أو قلق من الحكم عليك قبل تغيّر مهمّ", "escrutínio, exposição ou ansiedade de ser julgado antes de uma mudança importante")
A("lost-luggage-at-airport", "خوف فقدان موارد أو هويّة أو أجزاء مهمّة منك أثناء انتقال", "medo de perder recursos, identidade ou partes importantes de si numa transição")
A("boarding-a-plane", "الالتزام بتغيّر، قبول اتجاه جديد، أو جاهزية للمضي قدماً", "comprometer-se com uma mudança, aceitar uma direção nova ou a prontidão de seguir em frente")
A("cancelled-flight", "خطط مُوقَفة، إحباط، أو انتقال تأخّر خارج سيطرتك", "planos travados, frustração ou uma transição adiada além do seu controle")
A("prison", "تقييد، ذنب، عجز، ورغبة في الخروج من وضع يبدو بلا مفرّ", "restrição, culpa, impotência e o desejo de ser liberado de uma situação que parece sem saída")
A("being-in-prison", "تقييد، ذنب، أو وضع في اليقظة يبدو بلا مفرّ أو ظالماً في حدوده", "restrição, culpa ou uma situação da vida acordada que parece sem saída ou injustamente limitante")
A("escaping-prison", "رغبة في الحرّية، كسر قيد، أو استعادة السيطرة على وضع خانق", "desejo de liberdade, romper uma limitação ou retomar o controle de uma situação restritiva")
A("visiting-someone-in-prison", "قلق على آخر، ذنب بالتداعي، أو مشاهدة ظروف مقيَّدة لسواك", "preocupação com outra pessoa, culpa por associação ou testemunhar a restrição da vida de alguém")
A("prison-cell", "عزلة، حبس، أو مجموعة خيارات ضيّقة تخنق", "isolamento, confinamento ou um conjunto estreito de escolhas que sufoca")
A("being-wrongly-imprisoned", "ظلم، سوء فهم، أو شعور بأنك تُلام على ما خرج عن يدك", "injustiça, mal-entendido ou a sensação de ser culpado por algo fora do seu controle")
A("prison-guards", "سلطة، رقابة، أو ضغط ممّن يمسك بخياراتك", "autoridade, vigilância ou pressão de alguém que controla as suas escolhas")
A("breaking-out-of-prison", "تمرّد، إلحاح، أو محاولة مصمّمة للخروج من ظرف مقيِّد", "rebeldia, urgência ou uma tentativa determinada de escapar de uma circunstância limitante")
A("locked-in-prison", "عجز، يأس، أو شعور ممتدّ بالحبس بلا حلّ", "impotência, desespero ou a sensação prolongada de estar preso sem resolução")
A("castle", "مكانة، طموح، حماية، عزلة، والمسافة التي يخلقها النفوذ أو الإنجاز", "posição, ambição, proteção, isolamento e a distância que o poder ou a conquista podem criar")
A("old-castle", "مكانة موروثة، تاريخ، تقليد، أو إرث ما زال يشكّل هويّتك", "posição herdada, história, tradição ou um legado que ainda molda a sua identidade")
A("haunted-castle", "تاريخ عائلي معلّق، خوف باقٍ، أو فخامة يظلّلها شيء لم يُتم", "história familiar sem fecho, medo que fica ou uma grandeza sombreada por algo inacabado")
A("living-in-castle", "مكانة محقَّقة، طموح اكتمل، أو راحة تأتي بمسؤولية جديدة", "posição alcançada, ambição cumprida ou o conforto que chega com uma responsabilidade nova")
A("castle-ruins", "مكانة ساقطة، إنجاز ضائع، أو حزن على ما كان قويّاً ثم انحدر", "posição caída, conquista perdida ou luto por algo que já foi poderoso e depois declinou")
A("castle-on-a-hill", "تطلّع، مسافة عن الآخرين، أو هدف مرغوب وصعب المنال معاً", "aspiração, distância dos outros ou um objetivo que parece desejável e difícil de alcançar")
A("entering-a-castle", "الاقتراب من مستوى جديد من المكانة أو الفرصة أو نفوذ غير مألوف", "aproximar-se de um nível novo de posição, oportunidade ou uma posição de influência ainda estranha")
A("being-trapped-in-castle", "عزلة تأتي مع المكانة، جدران حماية صارت قيداً، أو وحدة في القمّة", "o isolamento que vem com a posição, muros protetores que viraram limite ou solidão no topo")
A("royal-castle", "سلطة، إرث، رسمية، أو ضغط مرتبط بموقع قيادة", "autoridade, legado, formalidade ou pressão ligada a uma posição de liderança")
A("beach", "استرخاء، انكشاف عاطفي، ملتقى الحياة الواعية والشعور الأعمق، وحاجة إلى تجدّد", "relaxamento, exposição emocional, o encontro da vida consciente com o sentimento mais fundo e a necessidade de renovação")
A("walking-on-beach", "تأمّل، تقدّم بطيء، أو إيجاد هدوء على حافّة عاطفة قويّة", "reflexão, progresso lento ou achar calma na beira de uma emoção forte")
A("empty-beach", "عزلة، انسحاب هادئ، أو حاجة إلى مساحة بعيداً عن مطالب اليوم", "solidão, recolhimento sereno ou a necessidade de espaço longe das demandas do dia")
A("beach-waves", "إيقاع العاطفة، تحدّيات تتكرّر، أو مدّ وجزر شعور لا تضبطه تماماً", "ritmos da emoção, desafios que se repetem ou a subida e a descida naturais de um sentimento que você não controla por inteiro")
A("stormy-beach", "اضطراب عاطفي على حافّة الوعي، أو ركن هادئ من الحياة تعكّره مشاعر مفاجئة", "turbulência emocional na beira da consciência ou uma área calma da vida perturbada por um sentimento súbito")
A("sunny-beach", "يسر، تفاؤل، مكافأة، أو فترة راحة وصفاء استُحقّت", "leveza, otimismo, recompensa ou um período merecido de descanso e clareza")
A("beach-at-night", "غموض، التفات إلى الداخل، أو أعماق عاطفية لا تظهر إلا حين تنخفض الدفاعات", "mistério, introspecção ou profundezas emocionais que só sobem quando as defesas baixam")
A("finding-something-on-beach", "بصيرة غير متوقّعة، مورد منسي، أو معنى يطفو من تحت الوعي", "uma percepção inesperada, um recurso esquecido ou um sentido emergindo debaixo da consciência")
A("lost-on-beach", "تيه في زمن كان للراحة، أو صعوبة إيجاد اتجاه في فترة هادئة", "desorientação num tempo feito para o descanso ou dificuldade de achar rumo num período calmo")
A("forest", "اللاوعي، الارتياب، الغريزة، النموّ، والأرض المجهولة وراء البنية المألوفة", "o inconsciente, a incerteza, o instinto, o crescimento e o território desconhecido além da estrutura familiar")
A("dark-forest", "خوف المجهول، ارتباك، أو جانب معلّق من اللاوعي", "medo do desconhecido, confusão ou uma parte sem resolução da mente inconsciente")
A("walking-in-forest", "استكشاف، اكتشاف للذات، أو تقدّم ثابت في مرحلة حياة غير محسومة", "exploração, autodescoberta ou progresso firme numa fase incerta da vida")
A("getting-lost-in-forest", "تيه، فقدان الاتجاه، أو صعوبة الثقة بحكمك في أرض غير مألوفة", "desorientação, perda de rumo ou dificuldade de confiar no próprio julgamento em território estranho")
A("burning-forest", "تغيّر مدمّر سريع، قلق فقدان موارد، أو تحوّل يطغى", "mudança destrutiva rápida, ansiedade com perda de recursos ou uma transformação avassaladora")
A("green-forest", "نموّ، حيوية، تجدّد، أو ثقة بمسار طبيعي يسير في وقته", "crescimento, vitalidade, renovação ou confiança num processo natural que se desenrola no próprio tempo")
A("forest-animals", "غريزة، تأثيرات خفية، أو جوانب غير مألوفة منك تظهر في موضع بلا حراسة", "instinto, influências escondidas ou partes desconhecidas de você aparecendo num lugar desprotegido")
A("running-through-forest", "إلحاح، تجنّب، أو حاجة ضاغطة للهرب من تهديد غير واضح", "urgência, evitação ou a necessidade premente de escapar de uma ameaça pouco clara")
A("enchanted-forest", "خيال، إمكان خفي، أو فرصة غير مألوفة تبدو جاذبة وغير محسومة معاً", "imaginação, potencial escondido ou uma oportunidade desconhecida que convida e ao mesmo tempo inquieta")
A("fish", "حدس، موارد عاطفية، وفرة، خصوبة، وأفكار أو مشاعر تسير تحت السطح", "intuição, recursos emocionais, fartura, fertilidade e ideias ou sentimentos se movendo sob a superfície")
A("big-fish", "فرصة كبيرة، طموح مهمّ، أو مورد عاطفي يبدو أكبر من المعتاد", "uma oportunidade grande, uma ambição importante ou um recurso emocional que parece grande demais para ignorar")
A("dead-fish", "فرصة ضائعة، خدر عاطفي، أو مورد أو شعور توقّف نموّه", "oportunidade perdida, entorpecimento emocional ou um recurso ou sentimento que parou de se desenvolver")
A("catching-fish", "جهد ناجح، فرصة أُمسكت، أو بصيرة في شيء كان خفيّاً", "esforço bem-sucedido, oportunidade capturada ou uma percepção sobre algo que estava escondido")
A("swimming-fish", "يسر مع العاطفة، حدس سليم، أو حركة مريحة في حال متغيّر", "facilidade com a emoção, intuição saudável ou movimento confortável por uma situação em mudança")
A("fish-jumping", "بصيرة مفاجئة، فرصة غير متوقّعة، أو عاطفة تقتحم الوعي لحظة", "uma percepção súbita, oportunidade inesperada ou uma emoção que rompe por um instante na consciência")
A("colorful-fish", "عاطفة زاهية، إمكان إبداعي، أو فرصة جذّابة تبرز عن غيرها", "emoção viva, potencial criativo ou uma oportunidade atraente que se destaca")
A("fish-in-clear-water", "صفاء عاطفي، بصيرة صادقة، أو فرصة يسهل التعرّف عليها", "clareza emocional, percepção honesta ou uma oportunidade fácil de reconhecer")
A("fish-tank", "عاطفة محصورة، بيئة مضبوطة، أو مشاعر تُراقَب بأمان من مسافة", "emoção contida, um ambiente controlado ou sentimentos observados com segurança à distância")
A("bird", "حرّية، منظور، تواصل، أمل، ورسائل أو بصيرة تأتي من خارج زاويتك المعتادة", "liberdade, perspectiva, comunicação, esperança e mensagens ou percepções que chegam de fora do seu ponto de vista habitual")
A("flying-bird", "حرّية، طموح، تفاؤل، أو رسالة أمل تصلك في وقتها", "liberdade, ambição, otimismo ou uma mensagem de esperança chegando na hora certa")
A("black-bird", "خبر غير مألوف، غموض، حزن، أو انتقال يأتي في هيئة يصعب قراءتها", "notícia desconhecida, mistério, luto ou uma transição que chega numa forma difícil de ler")
A("white-bird", "سلام، صفاء، طمأنينة روحية، أو علامة أمل في زمن غير محسوم", "paz, clareza, consolo espiritual ou um sinal de esperança num tempo incerto")
A("bird-attack", "نقد مفاجئ، قلق من الحكم عليك، أو رسالة تبدو عدوانية", "crítica súbita, ansiedade de ser julgado ou uma mensagem que chega agressiva")
A("dead-bird", "أمل ضائع، خطّة توقّفت، أو حزن على حرّية أو فرصة انتهت", "esperança perdida, um plano travado ou luto por uma liberdade ou oportunidade que acabou")
A("bird-nest", "بيت، أسرة، تهيئة، أو بناء حذر لأمان شيء جديد", "lar, família, preparo ou a construção cuidadosa de segurança para algo novo")
A("singing-bird", "فرح، تواصل، تشجيع، أو رسالة إيجابية تستحق الانتباه", "alegria, comunicação, ânimo ou uma mensagem positiva que vale a atenção")
A("flock-of-birds", "جماعة، اتجاه مشترك، انتماء اجتماعي، أو حركة جماعية أنت جزء منها أو تشهدها", "comunidade, direção compartilhada, pertencimento social ou um movimento coletivo do qual você faz parte")
A("horse", "قوّة، دافع، حرّية، غريزة، والطاقة التي تحملك نحو هدف مهمّ", "poder, impulso, liberdade, instinto e a energia que te leva a um objetivo importante")
A("white-horse", "صفاء القصد، أمل، أو دافع قوي يهديه نيّة واضحة", "pureza de propósito, esperança ou um impulso poderoso guiado por uma intenção clara")
A("black-horse", "قوّة غير مألوفة، دافع خفي، أو غريزة قويّة لم تُفهم تماماً بعد", "poder desconhecido, impulso escondido ou um instinto forte que ainda não foi compreendido por inteiro")
A("riding-horse", "سيطرة شخصية، ثقة، وقيادة مباشرة لطاقتك واتجاهك", "controle pessoal, confiança e o comando direto da sua própria energia e direção")
A("wild-horse", "طموح جامح، غريزة خام، أو حرّية تأبى البنية والضبط", "ambição indomada, instinto cru ou uma liberdade que resiste à estrutura e ao controle")
A("injured-horse", "طاقة نضبت، تقدّم مسدود، أو دافع قوي أُضعف", "energia esgotada, progresso bloqueado ou um impulso poderoso que foi enfraquecido")
A("dead-horse", "زخم ضائع، نهاية جهد كبير، أو حزن على طموح تُرك", "ímpeto perdido, o fim de um esforço grande ou luto por uma ambição abandonada")
A("horse-race", "منافسة، إلحاح، طموح، أو ضغط لسبق الآخرين نحو هدف", "competição, urgência, ambição ou a pressão de ultrapassar os outros rumo a um objetivo")
A("horse-chasing-you", "دافع يطغى، ضغط من طموحك أنت، أو قوّة تشعر أنها أكبر منك", "impulso avassalador, pressão da própria ambição ou uma força que você sente grande demais")
